## Limits Involving Infinity {#sec:limits_infty}

```{youtube}
id: UVhqWmKqHtw
```

In Definition \ref{def:limit} we stated that in the equation $\lim_{x\to c}f(x) = L$, both $c$ and $L$ were numbers. In this
section we relax that definition a bit by considering situations when it
makes sense to let $c$ and/or $L$ be “infinity.”

As a motivating example, consider $f(x) = 1/x^2$, as shown in Figure
\@ref(fig:oneoverxsquared). Note how, as $x$ approaches 0, $f(x)$ grows
very, very large – in fact, it grows without bound. It seems
appropriate, and descriptive, to state that
$$\lim_{x\rightarrow 0} \frac1{x^2}=\infty.$$ Also note that as $x$ gets
very large, $f(x)$ gets very, very small. We could represent this
concept with notation such as
$$\lim_{x\rightarrow \infty} \frac1{x^2}=0.$$

We explore both types of use of $\infty$ in turn.

### Limits of Infinity and Verical Asymptotes {-}

```{definition, name="Limit of Infinity, $\\infty$", label="limit-of-infinity", echo=TRUE}
Let $I$ be an open interval containing $c$, and let $f$ be a function
defined on $I$, except possibly at $c$.

-   The **limit of $f(x)$, as $x$ approaches $c$, is infinity**, denoted
    by $$\displaystyle \lim_{x\rightarrow c} f(x) = \infty,$$ means that
    given any $N > 0$, there exists $\delta > 0$ such that for all $x$
    in $I$, where $x\neq c$, if $|x - c| < \delta$, then $f(x) >N$.

-   The **limit of $f(x)$, as $x$ approaches $c$, is negative
    infinity**, denoted by
    $$\displaystyle \lim_{x\rightarrow c} f(x) = -\infty,$$ means that
    given any $N < 0$, there exists $\delta > 0$ such that for all $x$
    in $I$, where $x\neq c$, if $|x - c| < \delta$, then $f(x)  < N$.
```

The first definition is similar to the $\epsilon$–$\delta$ definition
from Section \@ref(sec:limitdef). In that definition, given any (small)
value $\epsilon$, if we let $x$ get close enough to $c$ (within $\delta$
units of $c$) then $f(x)$ is guaranteed to be within $\epsilon$ of $L$.
Here, given any (large) value $N$, if we let $x$ get close enough to $c$
(within $\delta$ units of $c$), then $f(x)$ will be at least as large as
$N$. In other words, if we get close enough to $c$, then we can make
$f(x)$ as large as we want. We define limits equal to $-\infty$ in a
similar way.

It is important to note that by saying $\lim_{x\to c}f(x) = \infty$ we
are implicitly stating that *the* limit of $f(x)$, as $x$ approaches
$c$, *does not exist.* A limit only exists when $f(x)$ approaches an
actual numeric value. We use the concept of limits that approach
infinity because it is helpful and descriptive.

We define one-sided limits that approach infinity in a similar way.

```{definition, name="One-Sided Limits of Infinity", label="onesided-limit-of-infinity", echo=TRUE}
As before, one-sided limits are concerned with the values of $x$ on only one side of the point $c$.

-   Let $f$ be a function defined on $(a,c)$ for some $a<c$.
    The **limit of $f(x)$, as $x$ approaches $c$ from the left, is
    infinity**, or, **the left-hand limit of $f$ at $c$ is infinity**,
    denoted by $$\displaystyle \lim_{x\rightarrow c^-} f(x) = \infty,$$
    means given any $N > 0$, there exists $\delta > 0$ such that for all
    $a<x<c$, if $|x - c| < \delta$, then $f(x) >N$.

-   Let $f$ be a function defined on $(c,b)$ for some $b>c$.
    The **limit of $f(x)$, as $x$ approaches $c$ from the right, is
    infinity**, or, **the right-hand limit of $f$ at $c$ is infinity**,
    denoted by $$\displaystyle \lim_{x\rightarrow c^+} f(x) = \infty,$$
    means given any $N > 0$, there exists $\delta > 0$ such that for all
    $c<x<b$, if $|x - c| < \delta$, then $f(x) >N$.

-   The term **left- (or, right-) hand limit of $f$ at c is negative
    infinity** is defined in a manner similar to Definition
    \@ref(def:limit-of-infinity).

```


```{youtube}
id: S3dUAUQiKFQ
```

```{example, name="Evaluating limits involving infinity", label="exinflim1", echo=TRUE}
Find $\displaystyle \lim_{x\rightarrow 1}\frac1{(x-1)^2}$ as shown in
Figure \@ref(fig:inflim1).

In Example \@ref(exm:no-limit2) of Section \@ref(sec:limitintro), by
inspecting values of $x$ close to 1 we concluded that this limit does
not exist. That is, it cannot equal any real number. But the limit could
be infinite. And in fact, we see that the function does appear to be
growing larger and larger, as $f(.99)=10^4$, $f(.999)=10^6$,
$f(.9999)=10^8$. A similar thing happens on the other side of 1. In
general, let a “large” value $N$ be given. Let $\delta=1/\sqrt{N}$. If
$x$ is within $\delta$ of 1, i.e., if $|x-1|<1/\sqrt{N}$, then:
$$\begin{aligned}
    |x-1| &< \frac{1}{\sqrt{N}} \\
    (x-1)^2 &< \frac{1}{N}\\
    \frac{1}{(x-1)^2} &> N,
    \end{aligned}$$ which is what we wanted to show. So we may say
$\displaystyle\lim_{x\rightarrow 1}1/{(x-1)^2}=\infty$.
```


```{geogebra, inflim1}
material_id: q9kc2gtt
caption: "A function that grows without bound as $x \\to 1$."
```


```{youtube}
id: JP1k74FZE1I
```


```{example, name="Evaluating limits involving infinity", label="inflim2", echo=TRUE}
Find $\displaystyle\lim_{x\rightarrow 0}\frac1x$, as shown in Figure
\@ref(fig:oneoverx).

It is easy to see that the function grows without bound near 0, but it
does so in different ways on different sides of 0. Since its behavior is
not consistent, we cannot say that
$\displaystyle \lim_{x\to 0}\frac{1}{x}=\infty$. However, we can make a statement
about one–sided limits. We can state that
$\displaystyle \lim_{x\rightarrow 0^+}\frac1x=\infty$ and
$\displaystyle \lim_{x\rightarrow 0^-}\frac1x=-\infty$.
```

```{geogebra, oneoverx}
material_id: j3qvvphq
caption: "The function $f(x) = 1 / x$."
```

The graphs in the two previous examples demonstrate that if a function
$f$ has a limit (or, left- or right-hand limit) of infinity at $x=c$,
then the graph of $f$ looks similar to a vertical line near $x=c$. This
observation leads to a definition.


```{youtube}
id: qIrLL7jbEZw
```


```{definition, name="Vertical Asymptote", label="vertical-asymptote", echo=TRUE}
Let $I$ be an interval that either contains $c$ or has $c$ as an
endpoint, and let $f$ be a function defined on $I$, except possibly at
$c$.

If the limit of $f(x)$ as $x$ approaches $c$ from either the left or
right (or both) is $\infty$ or $-\infty$, then the line $x=c$ is a
**vertical asymptote** of $f$.
```


```{youtube}
id: h-1BCF_lsHI
```


```{example, name="Finding vertical asymptotes", label="vertasy1", echo=TRUE}
Find the vertical asymptotes of $f(x)=\dfrac{3x}{x^2-4}$.

Vertical asymptotes occur where the function grows without bound; this
can occur at values of $c$ where the denominator is 0. When $x$ is near
$c$, the denominator is small, which in turn can make the function take
on large values. In the case of the given function, the denominator is 0
at $x=\pm 2$. Substituting in values of $x$ close to $2$ and $-2$ seems
to indicate that the function tends toward $\infty$ or $-\infty$ at
those points. We can graphically confirm this by looking at Figure
\@ref(fig:multipleasymptotes). Thus the vertical asymptotes are at
$x=\pm2$.
```
  
```{geogebra, multipleasymptotes}
material_id: mxfmgduv
caption: "The rational function $f(x)=\\dfrac{3x}{x^2-4}$"
```
  
When a rational function has a vertical asymptote at $x=c$, we can
conclude that the denominator is 0 at $x=c$. However, just because the
denominator is 0 at a certain point does not mean there is a vertical
asymptote there. For instance, $f(x)=(x^2-1)/(x-1)$ does not have a
vertical asymptote at $x=1$, as shown in Figure \@ref(fig:noasy). While the
denominator does get small near $x=1$, the numerator gets small too,
matching the denominator step for step. In fact, factoring the
numerator, we get $$f(x)=\frac{(x-1)(x+1)}{x-1}.$$ Canceling the common
term, we get that $f(x)=x+1$ for $x\not=1$. So there is clearly no
asymptote; rather, a hole exists in the graph at $x=1$.

```{geogebra noasy}
material_id: rpbcgjax
caption: "The rational function $f(x)=(x^2-1)/(x-1)$ has no asymptotes."
```

The above example may seem a little contrived. Another example
demonstrating this important concept is $f(x)= (\sin x)/x$. We have
considered this function several times in the previous sections. We
found that $\lim_{x\to0}\frac{\sin x}{x}=1$; i.e., there is no vertical
asymptote. No simple algebraic cancellation makes this fact obvious; we
used the Squeeze Theorem in Section \@ref(sec:limit-analytically) to prove
this.

If the denominator is 0 at a certain point but the numerator is not,
then there will usually be a vertical asymptote at that point. On the
other hand, if the numerator and denominator are both zero at that
point, then there may or may not be a vertical asymptote at that point.
This case where the numerator and denominator are both zero returns us
to an important topic.

### Indeterminate Forms {- #sec:indeterminate-forms}

We have seen how the limits
$$\lim_{x\rightarrow 0}\frac{\sin x}{x}\quad \text{and}\quad \lim_{x\to1}\frac{x^2-1}{x-1}$$
each return the indeterminate form “$0/0$” when we blindly plug in $x=0$
and $x=1$, respectively. However, $0/0$ is not a valid arithmetical
expression. It gives no indication that the respective limits are 1 and
2.

With a little cleverness, one can come up with $0/0$ expressions which
have a limit of $\infty$, 0, or any other real number. That is why this
expression is called *indeterminate*.

A key concept to understand is that such limits do not really return
$0/0$. Rather, keep in mind that we are taking *limits*. What is really
happening is that the numerator is shrinking to 0 while the denominator
is also shrinking to 0. The respective rates at which they do this are
very important and determine the actual value of the limit.

An indeterminate form indicates that one needs to do more work in order
to compute the limit. That work may be algebraic (such as factoring and
canceling) or it may require a tool such as the Squeeze Theorem. In a
later section we will learn a technique called l’Hôspital’s Rule that
provides another way to handle indeterminate forms.

Some other common indeterminate forms are $\infty-\infty$,
$\infty\cdot 0$, $\infty/\infty$, $0^0$, $\infty^0$ and $1^{\infty}$.
Again, keep in mind that these are the “blind” results of evaluating a
limit, and each, in and of itself, has no meaning. The expression
$\infty-\infty$ does not really mean “subtract infinity from infinity.”
Rather, it means “One quantity is subtracted from the other, but both
are growing without bound.” What is the result? It is possible to get
every value between $-\infty$ and $\infty$.

Note that $1/0$ and $\infty/0$ are not indeterminate forms, though they
are not exactly valid mathematical expressions, either. In each, the
function is growing without bound, indicating that the limit will be
$\infty$, $-\infty$, or simply not exist if the left- and right-hand
limits do not match.

### Limits at Infinity and Horizontal Asymptotes {- #sec:horizontal-asymptotes}

```{youtube}
id: 7PwKJHgic7U
```

At the beginning of this section we briefly considered what happens to
$f(x) = 1/x^2$ as $x$ grew very large. Graphically, it concerns the
behavior of the function to the “far right” of the graph. We make this
notion more explicit in the following definition.

```{definition, name="Limits at Infinity and Horizontal Asymptotes", label="limit-at-infinity", echo=TRUE}
Let $L$ be a real number.

1.  Let $f$ be a function defined on $(a,\infty)$ for some number $a$.
    The **limit of $f$ at infinity is $L$**, or
    $\displaystyle\lim_{x\rightarrow\infty} f(x)=L$, means for every $\epsilon>0$
    there exists $M>a$ such that if $x > M$, then $|f(x)-L|<\epsilon$.\

2.  Let $f$ be a function defined on $(-\infty,b)$ for some number $b$.
    The **limit of $f$ at negative infinity is $L$**, or
    $\displaystyle\lim_{x\rightarrow-\infty} f(x)=L$, means for every $\epsilon>0$
    there exists $M<b$ such that if $x < M$, then $|f(x)-L|<\epsilon$.\

3.  If $\displaystyle\lim_{x\rightarrow\infty} f(x)=L$ or
    $\displaystyle\lim_{x\rightarrow-\infty} f(x)=L$, we say the line $y=L$ is a
    **horizontal asymptote** of $f$.
```
    
We can also define limits such as
$\displaystyle\lim_{x\rightarrow\infty}f(x)=\infty$ by combining this definition
with Definition \@ref(def:limit-of-infinity).\


```{youtube}
id: kYmfeq-qKiI
```


```{example, name="Approximating horizontal asymptotes", label="hzasy1", echo=TRUE}
Approximate the horizontal asymptote(s) of $\displaystyle f(x)=\frac{x^2}{x^2+4}$.

We will approximate the horizontal asymptotes by approximating the
limits
$$\lim_{x\to-\infty} \frac{x^2}{x^2+4}\quad \text{and}\quad \lim_{x\to\infty} \frac{x^2}{x^2+4}.$$
Figure \@ref(fig:hzasy1)(a) shows a sketch of $f$, and part (b) gives
values of $f(x)$ for large magnitude values of $x$. It seems reasonable
to conclude from both of these sources that $f$ has a horizontal
asymptote at $y=1$.

Later, we will show how to determine this analytically.
```


Horizontal asymptotes can take on a variety of forms. Figure
\@ref(fig:hzasy)(a) shows that $f(x) = x/(x^2+1)$ has a horizontal
asymptote of $y=0$, where 0 is approached from both above and below.

Figure \@ref(fig:hzasy)(b) shows that $f(x) =x/\sqrt{x^2+1}$ has two
horizontal asymptotes; one at $y=1$ and the other at $y=-1$.

Figure \@ref(fig:hzasy)(c) shows that $f(x) = (\sin x)/x$ has even more
interesting behavior than at just $x=0$; as $x$ approaches $\pm\infty$,
$f(x)$ approaches 0, but oscillates as it does this.\

  ----- ----- -----
              
   (a)   (b)   (c)
  ----- ----- -----

\

We can analytically evaluate limits at infinity for rational functions
once we understand $\lim_{x\rightarrow\infty} 1/x$. As $x$ gets larger
and larger, $1/x$ gets smaller and smaller, approaching 0. We can, in
fact, make $1/x$ as small as we want by choosing a large enough value of
$x$. Given $\epsilon$, we can make $1/x<\epsilon$ by choosing
$x>1/\epsilon$. Thus we have $\lim_{x\rightarrow\infty} 1/x=0$.

It is now not much of a jump to conclude the following:
$$\lim_{x\rightarrow\infty}\frac1{x^n}=0\quad \text{and}\quad \lim_{x\rightarrow-\infty}\frac1{x^n}=0$$

Now suppose we need to compute the following limit:
$$\lim_{x\rightarrow\infty}\frac{x^3+2x+1}{4x^3-2x^2+9}.$$ A good way of
approaching this is to divide through the numerator and denominator by
$x^3$ (hence multiplying by 1), which is the largest power of $x$ to
appear in the function. Doing this, we get $$\begin{aligned}
\lim_{x\rightarrow\infty}\frac{x^3+2x+1}{4x^3-2x^2+9} &=
\lim_{x\rightarrow\infty}\frac{1/x^3}{1/x^3}\cdot\frac{x^3+2x+1}{4x^3-2x^2+9}\\ &=\lim_{x\rightarrow\infty}\frac{x^3/x^3+2x/x^3+1/x^3}{4x^3/x^3-2x^2/x^3+9/x^3}\\ &= \lim_{x\rightarrow\infty}\frac{1+2/x^2+1/x^3}{4-2/x+9/x^3}.\end{aligned}$$
Then using the rules for limits (which also hold for limits at
infinity), as well as the fact about limits of $1/x^n$, we see that the
limit becomes $$\frac{1+0+0}{4-0+0}=\frac14.$$

```{youtube}
id: v5SrtUsdMeU
```

This procedure works for any rational function. In fact, it gives us the
following theorem.

```{theorem, name="Limits of Rational Functions at Infinity", label="lim-rational-fn-at-infty", echo=TRUE}
Let $f(x)$ be a rational function of the following form:
$$f(x)=\frac{a_nx^n + a_{n-1}x^{n-1}+\dots + a_1x + a_0}{b_mx^m + b_{m-1}x^{m-1} + \dots + b_1x + b_0},$$
where any of the coefficients may be 0 except for $a_n$ and $b_m$.

1. If $n=m$, then $\displaystyle\lim_{x\rightarrow\infty} f(x) = \lim_{x\rightarrow-\infty} f(x) = \frac{a_n}{b_m}$.

2. If $n<m$, then $\displaystyle\lim_{x\rightarrow\infty} f(x) = \lim_{x\rightarrow-\infty} f(x) = 0$.

3. If $n>m$, then $\displaystyle\lim_{x\rightarrow\infty} f(x)$ and $\displaystyle\lim_{x\rightarrow-\infty} f(x)$ are both infinite.

```

We can see why this is true. If the highest power of $x$ is the same in
both the numerator and denominator (i.e. $n=m$), we will be in a
situation like the example above, where we will divide by $x^n$ and in
the limit all the terms will approach 0 except for $a_nx^n/x^n$ and
$b_mx^m/x^n$. Since $n=m$, this will leave us with the limit $a_n/b_m$.
If $n<m$, then after dividing through by $x^m$, all the terms in the
numerator will approach 0 in the limit, leaving us with $0/b_m$ or 0. If
$n>m$, and we try dividing through by $x^n$, we end up with all the
terms in the denominator tending toward 0, while the $x^n$ term in the
numerator does not approach 0. This is indicative of some sort of
infinite limit.

Intuitively, as $x$ gets very large, all the terms in the numerator are
small in comparison to $a_nx^n$, and likewise all the terms in the
denominator are small compared to $b_nx^m$. If $n=m$, looking only at
these two important terms, we have $(a_nx^n)/(b_nx^m)$. This reduces to
$a_n/b_m$. If $n<m$, the function behaves like $a_n/(b_mx^{m-n})$, which
tends toward 0. If $n>m$, the function behaves like $a_nx^{n-m}/b_m$,
which will tend to either $\infty$ or $-\infty$ depending on the values
of $n$, $m$, $a_n$, $b_m$ and whether you are looking for
$\lim_{x\rightarrow\infty} f(x)$ or $\lim_{x\rightarrow-\infty} f(x)$.

With care, we can quickly evaluate limits at infinity for a large number
of functions by considering the largest powers of $x$. For instance,
consider again $\displaystyle\lim_{x\to\pm\infty}\frac{x}{\sqrt{x^2+1}},$ graphed
in Figure \@ref(fig:hzasy)(b). When $x$ is very large, $x^2+1 \approx x^2$.
Thus
$$\sqrt{x^2+1}\approx \sqrt{x^2} = |x|,\quad \text{and}\quad \frac{x}{\sqrt{x^2+1}} \approx \frac{x}{|x|}.$$
This expression is 1 when $x$ is positive and $-1$ when $x$ is negative.
Hence we get asymptotes of $y=1$ and $y=-1$, respectively.\

```{youtube}
id: cmZ39j1YI-o
```


```{example, name="Finding a limit of a rational function", label="hzasy2", echo=TRUE}
Confirm analytically that $y=1$ is the horizontal asymptote of
$\displaystyle f(x) = \frac{x^2}{x^2+4}$, as approximated in Example
\@ref(exm:hzasy1).

-----

Before using Theorem \@ref(thm:lim-rational-fn-at-infty), let’s use the
technique of evaluating limits at infinity of rational functions that
led to that theorem. The largest power of $x$ in $f$ is 2, so divide the
numerator and denominator of $f$ by $x^2$, then take limits.
$$\begin{aligned}
\lim_{x\to\infty}\frac{x^2}{x^2+4} 
  &= \lim_{x\to\infty}\frac{x^2/x^2}{x^2/x^2+4/x^2}\\
  &=\lim_{x\to\infty}\frac{1}{1+4/x^2}\\
  &=\frac{1}{1+0}\\
  &= 1.
\end{aligned}$$

We can also use Theorem \@ref(thm:lim-rational-fn-at-infty) directly;
in this case $n=m$ so the limit is the ratio of the leading coefficients
of the numerator and denominator, i.e., 1/1 = 1.
```



```{example, echo=TRUE, name="Finding limits of rational functions", label="hzasy3"}
Use Theorem \@ref(thm:lim-rational-fn-at-infty) to evaluate each of the
following limits.

1.  $\displaystyle\lim_{x\rightarrow-\infty}\frac{x^2+2x-1}{x^3+1}$

2.  $\displaystyle\lim_{x\rightarrow\infty}\frac{x^2+2x-1}{1-x-3x^2}$

1.  $\displaystyle\lim_{x\rightarrow\infty}\frac{x^2-1}{3-x}$

-----

1.  The highest power of $x$ is in the denominator. Therefore, the limit
    is 0; see Figure \@ref(fig:hzasy3)(a).

2.  The highest power of $x$ is $x^2$, which occurs in both the
    numerator and denominator. The limit is therefore the ratio of the
    coefficients of $x^2$, which is $-1/3$. See Figure
    \@ref(fig:hzasy3)(b).

3.  The highest power of $x$ is in the numerator so the limit will be
    $\infty$ or $-\infty$. To see which, consider only the dominant
    terms from the numerator and denominator, which are $x^2$ and $-x$.
    The expression in the limit will behave like $x^2/(-x) = -x$ for
    large values of $x$. Therefore, the limit is $-\infty$. See Figure
    \@ref(fig:hzasy3)(c).
```


```{youtube}
id: vD1-zrRZQTI
```



## Chapter Summary {-}

In this chapter we:

-   defined the limit,

-   found accessible ways to approximate the value of limits numerically
    and graphically,

-   developed a not–so–easy method of proving the value of a limit
    ($\epsilon$-$\delta$ proofs),

-   explored when limits do not exist,

-   defined continuity and explored properties of continuous functions,
    and

-   considered limits that involved infinity.

Why? Mathematics is famous for building on itself and calculus proves to
be no exception. In the next chapter we will be interested in “dividing
by 0.” That is, we will want to divide a quantity by smaller and smaller
numbers and see what value the quotient approaches. In other words, we
will want to find a limit. These limits will enable us to, among other
things, determine *exactly* how fast something is moving when we are
only given position information.

Later, we will want to add up an infinite list of numbers. We will do so
by first adding up a finite list of numbers, then take a limit as the
number of things we are adding approaches infinity. Surprisingly, this
sum often is finite; that is, we can add up an infinite list of numbers
and get, for instance, 42.

These are just two quick examples of why we are interested in limits.
Many students dislike this topic when they are first introduced to it,
but over time an appreciation is often formed based on the scope of its
applicability.
