## Derivatives of Inverse Functions {#sec:deriv_inverse_function}

```{youtube}
id: rBIBiDXbWf8
```

Recall that a function $y=f(x)$ is said to be *one to one* if it passes
the horizontal line test; that is, for two different $x$ values $x_1$
and $x_2$, we do *not* have $f(x_1)=f(x_2)$. In some cases the domain of
$f$ must be restricted so that it is one to one. For instance, consider
$f(x)=x^2$. Clearly, $f(-1)= f(1)$, so $f$ is not one to one on its
regular domain, but by restricting $f$ to $(0,\infty)$, $f$ is one to
one.

Now recall that one to one functions have *inverses*. That is, if $f$ is
one to one, it has an inverse function, denoted by $f\,^{-1}$, such that
if $f(a)=b$, then $f\,^{-1}(b) = a$. The domain of $f\,^{-1}$ is the
range of $f$, and vice-versa. For ease of notation, we set $g=f\,^{-1}$
and treat $g$ as a function of $x$.

Since $f(a)=b$ implies $g(b)=a$, when we compose $f$ and $g$ we get a
nice result: $$f\big(g(b)\big) = f(a) = b.$$ In general,
$f\big(g(x)\big) =x$ and $g\big(f(x)\big) = x$. This gives us a
convenient way to check if two functions are inverses of each other:
compose them and if the result is $x$, then they are inverses (on the
appropriate domains.)

```{youtube}
id: 1g9gAQC301Q
```

```{youtube}
id: PsJKKckGcXE
```

When the point $(a,b)$ lies on the graph of $f$, the point $(b,a)$ lies
on the graph of $g$. This leads us to discover that the graph of $g$ is
the reflection of $f$ across the line $y=x$. In Figure
\@ref(fig:inverse1) we see a function graphed along with its inverse.
See how the point $(1,1.5)$ lies on one graph, whereas $(1.5,1)$ lies on
the other. Because of this relationship, whatever we know about $f$ can
quickly be transferred into knowledge about $g$.

```{geogebra, label="inverse1"}
material_id: ukseqqqg
caption: >
   A function $f$ along with its inverse $f\,^{-1}$. (Note how it
   does not matter which function we refer to as $f$, the other is
   $f\,^{-1}$.)

```

For example, consider Figure \@ref(fig:inverse2) where the tangent line
to $f$ at the point $(a,b)$ is drawn. That line has slope
$f^{\prime}(a)$. Through reflection across $y=x$, we can see that the
tangent line to $g$ at the point $(b,a)$ should have slope
$\displaystyle\frac{1}{f^{\prime}(a)}$. This then tells us that
$\displaystyle g\,'(b) = \frac{1}{f^{\prime}(a)}.$

```{geogebra, label="inverse2"}
material_id: etqqt9pv
caption: >
   Corresponding tangent lines drawn to $f$ and $f\,^{-1}$. Drag the point on the blue line or change the value of $a$ to 
   inspect the relationship between the tangent lines.

```

Consider:

::: {.center}
          Information about $f$                            Information about $g=f\,^{-1}$
  --------------------------------------              -----------------------------------------------------
            (-0.5, 0.375) lies on $f$                    (0.375,-0.5) lies on $g$
   Slope of tangent line to $f$ at $x=-0.5$ is $3/4$   Slope of tangent line to $f$ at $x=0.375$ is $4/3$
         $f^{\prime}(-0.5) = 3/4$                          $g\,'(0.375) = 4/3$
:::

We have discovered a relationship between $f^{\prime}$ and $g\,'$ in a
mostly graphical way. We can realize this relationship analytically as
well. Let $y = g(x)$, where again $g = f\,^{-1}$. We want to find
$\displaystyle y\,'$. Since $y = g(x)$, we know that $f(y) = x$. Using
the Chain Rule and Implicit Differentiation, take the derivative of both
sides of this last equality. $$\begin{aligned}
            \frac{d}{dx}\Big(f(y)\Big) &= \frac{d}{dx}\Big(x\Big) \\
            f^{\prime}(y)\cdot y\,' &= 1\\
            y\,' &= \frac{1}{f^{\prime}(y)}\\
            y\,' &= \frac{1}{f^{\prime}(g(x))}.
        \end{aligned}$$

This leads us to the following theorem.

```{youtube}
id: dOtVBJd75h8
```


```{theorem, label="deriv-inverse-functions", echo=TRUE}

(Derivatives of Inverse Functions). Let $f$ be differentiable and one to
one on an open interval $I$, where $f^{\prime}(x) \neq 0$ for all $x$ in
$I$, let $J$ be the range of $f$ on $I$, let $g$ be the inverse function
of $f$, and let $f(a) = b$ for some $a$ in $I$. Then $g$ is a
differentiable function on $J$, and in particular,

1. $g'(b)=\frac{1}{f'(a)}$
2. $g'(x)=\frac{1}{f'(g(x))}$

```

The results of Theorem \@ref(thm:deriv-inverse-functions) are not
trivial; the notation may seem confusing at first. Careful
consideration, along with examples, should earn understanding.

In the next example we apply Theorem \@ref(thm:deriv-inverse-functions)
to the arcsine function.\

```{youtube}
id: xBZqkvQRSG4
```

```{example, label="deriv-arcsin", echo=TRUE}

(Finding the derivative of an inverse trigonometric function). Let
$y = \arcsin x = \sin^{-1} x$. Find $y\,'$ using Theorem
\@ref(thm:deriv-inverse-functions).

------------------------------------------------------------------------

Adopting our previously defined notation, let $g(x) = \arcsin x$ and
$f(x) = \sin x$. Thus $f^{\prime}(x) = \cos x$. Applying the theorem, we
have $$\begin{aligned}
            g\,'(x) &= \frac{1}{f^{\prime}(g(x))} \\
                        &= \frac{1}{\cos(\arcsin x)}.
            \end{aligned}$$

This last expression is not immediately illuminating. Drawing a figure
will help, as shown in Figure \@ref(fig:inverse3). Recall that the sine
function can be viewed as taking in an angle and returning a ratio of
sides of a right triangle, specifically, the ratio "opposite over
hypotenuse." This means that the arcsine function takes as input a ratio
of sides and returns an angle. The equation $y=\arcsin x$ can be
rewritten as $y=\arcsin (x/1)$; that is, consider a right triangle where
the hypotenuse has length 1 and the side opposite of the angle with
measure $y$ has length $x$. This means the final side has length
$\sqrt{1-x^2}$, using the Pythagorean Theorem.
```

:::{style="float:right;max-width:30%"}
```{tikz, label="inverse3", fig.cap="A right triangle defined by $y=\\sin^{-1}(x/1)$ with the length of the third leg found using the Pythagorean Theorem.", echo=FALSE, dev='png', cache=TRUE}
\begin{tikzpicture}[x=.5\marginparwidth,y=.5\marginparwidth,>=stealth]
\draw (0,0) node [shift={(15pt,5pt)}] {\scriptsize$y$} -- (2,0) node [pos=.5,below] {\scriptsize $\sqrt{1-x^2}$}%
-- (2,1.5) node [pos=.5,right] {\scriptsize $x$} -- (0,0) node [pos=.5,above] {\scriptsize $1$};
\end{tikzpicture}
```
:::

Therefore $\cos (\sin^{-1} x) = \cos y = \sqrt{1-x^2}/1 = \sqrt{1-x^2}$,
resulting in
$$\frac{d}{dx}\big(\arcsin x\big) = g\,'(x) = \frac{1}{\sqrt{1-x^2}}.$$

Remember that the input $x$ of the arcsine function is a ratio of a side
of a right triangle to its hypotenuse; the absolute value of this ratio
will never be greater than 1. Therefore the inside of the square root
will never be negative.

In order to make $y=\sin x$ one to one, we restrict its domain to
$[-\pi/2,\pi/2]$; on this domain, the range is $[-1,1]$. Therefore the
domain of $y=\arcsin x$ is $[-1,1]$ and the range is $[-\pi/2,\pi/2]$.
When $x=\pm 1$, note how the derivative of the arcsine function is
undefined; this corresponds to the fact that as $x\to \pm1$, the tangent
lines to arcsine approach vertical lines with undefined slopes.

```{geogebra, label="inverse4"}
material_id: paqkm3vk
caption: >
   Graphs of $\sin x$ and $\sin^{-1}x$ along with corresponding
   tangent lines.

```

In Figure \@ref(fig:inverse4) we see $f(x) = \sin x$ and
$f\,^{-1}(x) = \sin^{-1} x$ graphed on their respective domains. The
line tangent to $\sin x$ at the point $(\pi/3, \sqrt{3}/2)$ has slope
$\cos \pi/3 = 1/2$. The slope of the corresponding point on
$\sin^{-1}x$, the point $(\sqrt{3}/2,\pi/3)$, is
$$\frac{1}{\sqrt{1-(\sqrt{3}/2)^2}} = \frac{1}{\sqrt{1-3/4}} = \frac{1}{\sqrt{1/4}} = \frac{1}{1/2}=2,$$
verifying yet again that at corresponding points, a function and its
inverse have reciprocal slopes.\
Using similar techniques, we can find the derivatives of all the inverse
trigonometric functions. In the table below we show the
restrictions of the domains of the standard trigonometric functions that
allow them to be invertible.\

```{youtube}
id: lCNZPbfiono
```


:::{style="font-size:smaller;"}

 Function    Domain                      Range                        Inverse Function     Domain                          Range
---------- ---------------------      ------------------------------ ------------------   ----------------------        ----------
$\sin x$   $[-\pi/2, \pi/2]$           $[-1,1]$                      $\sin^{-1} x$         $[-1,1]$                     $[-\pi/2, \pi/2]$
$\cos x$   $[0,\pi]$                   $[-1,1]$                      $\cos^{-1} x$         $[-1,1]$                     $[0,\pi]$
$\tan x$   $(-\pi/2,\pi/2)$            $(-\infty,\infty)$            $\tan^{-1} x$         $(-\infty,\infty)$           $(-\pi/2,\pi/2)$
$\csc x$   $[-\pi/2,0)\cup(0,\pi/2]$   $(-\infty,-1]\cup[1,\infty)$  $\csc^{-1} x$         $(-\infty,-1]\cup[1,\infty)$  $[-\pi/2,0)\cup (0,\pi/2]$
$\sec x$   $[0,\pi/2)\cup(\pi/2,\pi]$ $(-\infty,-1]\cup[1,\infty)$   $\sec^{-1} x$         $(-\infty,-1]\cup[1,\infty)$   $[0,\pi/2)\cup (\pi/2,\pi]$
$\cot x$   $(0,\pi)$                   $(-\infty,\infty)$            $\cot^{-1} x$         $(-\infty,\infty)$           $(0,\pi)$

:::

```{youtube}
id: yO-BT5vEZ9A
```

```{theorem, label="deriv-inverse-trig", echo=TRUE}

(Derivatives of Inverse Trigonometric Functions). The inverse
trigonometric functions are differentiable on all open sets contained in
their domains (as listed in the preceeding table) and their
derivatives are as follows:\

:::{style="columns: 2 300px;"}

1.  $\displaystyle\frac{d}{dx}\big(\sin^{-1} x \big) = \frac{1}{\sqrt{1-x^2}}$

2.  $\displaystyle\frac{d}{dx}\big(\sec^{-1} x \big) = \frac{1}{|x|\sqrt{x^2-1}}$

3.  $\displaystyle\frac{d}{dx}\big(\tan^{-1} x \big) = \frac{1}{1+x^2}$

1.  $\displaystyle\frac{d}{dx}\big(\cos^{-1} x \big) = -\frac{1}{\sqrt{1-x^2}}$

2.  $\displaystyle\frac{d}{dx}\big(\csc^{-1} x \big) = -\frac{1}{|x|\sqrt{x^2-1}}$

3.  $\displaystyle\frac{d}{dx}\big(\cot^{-1} x \big) = -\frac{1}{1+x^2}$

:::   

```

Note how the last three derivatives are merely the opposites of the
first three, respectively. Because of this, the first three are used
almost exclusively throughout this text.\
In Section \@ref(sec:basic-diff-rules), we stated without proof or
explanation that
$\displaystyle\frac{d}{dx}\big(\ln x\big) = \frac{1}{x}$. We can justify
that now using Theorem \@ref(thm:deriv-inverse-functions), as shown in
the example.\

```{youtube}
id: B0C22F6gJD4
```


```{example, label="deriv-lnx", echo=TRUE}

(Finding the derivative of $y=\ln x$). Use Theorem
\@ref(thm:deriv-inverse-functions) to compute
$\displaystyle\frac{d}{dx}\big(\ln x\big)$.

------------------------------------------------------------------------

View $y= \ln x$ as the inverse of $y = e^x$. Therefore, using our
standard notation, let $f(x) = e^x$ and $g(x) = \ln x$. We wish to find
$g\,'(x)$. Theorem \@ref(thm:deriv-inverse-functions) gives:
$$\begin{aligned}
        g\,'(x) &= \frac{1}{f^{\prime}(g(x))} \\
                    &=  \frac{1}{e^{\ln x}}\rule{0pt}{15pt} \\
                    &= \frac{1}{x}.\rule{0pt}{17pt}
        \end{aligned}$$
```


```{youtube}
id: B0C22F6gJD4
```


## Chapter Summary {#chap-2-summary}

In this chapter we have defined the derivative, given rules to
facilitate its computation, and given the derivatives of a number of
standard functions. We restate the most important of these in the
following theorem, intended to be a reference for further work.

```{theorem, label="deriv-glossary", echo=TRUE}

(Glossary of Derivatives of Elementary Functions). Let $u$ and $v$ be
differentiable functions, and let $a$, $c$ and $n$ be real numbers,
$a>0$, $n\neq 0$.\

:::{style="columns: 3 220px;"}

1.  $\frac{d}{dx}\big(cu\big) = cu'$

2.  $\frac{d}{dx}\big(u\cdot v\big) = uv'+u'v$

3.  $\frac{d}{dx}\big(u(v)\big) = u'(v)v'$

4.  $\frac{d}{dx}\big(x\big) = 1$

5.  $\frac{d}{dx}\big(e^x\big) = e^x$

6.  $\frac{d}{dx}\big(\ln x\big) = \frac{1}{x}$

7.  $\frac{d}{dx}\big(\sin x\big) = \cos x$

8.  $\frac{d}{dx}\big(\sec x\big) = \sec x\tan x$

9.  $\frac{d}{dx}\big(\tan x\big) = \sec^2x$

10. $\frac{d}{dx}\big(\sin^{-1}x\big) = \frac{1}{\sqrt{1-x^2}}$

11. $\frac{d}{dx}\big(\sec^{-1}x\big) = \frac{1}{|x|\sqrt{x^2-1}}$

12. $\frac{d}{dx}\big(\tan^{-1}x\big) = \frac{1}{1+x^2}$

1.  $\frac{d}{dx}\big(u\pm v\big) = u'\pm v'$

2.  $\frac{d}{dx}\big(\frac uv\big) = \frac{u'v-uv'}{v^2}$

3.  $\frac{d}{dx}\big(c\big) = 0$

4.  $\frac{d}{dx}\big(x^n\big) = nx^{n-1}$

5.  $\frac{d}{dx}\big(a^x\big) = \ln a\cdot a^x$

6.  $\frac{d}{dx}\big(\log_a x\big) = \frac{1}{\ln a}\cdot\frac{1}{x}$

7.  $\frac{d}{dx}\big(\cos x\big) = -\sin x$

8.  $\frac{d}{dx}\big(\csc x\big) = -\csc x\cot x$

9.  $\frac{d}{dx}\big(\cot x\big) = -\csc^2x$

10. $\frac{d}{dx}\big(\cos^{-1}x\big) = -\frac{1}{\sqrt{1-x^2}}$

11. $\frac{d}{dx}\big(\csc^{-1}x\big) = -\frac{1}{|x|\sqrt{x^2-1}}$

12. $\frac{d}{dx}\big(\cot^{-1}x\big) = -\frac{1}{1+x^2}$

:::

```
