## The Chain Rule {#sec:chainrule}

We have covered almost all of the derivative rules that deal with
combinations of two (or more) functions. The operations of addition,
subtraction, multiplication (including by a constant) and division led
to the Sum and Difference rules, the Constant Multiple Rule, the Power
Rule, the Product Rule and the Quotient Rule. To complete the list of
differentiation rules, we look at the last way two (or more) functions
can be combined: the process of composition (i.e. one function "inside"
another).

One example of a composition of functions is $f(x) = \cos(x^2).$ We
currently do not know how to compute this derivative. If forced to
guess, one would likely guess $f^{\prime}(x) = -\sin(2x)$, where we
recognize $-\sin x$ as the derivative of $\cos x$ and $2x$ as the
derivative of $x^2.$ However, this is not the case;
$f^{\prime}(x)\neq -\sin(2x).$ In Example \@ref(exm:chain7ex) we'll see
the correct answer, which employs the new rule this section introduces,
the **Chain Rule**.

Before we define this new rule, recall the notation for composition of
functions. We write $(f \circ g)(x)$ or $f(g(x))$, read as "$f$ of $g$
of $x$," to denote composing $f$ with $g.$ In shorthand, we simply write
$f \circ g$ or $f(g)$ and read it as "$f$ of $g.$" Before giving the
corresponding differentiation rule, we note that the rule extends to
multiple compositions like $f(g(h(x)))$ or $f(g(h(j(x))))$, etc.

To motivate the rule, let's look at three derivatives we can already
compute.\

```{example, label="chain1", echo=TRUE}

(Exploring similar derivatives). Find the derivatives of
$F_1(x) = (1-x)^2$, $F_2(x) = (1-x)^3,$ and $F_3(x) = (1-x)^4.$ (We'll
see later why we are using subscripts for different functions and an
uppercase $F.$)

------------------------------------------------------------------------

In order to use the rules we already have, we must first expand each
function as $F_1(x) = 1 - 2x + x^2$, $F_2(x) = 1 - 3x + 3x^2 - x^3$ and
$F_3(x) = 1 - 4x + 6x^2 - 4x^3 + x^4.$

It is not hard to see that:\
$F\hskip.5pt_1'(x) = -2 + 2x$,

$F\hskip.5pt_2'(x) = -3 + 6x - 3x^2$ and

$F\hskip.5pt_3'(x) = -4 + 12x - 12x^2 + 4x^3.$\
An interesting fact is that these can be rewritten as
$$F\hskip.5pt_1'(x) = -2(1-x),\quad  F\hskip.5pt_2'(x) = -3(1-x)^2\ \textrm{ and } \ 
F\hskip.5pt_3'(x) = -4(1-x)^3.$$ A pattern might jump out at you; note
how the we end up multiplying by the old power and the new power is
reduced by 1. We also always multiply by $(-1).$

Recognize that each of these functions is a composition, letting
$g(x) = 1-x$: $$\begin{aligned}
F_1(x) = f_1(g(x)),& \text{ where } f_1(x) = x^2,\\
F_2(x) = f_2(g(x)),& \text{ where } f_2(x) = x^3,\\
F_3(x) = f_3(g(x)),& \text{ where } f_3(x) = x^4.\end{aligned}$$

We'll come back to this example after giving the formal statements of
the Chain Rule; for now, we are just illustrating a pattern.

```

\
When composing functions, we need to make sure that the new function is
actually defined. For instance, consider $f(x) = \sqrt{x}$ and
$g(x) = -x^2-1.$ The domain of $f$ excludes all negative numbers, but
the range of $g$ is only negative numbers. Therefore the composition
$f\big(g(x)\big) = \sqrt{-x^2-1}$ is not defined for any $x$, and hence
is not differentiable.

The following definition takes care to ensure this problem does not
arise. We'll focus more on the derivative result than on the
domain/range conditions.

```{theorem, label="chain-rule", echo=TRUE}

(The Chain Rule). Let $g$ be a differentiable function on an interval
$I$, let the range of $g$ be a subset of the interval $J$, and let $f$
be a differentiable function on $J.$ Then $y=f(g(x))$ is a
differentiable function on $I$, and
$$y\,' = f^{\prime}(g(x))\cdot g\,'(x).$$

```

To help understand the Chain Rule, we return to Example
\@ref(exm:chain1).\

```{example, label="chain2", echo=TRUE}

(Using the Chain Rule). Use the Chain Rule to find the derivatives of
the following functions, as given in Example \@ref(exm:chain1).

------------------------------------------------------------------------

Example \@ref(exm:chain1) ended with the recognition that each of the
given functions was actually a composition of functions. To avoid
confusion, we ignore most of the subscripts here.\

------------

$$F_1(x) = (1-x)^2$$

We found that
$$y=(1-x)^2 = f(g(x)), \text{ where } f(x) = x^2\ \text{ and }\ g(x) = 1-x.$$
To find $y\,'$, we apply the Chain Rule. We need $f^{\prime}(x)=2x$ and
$g\,'(x)=-1.$

Part of the Chain Rule uses $f^{\prime}(g(x)).$ This means substitute
$g(x)$ for $x$ in the equation for $f^{\prime}(x).$ That is,
$f^{\prime}(x) = 2(1-x).$ Finishing out the Chain Rule we have
$$y\,' = f^{\prime}(g(x))\cdot g\,'(x) = 2(1-x)\cdot (-1) = -2(1-x)= 2x-2.$$

--------------------    
    
$$F_2(x) = (1-x)^3$$

Let $y = (1-x)^3 = f(g(x))$, where $f(x) = x^3$ and $g(x) = (1-x).$ We
have $f^{\prime}(x) = 3x^2$, so $f^{\prime}(g(x)) = 3(1-x)^2.$ The Chain
Rule then states
$$y\,' = f^{\prime}(g(x))\cdot g\,'(x) = 3(1-x)^2\cdot(-1) = -3(1-x)^2.$$

----------------    
    
    
$$F_3(x) = (1-x)^4$$

Finally, when $y = (1-x)^4$, we have $f(x)= x^4$ and $g(x) = (1-x).$
Thus $f^{\prime}(x) = 4x^3$ and $f^{\prime}(g(x)) = 4(1-x)^3.$ Thus
$$y\,' = f^{\prime}(g(x))\cdot g\,'(x) = 4(1-x)^3\cdot (-1) = -4(1-x)^3.$$

```

\
Example \@ref(exm:chain2) demonstrated a particular pattern: when
$f(x)=x^n$, then $y\,' =n\cdot (g(x))^{n-1}\cdot g\,'(x).$ This is
called the Generalized Power Rule.\

```{theorem, label="gen-power-rule", echo=TRUE}

(Generalized Power Rule). Let $g(x)$ be a differentiable function and
let $n\neq 0$ be an integer. Then
$$\frac{d}{dx}\Big(g(x)^n\Big) = n\cdot \big(g(x)\big)^{n-1}\cdot g\,'(x).$$

```

This allows us to quickly find the derivative of functions like
$y = (3x^2-5x+7+\sin x)^{20}.$ While it may look intimidating, the
Generalized Power Rule states that
$$y\,' = 20(3x^2-5x+7+\sin x)^{19}\cdot (6x-5+\cos x).$$

Treat the derivative--taking process step--by--step. In the example just
given, first multiply by 20, then rewrite the inside of the parentheses,
raising it all to the 19$^{\text{th}}$ power. Then think about the
derivative of the expression inside the parentheses, and multiply by
that.

We now consider more examples that employ the Chain Rule.\

```{example, label="chain3", echo=TRUE}

(Using the Chain Rule). Find the derivatives of the following functions:

1.  $y = \sin{2x}$

1.  $y= \ln (4x^3-2x^2)$

1.  $y = e^{-x^2}$

------------------------------------------------------------------------

1.  Consider $y = \sin 2x.$ Recognize that this is a composition of
    functions, where $f(x) = \sin x$ and $g(x) = 2x.$ Thus
    $$y\,' = f^{\prime}(g(x))\cdot g\,'(x) = \cos (2x)\cdot 2 = 2\cos 2x.$$

2.  Recognize that $y = \ln (4x^3-2x^2)$ is the composition of
    $f(x) = \ln x$ and $g(x) = 4x^3-2x^2.$ Also, recall that
    $$\frac{d}{dx}\Big(\ln x\Big) = \frac{1}{x}.$$ This leads us to:
    $$y\,' = \frac{1}{4x^3-2x^2} \cdot (12x^2-4x) = \frac{12x^2-4x}{4x^3-2x^2}= \frac{4x(3x-1)}{2x(2x^2-x)} = \frac{2(3x-1)}{2x^2-x}.$$

3.  Recognize that $y = e^{-x^2}$ is the composition of $f(x) = e^x$ and
    $g(x) = -x^2.$ Remembering that $f^{\prime}(x) = e^x$, we have
    $$y\,' = e^{-x^2}\cdot (-2x) = (-2x)e^{-x^2}.$$

```



```{example, label="chain7ex", echo=TRUE}

(Using the Chain Rule to find a tangent line). Let $f(x) = \cos x^2.$
Find the equation of the line tangent to the graph of $f$ at $x=1.$

------------------------------------------------------------------------

The tangent line goes through the point $(1,f(1)) \approx (1,0.54)$ with
slope $f^{\prime}(1).$ To find $f^{\prime}$, we need the Chain Rule.

$f^{\prime}(x) = -\sin(x^2) \cdot(2x) = -2x\sin x^2.$ Evaluated at
$x=1$, we have $f^{\prime}(1) = -2\sin 1\approx -1.68.$ Thus the
equation of the tangent line is $$y = -1.68(x-1)+0.54 .$$

The tangent line is sketched along with $f$ in Figure \@ref(fig:chain7).

```

```{geogebra, label="chain7"}

caption: >
    $f(x) = \cos x^2$ sketched along with its tangent line at $x=1.$

```

The Chain Rule is used often in taking derivatives. Because of this, one
can become familiar with the basic process and learn patterns that
facilitate finding derivatives quickly. For instance,
$$\frac{d}{dx}\Big(\ln (\text{anything})\Big) = \frac{1}{\text{anything}}\cdot (\text{anything})' = \frac{(\text{anything})'}{\text{anything}}.$$
A concrete example of this is
$$\frac{d}{dx}\Big(\ln(3x^{15}-\cos x+e^x)\Big) = \frac{45x^{14}+\sin x+e^x}{3x^{15}-\cos x+e^x}.$$
While the derivative may look intimidating at first, look for the
pattern. The denominator is the same as what was inside the natural log
function; the numerator is simply its derivative.

This pattern recognition process can be applied to lots of functions. In
general, instead of writing "anything", we use $u$ as a generic function
of $x.$ We then say $$\frac{d}{dx}\Big(\ln u\Big) = \frac{u\,'}{u}.$$
The following is a short list of how the Chain Rule can be quickly
applied to familiar functions.

1.  $\displaystyle\frac{d}{dx}\Big(u^n\Big) = n\cdot u^{n-1}\cdot u\,'.$

2.  $\displaystyle\frac{d}{dx}\Big(e^u\Big) = u\,'\cdot e^u.$

3.  $\displaystyle\frac{d}{dx}\Big(\sin u\Big) = u\,'\cdot \cos u.$

1.  $\displaystyle\frac{d}{dx}\Big(\cos u\Big) = -u\,'\cdot \sin u.$

2.  $\displaystyle\frac{d}{dx}\Big(\tan u\Big) = u\,'\cdot \sec^2 u.$

Of course, the Chain Rule can be applied in conjunction with any of the
other rules we have already learned. We practice this next.\

```{example, label="chain4", echo=TRUE}
(Using the Product, Quotient and Chain Rules). Find the derivatives of
the following functions.\
1. $f(x) = x^5 \sin{2x^3}$ .
$\displaystyle f(x) = \frac{5x^3}{e^{-x^2}}.$

------------------------------------------------------------------------

1.  We must use the Product and Chain Rules. Do not think that you must
    be able to "see" the whole answer immediately; rather, just proceed
    step--by--step.
    $$f^{\prime}(x) = x^5\big(6x^2\cos 2x^3\big) + 5x^4\big(\sin 2x^3\big)= 6x^7\cos 2x^3+5x^4\sin 2x^3.$$

2.  We must employ the Quotient Rule along with the Chain Rule. Again,
    proceed step--by--step. $$\begin{aligned}
    f^{\prime}(x) = \frac{e^{-x^2}\big(15x^2\big) - 5x^3\big((-2x)e^{-x^2}\big)}{\big(e^{-x^2}\big)^2} &=\frac{e^{-x^2}\big(10x^4+15x^2\big)}{e^{-2x^2}}\\
     &= e^{x^2}\big(10x^4+15x^2\big).\end{aligned}$$

```


A key to correctly working these problems is to break the problem down
into smaller, more manageable pieces. For instance, when using the
Product and Chain Rules together, just consider the first part of the
Product Rule at first: $f(x)g\,'(x).$ Just rewrite $f(x)$, then find
$g\,'(x).$ Then move on to the $f^{\prime}(x)g(x)$ part. Don't attempt
to figure out both parts at once.

Likewise, using the Quotient Rule, approach the numerator in two steps
and handle the denominator after completing that. Only simplify
afterward.

We can also employ the Chain Rule itself several times, as shown in the
next example.\

```{example, label="chain6", echo=TRUE}

(Using the Chain Rule multiple times). Find the derivative of
$y = \tan^5(6x^3-7x).$

------------------------------------------------------------------------

Recognize that we have the $g(x)=\tan(6x^3-7x)$ function "inside" the
$f(x)=x^5$ function; that is, we have $y = \big(\tan(6x^3-7x)\big)^5.$
We begin using the Generalized Power Rule; in this first step, we do not
fully compute the derivative. Rather, we are approaching this
step--by--step. $$y\,' = 5\big(\tan(6x^3-7x)\big)^4\cdot g\,'(x).$$ We
now find $g\,'(x).$ We again need the Chain Rule;
$$g\,'(x) = \sec^2(6x^3-7x)\cdot(18x^2-7).$$ Combine this with what we
found above to give $$\begin{aligned}
y\,' &= 5\big(\tan(6x^3-7x)\big)^4\cdot\sec^2(6x^3-7x)\cdot(18x^2-7)\\ 
&= (90x^2-35)\sec^2(6x^3-7x)\tan^4(6x^3-7x).\end{aligned}$$

This function is frankly a ridiculous function, possessing no real
practical value. It is very difficult to graph, as the tangent function
has many vertical asymptotes and $6x^3-7x$ grows so very fast. The
important thing to learn from this is that the derivative can be found.
In fact, it is not "hard;" one can take several simple steps and should
be careful to keep track of how to apply each of these steps.

```

\
It is a traditional mathematical exercise to find the derivatives of
arbitrarily complicated functions just to demonstrate that it *can be
done*. Just break everything down into smaller pieces.\

```{example, label="chain5", echo=TRUE}

(Using the Product, Quotient and Chain Rules). Find the derivative of
$\displaystyle f(x) = \frac{x\cos(x^{-2})-\sin^2(e^{4x})}{\ln(x^2+5x^4)}.$

------------------------------------------------------------------------

This function likely has no practical use outside of demonstrating
derivative skills. The answer is given below without simplification. It
employs the Quotient Rule, the Product Rule, and the Chain Rule three
times.\
$f^{\prime}(x) =$
$$\frac{\left(\begin{array}{l}\ln(x^2+5x^4)\cdot\Big[\big(x\cdot(-\sin(x^{-2}))\cdot(-2x^{-3})+1\cdot \cos(x^{-2})\big)-2\sin(e^{4x})\cdot\cos(e^{4x})\cdot(4e^{4x})\Big]\\
\qquad-\Big(x\cos(x^{-2})-\sin^2(e^{4x})\Big)\cdot\frac{2x+20x^3}{x^2+5x^4}\end{array}\right)}{\big(\ln(x^2+5x^4)\big)^2}.$$

The reader is highly encouraged to look at each term and recognize why
it is there. (I.e., the Quotient Rule is used; in the numerator,
identify the "LOdHI" term, etc.) This example demonstrates that
derivatives can be computed systematically, no matter how arbitrarily
complicated the function is.

```

\
The Chain Rule also has theoretic value. That is, it can be used to find
the derivatives of functions that we have not yet learned as we do in
the following example.\

```{example, label="chain8", echo=TRUE}

(The Chain Rule and exponential functions). Use the Chain Rule to find
the derivative of $y= 2^x.$

------------------------------------------------------------------------

We only know how to find the derivative of one exponential function,
$y = e^x.$ We can accomplish our goal by rewriting $2$ in terms of $e.$
Recalling that $e^x$ and $\ln x$ are inverse functions, we can write
$$2=e^{\ln 2} \quad \text{and so }\quad y=2^x = \big(e^{\ln 2}\big)^x = e^{x(\ln 2)}.$$

The function is now the composition $y=f(g(x))$, with $f(x) = e^x$ and
$g(x) = x(\ln 2).$ Since $f^{\prime}(x) = e^x$ and $g\,'(x) = \ln 2$,
the Chain Rule gives

$$y\,' = e^{x (\ln 2)} \cdot \ln 2.$$ Recall that the $e^{x(\ln 2)}$
term on the right hand side is just $2^x$, our original function. Thus,
the derivative contains the original function itself. We have
$$y\,' = y \cdot \ln 2 = 2^x\cdot \ln 2.$$ We can extend this process to
use any base $a$, where $a>0$ and $a\neq 1.$ All we need to do is
replace each "2" in our work with "$a.$" The Chain Rule, coupled with
the derivative rule of $e^x$, allows us to find the derivatives of all
exponential functions.

```

\
The comment at the end of previous example is important and is restated
formally as a theorem.

```{theorem, label="exponentials", echo=TRUE}

(Derivatives of Exponential Functions). Let $f(x)=a^x$, for
$a>0, a\neq 1.$ Then $f$ is differentiable for all real numbers (i.e.,
differentiable everywhere) and $$f^{\prime}(x) = \ln a\cdot a^x.$$

```

**Alternate Chain Rule Notation**\
It is instructive to understand what the Chain Rule "looks like" using
"$\frac{dy}{dx}$" notation instead of $y\,'$ notation. Suppose that
$y=f(u)$ is a function of $u$, where $u=g(x)$ is a function of $x$, as
stated in Theorem \@ref(thm:chain-rule). Then, through the composition
$f \circ g$, we can think of $y$ as a function of $x$, as $y=f(g(x)).$
Thus the derivative of $y$ with respect to $x$ makes sense; we can talk
about $\frac{dy}{dx}.$ This leads to an interesting progression of
notation:

$$\begin{aligned}
y\,' &= f^{\prime}(g(x))\cdot g\,'(x) \\
\frac{dy}{dx} &= \displaystyle y\,'(u) \cdot u\,'(x) \text{ (since $y=f(u)$ and $u=g(x)$)}\\
\frac{dy}{dx} &= \displaystyle\frac{dy}{du} \cdot \frac{du}{dx}  \text{ (using "fractional" notation for the derivative)}\end{aligned}$$

Here the "fractional" aspect of the derivative notation stands out. On
the right hand side, it seems as though the "$du$" terms cancel out,
leaving $$\frac{dy}{dx} = \frac{dy}{dx}.$$ It is important to realize
that we *are not* canceling these terms; the derivative notation of
$\frac{dy}{du}$ is one symbol. It is equally important to realize that
this notation was chosen precisely because of this behavior. It makes
applying the Chain Rule easy with multiple variables. For instance,

$$\frac{dy}{dt} = \frac{dy}{d\bigcirc} \cdot \frac{d\bigcirc}{d\triangle} \cdot \frac{d\triangle}{dt}.$$
where $\bigcirc$ and $\triangle$ are any variables you 'd like to use.

One of the most common ways of "visualizing " the Chain Rule is to
consider a set of gears, as shown in Figure \@ref(fig:chainrulegears).
The gears have 36, 18, and 6 teeth, respectively. That means for every
revolution of the $x$ gear, the $u$ gear revolves twice. That is, the
rate at which the $u$ gear makes a revolution is twice as fast as the
rate at which the $x$ gear makes a revolution. Using the terminology of
calculus, the rate of $u$-change, with respect to $x$, is
$\frac{du}{dx} = 2.$

```{geogebra, label="chainrulegears"}

caption: >
    A series of gears to demonstrate the Chain Rule. Note how 
    $\frac{dy}{dx} = \frac{dy}{du}\cdot\frac{du}{dx}$

```

Likewise, every revolution of $u$ causes 3 revolutions of $y$:
$\frac{dy}{du} = 3.$ How does $y$ change with respect to $x$? For each
revolution of $x$, $y$ revolves 6 times; that is,
$$\frac{dy}{dx} = \frac{dy}{du}\cdot \frac{du}{dx} = 2\cdot 3 = 6.$$ We
can then extend the Chain Rule with more variables by adding more gears
to the picture.\
It is difficult to overstate the importance of the Chain Rule. So often
the functions that we deal with are compositions of two or more
functions, requiring us to use this rule to compute derivatives. It is
also often used in real life when actual functions are unknown. Through
measurement, we can calculate (or, approximate) $\frac{dy}{du}$ and
$\frac{du}{dx}.$ With our knowledge of the Chain Rule, we can find
$\frac{dy}{dx}.$

In the next section, we use the Chain Rule to justify another
differentiation technique. There are many curves that we can draw in the
plane that fail the "vertical line test." For instance, consider
$x^2+y^2=1$, which describes the unit circle. We may still be interested
in finding slopes of tangent lines to the circle at various points. The
next section shows how we can find $\frac{dy}{dx}$ without first
"solving for $y.$" While we can in this instance, in many other
instances solving for $y$ is impossible. In these situations, *implicit
differentiation* is indispensable.
