## Interpretations of the Derivative {#sec:interp-deriv}

The previous section defined the derivative of a function and gave
examples of how to compute it using its definition (i.e., using limits).
The section also started with a brief motivation for this definition,
that is, finding the instantaneous velocity of a falling object given
its position function. The next section will give us more accessible
tools for computing the derivative, tools that are easier to use than
repeated use of limits.

This section falls in between the "What is the definition of the
derivative?" and "How do I compute the derivative?" sections. Here we
are concerned with "What does the derivative mean?", or perhaps, when
read with the right emphasis, "What *is* the derivative?" We offer two
interconnected interpretations of the derivative, hopefully explaining
why we care about it and why it is worthy of study.

### Interpretation 1: Instantaneous Rate of Change
The previous section started with an example of using the position of an
object (in this case, a falling amusement--park rider) to find the
object's velocity. This type of example is often used when introducing
the derivative because we tend to readily recognize that velocity is the
*instantaneous rate of change of position.* In general, if $f$ is a
function of $x$, then $f^{\prime}(x)$ measures the instantaneous rate of
change of $f$ with respect to $x$. Put another way, the derivative
answers "When $x$ changes, at what rate does $f$ change?" Thinking back
to the amusement--park ride, we asked "When time changed, at what rate
did the height change?" and found the answer to be "By $-64$ feet per
second."

Now imagine driving a car and looking at the speedometer, which reads
"60 mph." Five minutes later, you wonder how far you have traveled.
Certainly, lots of things could have happened in those 5 minutes; you
could have intentionally sped up significantly, you might have come to a
complete stop, you might have slowed to 20 mph as you passed through
construction. But suppose that you know, as the driver, none of these
things happened. You know you maintained a fairly consistent speed over
those 5 minutes. What is a good approximation of the distance traveled?

One could argue the *only* good approximation, given the information
provided, would be based on "distance = rate $\times$ time." In this
case, we assume a constant rate of 60 mph with a time of $5/60$ hours.
Hence we would approximate the distance traveled as 5 miles.\
Referring back to the falling amusement--park ride, knowing that at
$t=2$ the velocity was $-64$ ft/s, we could reasonably assume that 1
second later the riders' height would have dropped by about 64 feet.
Knowing that the riders were *accelerating* as they fell would inform us
that this is an *under--approximation*. If all we knew was that
$f(2) = 86$ and $f^{\prime}(2) = -64$, we'd know that we'd have to stop the
riders quickly otherwise they would hit the ground.

### Units of the Derivative

```{youtube}
id: bMeCSL0p9rw
```


It is useful to recognize the *units* of the derivative function. If $y$
is a function of $x$, i.e., $y=f(x)$ for some function $f$, and $y$ is
measured in feet and $x$ in seconds, then the units of $y' = f^{\prime}$ are
"feet per second," commonly written as "ft/s." In general, if $y$ is
measured in units $P$ and $x$ is measured in units $Q$, then $y'$ will
be measured in units "$P$ per $Q$", or "$P/Q$." Here we see the
fraction--like behavior of the derivative in the notation:

::: {.center}
the units of $\displaystyle\frac{dy}{dx}$ are 
$\displaystyle\frac{\text{units of $y$}}{\text{units of $x$}}$.
:::

```{example, label="der-meaning1", echo=TRUE}
(*The meaning of the derivative: World Population*)
Let $P(t)$ represent the world population $t$ minutes after 12:00 a.m.,
January 1, 2012. It is fairly accurate to say that
$P(0) = 7,028,734,178$ ([www.prb.org](https://www.prb.org)). It is also fairly accurate to
state that $P^\prime(0) = 156$; that is, at midnight on January 1, 2012, the
population of the world was growing by about 156 *people per minute*
(note the units). Twenty days later (or, 28,800 minutes later) we could
reasonably assume the population grew by about
$28,800\cdot 156 = 4,492,800$ people.

```



```{example, label="der-meaning2", echo=TRUE}
(The meaning of the derivative: Manufacturing). The term *widget* is an
economic term for a generic unit of manufacturing output. Suppose a
company produces widgets and knows that the market supports a price of
\$10 per widget. Let $P(n)$ give the profit, in dollars, earned by
manufacturing and selling $n$ widgets. The company likely cannot make a
(positive) profit making just one widget; the start--up costs will
likely exceed \$10. Mathematically, we would write this as $P(1) < 0$.

- What do $P(1000) = 500$ and $P^{\prime}(1000)=0.25$ mean? 
- Approximate $P(1100)$.

------------------------------------------------------------------------

The equation $P(1000)=500$ means that selling 1,000 widgets returns a
profit of \$500. We interpret $P^{\prime}(1000) = 0.25$ as meaning that the
profit is increasing at rate of $\$0.25$ per widget (the units are
"dollars per widget.") Since we have no other information to use, our
best approximation for $P(1100)$ is:
$$P(1100) \approx P(1000) + P^{\prime}(1000)\times 100 = \text{\$500} + 100\cdot 0.25 = \text{\$525.}$$
We approximate that selling 1,100 widgets returns a profit of \$525.

```

\
The previous examples made use of an important approximation tool that
we first used in our previous "driving a car at 60 mph" example at the
beginning of this section. Five minutes after looking at the
speedometer, our best approximation for distance traveled assumed the
rate of change was constant. In Examples \@ref(exm:der-meaning1) and
\@ref(exm:der-meaning2) we made similar approximations. We were given
rate of change information which we used to approximate total change.
Notationally, we would say that
$$f(c+h) \approx f(c) + f^{\prime}(c)\cdot h.$$ This approximation is best
when $h$ is "small." "Small" is a relative term; when dealing with the
world population, $h=$ 22 days = 28,800 minutes is small in comparison
to years. When manufacturing widgets, 100 widgets is small when one
plans to manufacture thousands.\

### The Derivative and Motion
One of the most fundamental applications of the derivative is the study
of motion. Let $s(t)$ be a position function, where $t$ is time and
$s(t)$ is distance. For instance, $s$ could measure the height of a
projectile or the distance an object has traveled.

Let's let $s(t)$ measure the distance traveled, in feet, of an object
after $t$ seconds of travel. Then $s^{\prime}(t)$ has units "feet per second,"
and $s^{\prime}(t)$ measures the *instantaneous rate of distance change* -- it
measures **velocity**.

Now consider $v(t)$, a velocity function. That is, at time $t$, $v(t)$
gives the velocity of an object. The derivative of $v$, $v^{\prime}(t)$, gives
the *instantaneous rate of velocity change* -- **acceleration**. (We
often think of acceleration in terms of cars: a car may "go from 0 to 60
in 4.8 seconds." This is an *average* acceleration, a measurement of how
quickly the velocity changed.) If velocity is measured in feet per
second, and time is measured in seconds, then the units of acceleration
(i.e., the units of $v^{\prime}(t)$) are "feet per second per second," or
$($ft/s$)$/s. We often shorten this to "feet per second squared," or
ft/s$^2$, but this tends to obscure the meaning of the units.

Perhaps the most well known acceleration is that of gravity. In this
text, we use $g=32$ft/s$^2$ or $g=9.8$m/s$^2$. What do these numbers
mean?

A constant acceleration of 32$($ft/s$)$/s means that the velocity
changes by 32ft/s each second. For instance, let $v(t)$ measures the
velocity of a ball thrown straight up into the air, where $v$ has units
ft/s and $t$ is measured in seconds. The ball will have a positive
velocity while traveling upwards and a negative velocity while falling
down. The acceleration is thus $-32$ft/s$^2$. If $v(1) = 20$ft/s, then
when $t=2$, the velocity will have decreased by 32ft/s; that is,
$v(2) = -12$ft/s. We can continue: $v(3) = -44$ft/s, and we can also
figure that $v(0) = 52$ft/s.

These ideas are so important we write them out as a definition.

```{definition, echo=TRUE, name="Velocity and acceleration", label="idea-motion"}
Let $s(t)$ be the position function of an object.

1.  Then $s^{\prime}(t)$ is the velocity function of the object, usually denoted $v(t)$.

2.  Let $v(t)$ be the velocity function of an object. Then $v^{\prime}(t)$ is
    the acceleration function of the object, often denoted $a(t)$. 
    
As we will see in the next section, this means that acceleration is the _second derivative_ $s''(t)$ of position.
```

We now consider the second interpretation of the derivative given in
this section. This interpretation is not independent from the first by
any means; many of the same concepts will be stressed, just from a
slightly different perspective.

### Interpretation 2: The Slope of the Tangent Line

```{youtube}
id: mGI4WaC1cd8
```

```{youtube}
id: P4B9RWGmapo
```

Given a function $y=f(x)$, the difference quotient
$\displaystyle\frac{f(c+h)-f(c)}{h}$ gives a change in $y$ values
divided by a change in $x$ values; i.e., it is a measure of the "rise
over run," or "slope," of the line that goes through two points on the
graph of $f$: $\big(c, f(c)\big)$ and $\big(c+h,f(c+h)\big)$. As $h$
shrinks to 0, these two points come close together; in the limit we find
$f^{\prime}(c)$, the slope of a special line called the tangent line that
intersects $f$ only once near $x=c$.

Lines have a constant rate of change, their slope. Nonlinear functions
do not have a constant rate of change, but we can measure their
*instantaneous rate of change* at a given $x$ value $c$ by computing
$f^{\prime}(c)$. We can get an idea of how $f$ is behaving by looking at the
slopes of its tangent lines. We explore this idea in the following
example.\

```{example, label="der-meaning3", echo=TRUE}
(Understanding the derivative: the rate of change). Consider
$f(x) = x^2$ as shown in Figure \@ref(fig:xsquared). It is clear that at
$x=3$ the function is growing faster than at $x=1$, as it is steeper at
$x=3$. How much faster is it growing?

------------------------------------------------------------------------

We can answer this directly after the following section, where we learn
to quickly compute derivatives. For now, we will answer graphically, by
considering the slopes of the respective tangent lines.

With practice, one can fairly effectively sketch tangent lines to a
curve at a particular point. In Figure \@ref(fig:xsquared), we
have sketched the tangent lines to $f$ at $x=1$ and $x=3$, along with a
grid to help us measure the slopes of these lines. At $x=1$, the slope
is 2; at $x=3$, the slope is 6. Thus we can say not only is $f$ growing
faster at $x=3$ than at $x=1$, it is growing *three times as fast*.

```

```{geogebra, xsquared}
material_id: x5whenaj
caption: >
  A graph of $f(x)=x^2$ and tangent lines. Change the value of $c$ to get tanget lines at different $x$-values.
```

```{example, label="der-meaning4", echo=TRUE}
(Understanding the graph of the derivative). Consider the graph of
$f(x)$ and its derivative, $f^{\prime}(x)$, in Figure
\@ref(fig:fwithderiv). Use these graphs to find the slopes of the
tangent lines to the graph of $f$ at $x=1$, $x=2$, and $x=3$.

------------------------------------------------------------------------

To find the appropriate slopes of tangent lines to the graph of $f$, we
need to look at the corresponding values of $f^{\prime}$.

The slope of the tangent line to $f$ at $x=1$ is $f^{\prime}(1)$; this looks
to be about $-1$.

The slope of the tangent line to $f$ at $x=2$ is $f^{\prime}(2)$; this looks
to be about $4$.

The slope of the tangent line to $f$ at $x=3$ is $f^{\prime}(3)$; this looks
to be about $3$.

Using these slopes, the tangent lines to $f$ are sketched in Figure
\@ref(fig:fwithderiv). Included on the graph of $f^{\prime}$ in this figure
are filled circles where $x=1$, $x=2$ and $x=3$ to help better visualize
the $y$ value of $f^{\prime}$ at those points.

```

```{geogebra fwithderiv}
material_id: sudgnujc
caption: >
  Graphs of $f$ and $f^{\prime}$ in Example \@ref(exm:der-meaning4), 
  along with tangent line. Move the point $c$ to investigate the slope 
  at different $x$-values.
```



```{example, label="der-meaning5", echo=TRUE}
(Approximation with the derivative). Consider again the graph of $f(x)$
and its derivative $f^{\prime}(x)$ in Example \@ref(exm:der-meaning4). Use the
tangent line to $f$ at $x=3$ to approximate the value of $f(3.1)$.

------------------------------------------------------------------------

Figure \@ref(fig:fwithderivzoom3) shows the graph of $f$ along with its
tangent line, zoomed in at $x=3$. Notice that near $x=3$, the tangent
line makes an excellent approximation of $f$. Since lines are easy to
deal with, often it works well to approximate a function with its
tangent line. (This is especially true when you don't actually know much
about the function at hand, as we don't in this example.)

While the tangent line to $f$ was drawn in Example
\@ref(exm:der-meaning4), it was not explicitly computed. Recall that the
tangent line to $f$ at $x=c$ is $y = f^{\prime}(c)(x-c)+f(c)$. While $f$ is
not explicitly given, by the graph it looks like $f(3) = 4$. Recalling
that $f^{\prime}(3) = 3$, we can compute the tangent line to be approximately
$y = 3(x-3)+4.$ It is often useful to leave the tangent line in
point--slope form.

To use the tangent line to approximate $f(3.1)$, we simply evaluate $y$
at $3.1$ instead of $f$.

$$f(3.1) \approx y(3.1) = 3(3.1-3)+4 = .1*3+4 = 4.3.$$

We approximate $f(3.1) \approx 4.3.$

```

```{geogebra fwithderivzoom3}
material_id: rp3syqkc
caption: >
  Zooming in on $f$ and its tangent line at $x=3$ for the
  function given in Examples \@ref(exm:der-meaning4) and
  \@ref(exm:der-meaning5).
```  

To demonstrate the accuracy of the tangent line approximation, we now
state that in Example \@ref(exm:der-meaning5), $f(x) = -x^3+7x^2-12x+4$.
We can evaluate $f(3.1) = 4.279$. Had we known $f$ all along, certainly
we could have just made this computation. In reality, we often only know
two things:

1.  what $f(c)$ is, for some value of $c$, and
2.  what $f^{\prime}(c)$ is.

For instance, we can easily observe the location of an object and its
instantaneous velocity at a particular point in time. We do not have a
"function $f$ " for the location, just an observation. This is enough to
create an approximating function for $f$.

This last example has a direct connection to our approximation method
explained above after Example \@ref(exm:der-meaning2). We stated there
that $$f(c+h) \approx f(c)+f^{\prime}(c)\cdot h.$$ If we know $f(c)$ and
$f^{\prime}(c)$ for some value $x=c$, then computing the tangent line at
$(c,f(c))$ is easy: $y(x) = f^{\prime}(c)(x-c)+f(c)$. In Example
\@ref(exm:der-meaning5), we used the tangent line to approximate a value
of $f$. Let's use the tangent line at $x=c$ to approximate a value of
$f$ near $x=c$; i.e., compute $y(c+h)$ to approximate $f(c+h)$, assuming
again that $h$ is "small." Note:
$$y(c+h) = f^{\prime}(c)\big((c+h)-c\big)+f(c) = f^{\prime}(c)\cdot h + f(c).$$ This
is the exact same approximation method used above! Not only does it make
intuitive sense, as explained above, it makes analytical sense, as this
approximation method is simply using a tangent line to approximate a
function's value.\

The importance of understanding the derivative cannot be understated.
When $f$ is a function of $x$, $f^{\prime}(x)$ measures the instantaneous rate
of change of $f$ with respect to $x$ and gives the slope of the tangent
line to $f$ at $x$.


```{youtube}
id: _eI6LFHWgaM
```

