# Graphical Behavior of Functions

Our study of limits led to continuous functions, a certain class of
functions that behave in a particularly nice way. Limits then gave us an
even nicer class of functions, functions that are differentiable.

This chapter explores many of the ways we can take advantage of the
information that continuous and differentiable functions provide.

```{youtube}
id: srE7xUmQtCQ
```

## Extreme Values {#sec:extreme-values}

Given any quantity described by a function, we are often interested in
the largest and/or smallest values that quantity attains. For instance,
if a function describes the speed of an object, it seems reasonable to
want to know the fastest/slowest the object traveled. If a function
describes the value of a stock, we might want to know the highest/lowest
values the stock attained over the past year. We call such values
*extreme values.*

```{definition, label="extreme-values", echo=TRUE}

(Extreme Values). Let $f$ be defined on an interval $I$ containing $c$.

1.  $f(c)$ is the **minimum** (also, **absolute minimum**) of $f$ on $I$
    if $f(c) \leq f(x)$ for all $x$ in $I$.

2.  $f(c)$ is the **maximum** (also, **absolute maximum**) of $f$ on $I$
    if $f(c) \geq f(x)$ for all $x$ in $I$.

The maximum and minimum values are the **extreme values**, or
**extrema**, of $f$ on $I$.

```

> **Note:** The extreme values of a function are "$y$" values, values
> the function attains, not the input values.

Consider Figure \@ref(fig:extreme). The function displayed in (a) has a
maximum, but no minimum, as the interval over which the function is
defined is open. In (b), the function has a minimum, but no maximum;
there is a discontinuity in the "natural" place for the maximum to
occur. Finally, the function shown in (c) has both a maximum and a
minimum; note that the function is continuous and the interval on which
it is defined is closed.


```{r extreme, fig.cap="Graphs of functions with and without extreme values. Toggle the functions on and off by clicking in the circles on the left side of the graph."}
knitr::include_url("https://www.desmos.com/calculator/qbcyuxgndp")
```



It is possible for discontinuous functions defined on an open interval
to have both a maximum and minimum value, but we have just seen examples
where they did not. On the other hand, continuous functions on a closed
interval *always* have a maximum and minimum value.

```{youtube}
id: GIcjxu8dTnY
```


```{theorem, label="extreme-val", echo=TRUE}

(The Extreme Value Theorem). Let $f$ be a continuous function defined on
a closed interval $I$. Then $f$ has both a maximum and minimum value on
$I$.

```

This theorem states that $f$ has extreme values, but it does not offer
any advice about how/where to find these values. The process can seem to
be fairly easy, as the next example illustrates. After the example, we
will draw on lessons learned to form a more general and powerful method
for finding extreme values.\

```{example, label="extval1ex", echo=TRUE}

(Approximating extreme values). Consider $f(x) = 2x^3-9x^2$ on
$I=[-1,5]$, as graphed in Figure \@ref(fig:extval1). Approximate the
extreme values of $f$.


------------------------------------------------------------------------

The graph is drawn in such a way to draw attention to certain points. It
certainly seems that the smallest $y$ value is $-27$, found when $x=3$.
It also seems that the largest $y$ value is 25, found at the endpoint of
$I$, $x=5$. We use the word *seems*, for by the graph alone we cannot be
sure the smallest value is not less than $-27$. Since the problem asks
for an approximation, we approximate the extreme values to be $25$ and
$-27$.

```


```{geogebra, label="extval1"}
material_id: ps9vpptc
caption: >
    A graph of $f(x) = 2x^3-9x^2$ as in Example \@ref(exm:extval1ex).

```

Notice how the minimum value came at "the bottom of a hill," and the
maximum value came at an endpoint. Also note that while $0$ is not an
extreme value, it would be if we narrowed our interval to $[-1,4]$. The
idea that the point $(0,0)$ is the location of an extreme value for some
interval is important, leading us to a definition of a *relative
maximum*. In short, a "relative max" is a $y$-value that's the largest
$y$-value "nearby."

> **Note:** The terms *local minimum* and *local maximum* are often used
> as synonyms for *relative minimum* and *relative maximum*.\
> As it makes intuitive sense that an absolute maximum is also a
> relative maximum, Definition \@ref(def:rel-ext) allows a relative
> maximum to occur at an interval's endpoint.

```{youtube}
id: nBZTnxn0vqQ
```

```{definition, label="rel-ext", echo=TRUE}

(Relative Minimum and Relative Maximum). Let $f$ be defined on an
interval $I$ containing $c$.

1.  If there is a $\delta>0$ such that $f(c) \leq f(x)$ for all $x$ in
    $I$ where $|x-c|<\delta$, then $f(c)$ is a **relative minimum** of
    $f$. We also say that $f$ has a relative minimum at $(c,f(c))$.

2.  If there is a $\delta>0$ such that $f(c) \geq f(x)$ for all $x$ in
    $I$ where $|x-c|<\delta$, then $f(c)$ is a **relative maximum** of
    $f$. We also say that $f$ has a relative maximum at $(c,f(c))$.

The relative maximum and minimum values comprise the **relative
extrema** of $f$.

```

We briefly practice using these definitions.\

```{example, label="extval2ex", echo=TRUE}

(Approximating relative extrema). Consider
$f(x) = (3x^4-4x^3-12x^2+5)/5$, as shown in Figure \@ref(fig:extval2).
Approximate the relative extrema of $f$. At each of these points,
evaluate $f^{\prime}$.


------------------------------------------------------------------------

We still do not have the tools to exactly find the relative extrema, but
the graph does allow us to make reasonable approximations. It seems $f$
has relative minima at $x=-1$ and $x=2$, with values of $f(-1)=0$ and
$f(2) = -5.4$. It also seems that $f$ has a relative maximum at the
point $(0,1)$.

We approximate the relative minima to be $0$ and $-5.4$; we approximate
the relative maximum to be $1$.

It is straightforward to evaluate
$f^{\prime}(x) =\frac 15(12x^3-12x^2-24x)$ at $x=0, 1$ and $2$. In each
case, $f^{\prime}(x) = 0$.

```


```{geogebra, label="extval2"}
material_id: q6wpkzpz
caption: > 
    A graph of $f(x) = (3x^4-4x^3-12x^2+5)/5$ as in Example \@ref(exm:extval2ex).

```

```{example, label="extval3ex", echo=TRUE}

(Approximating relative extrema). Approximate the relative extrema of
$f(x) = (x-1)^{2/3}+2$, shown in Figure \@ref(fig:extval3). At each of
these points, evaluate $f^{\prime}$.


------------------------------------------------------------------------

The figure implies that $f$ does not have any relative maxima, but has a
relative minimum at $(1,2)$. In fact, the graph suggests that not only
is this point a relative minimum, $y=f(1)=2$ is *the* minimum value of
the function.

We compute $f^{\prime}(x) = \frac 23(x-1)^{-1/3}$. When $x=1$,
$f^{\prime}$ is undefined.

```


```{geogebra, label="extval3"}
material_id: s9s5qypj
caption: >
    A graph of $f(x) = (x-1)^{2/3}+2$ as in Example \@ref(exm:extval3ex).

```

What can we learn from the previous two examples? We were able to
visually approximate relative extrema, and at each such point, the
derivative was either 0 or it was not defined. This observation holds
for all functions, leading to a definition and a theorem.

```{youtube}
id: WsBGpi006X0
```


```{definition, label="criticalnum", echo=TRUE}

(Critical Numbers and Critical Points). Let $f$ be defined at $c$. The
value $c$ is a **critical number** (or **critical value**) of $f$ if
$f^{\prime}(c)=0$ or $f^{\prime}(c)$ is not defined.\
If $c$ is a critical number of $f$, then the point $(c,f(c))$ is a
**critical point** of $f$.

```

```{theorem, label="criticalpts", echo=TRUE}

(Relative Extrema and Critical Points). Let a function $f$ be defined on
an open interval $I$ containing $c$, and let $f$ have a relative
extremum at the point $(c,f(c))$. Then $c$ is a critical number of $f$.

```

Be careful to understand that this theorem states "Relative extrema on
open intervals occur at critical points." It does not say "All critical
numbers produce relative extrema." For instance, consider $f(x) = x^3$.
Since $f^{\prime}(x) = 3x^2$, it is straightforward to determine that
$x=0$ is a critical number of $f$. However, $f$ has no relative extrema,
as illustrated in Figure \@ref(fig:extreme4).

```{geogebra, label="extreme4"}
material_id: rdxchnpu
caption: >
    A graph of $f(x)=x^3$ which has a critical value of $x=0$, but
    no relative extrema.

```

Theorem \@ref(thm:extreme-val) states that a continuous function on a
closed interval will have both an absolute maximum and an absolute
minimum. Common sense tells us "extrema occur either at the endpoints or
somewhere in between." It is easy to check for extrema at endpoints, but
there are infinitely many points to check that are "in between." Our
theory tells us we need only check at the critical points that are in
between the endpoints. We combine these concepts to offer a strategy for
finding extrema.

```{theorem extrema, echo=TRUE}
Let $f$ be a continuous function defined on a closed interval $[a,b]$.
To find the maximum and minimum values of $f$ on $[a,b]$:

1.  Evaluate $f$ at the endpoints $a$ and $b$ of the interval.

2.  Find the critical numbers of $f$ in $[a,b]$.

3.  Evaluate $f$ at each critical number.

4.  The absolute maximum of $f$ is the largest of these values, and the
    absolute minimum of $f$ is the least of these values.

```

We practice these ideas in the next examples.\

```{youtube}
id: LyhHlreZvhc
```


```{example, label="extval4", echo=TRUE}

(Finding extreme values). Find the extreme values of
$f(x) = 2x^3+3x^2-12x$ on $[0,3]$, graphed in Figure
\@ref(fig:ext4).

------------------------------------------------------------------------

We follow the steps outlined in Theorem \@ref(thm:extrema). We first
evaluate $f$ at the endpoints:
$$f(0) = 0 \quad \text{and}\quad f(3) =45.$$ Next, we find the critical
values of $f$ on $[0,3]$. $f^{\prime}(x) = 6x^2+6x-12 = 6(x+2)(x-1)$;
therefore the critical values of $f$ are $x=-2$ and $x=1$. Since $x=-2$
does not lie in the interval $[0,3]$, we ignore it. Evaluating $f$ at
the only critical number in our interval gives: $f(1) = -7$.

The special points in Figure \@ref(fig:ext4) gives $f$ evaluated at the
"important" $x$ values in $[0,3]$. We can easily see the maximum and
minimum values of $f$: the maximum value is $45$ and the minimum value
is $-7$.

```

```{geogebra ext4}
material_id: jxsdebf2
caption: >
    Finding the extreme values of
    $f(x)= 2x^3+3x^2-12x$ in Example \@ref(exm:extval4).
```

Note that all this was done without the aid of a graph; this work
followed an analytic algorithm and did not depend on any visualization.
Figure \@ref(fig:ext4) shows $f$ and we can confirm our answer, but it
is important to understand that these answers can be found without
graphical assistance.

We practice again.

```{youtube}
id: zn--ShSSMqk
```


```{example, label="extval5", echo=TRUE}

(Finding extreme values). Find the maximum and minimum values of $f$ on
$[-4,2]$, where
$$f(x) = \left\{\begin{array}{cc} (x-1)^2 & x\leq 0 \\ x+1 & x>0 \end{array}\right. ,$$
graphed in Figure \@ref(fig:ext5)(a).

------------------------------------------------------------------------

Here $f$ is piecewise--defined, but we can still apply Theorem
\@ref(thm:extrema) as it is continuous on $[-4,2]$ (one should check to
verify that $\displaystyle\lim_{x\to 0}f(x) =f(0)$). Evaluating $f$ at
the endpoints gives: $$f(-4) = 25 \quad \text{and} \quad f(2) = 3.$$

We now find the critical numbers of $f$. We have to define $f^{\prime}$
in a piecewise manner; it is
$$f^{\prime}(x) =\left\{\begin{array}{cc} 2(x-1) & x < 0 \\ 1 & x>0 \end{array}\right. .$$
Note that while $f$ is defined for all of $[-4,2]$, $f^{\prime}$ is not,
as the derivative of $f$ does not exist when $x=0$. (From the left, the
derivative approaches $-2$; from the right the derivative is 1.) Thus
one critical number of $f$ is $x=0$.

We now set $f^{\prime}(x) = 0$. When $x >0$, $f^{\prime}(x)$ is never 0.
When $x<0$, $f^{\prime}(x)$ is also never 0, so we find no critical
values from setting $f^{\prime}(x)=0$.

So we have three important $x$ values to consider: $x= -4, 2$ and $0$.
Evaluating $f$ at each gives, respectively, $25$, $3$ and $1$, shown in
Figure \@ref(fig:ext5)(b). Thus the absolute minimum of $f$ is 1, the
absolute maximum of $f$ is $25$, confirmed by the graph of $f$.

```

```{geogebra ext5}
material_id: yxnn8hnr
caption: >
    Finding the extreme values of a piecewise--defined
    function in Example \@ref(exm:extval5).
```


```{youtube}
id: sT_3kVSsbz4
```

```{example, label="extval6", echo=TRUE}

(Finding extreme values). Find the extrema of $f(x) = \cos (x^2)$ on
$[-2,2]$, graphed in Figure \@ref(fig:ext6).

------------------------------------------------------------------------

We again use Theorem \@ref(thm:extrema). Evaluating $f$ at the
endpoints of the interval gives:
$f(-2) = f(2) = \cos (4) \approx -0.6536.$ We now find the critical
values of $f$.

Applying the Chain Rule, we find $f^{\prime}(x) = -2x\sin (x^2)$. Set
$f^{\prime}(x) = 0$ and solve for $x$ to find the critical values of
$f$.

We have $f^{\prime}(x) = 0$ when $x = 0$ and when $\sin (x^2) = 0$. In
general, $\sin t = 0$ when $t = \ldots -2\pi, -\pi, 0, \pi, \ldots$ Thus
$\sin (x^2) = 0$ when $x^2 = 0, \pi, 2\pi, \ldots$ ($x^2$ is always
positive so we ignore $-\pi$, etc.) So $\sin (x^2)=0$ when
$x= 0, \pm \sqrt{\pi}, \pm\sqrt{2\pi},$ etc. The only values to fall in
the given interval of $[-2,2]$ are $0$ and $\pm\sqrt{\pi}$, where
$\sqrt{\pi} \approx 1.77$.

We again construct a table of important values in Figure
\@ref(fig:ext6). In this example we have 5 values to consider:
$x= 0, \pm 2, \pm\sqrt{\pi}$.

From the figure it is clear that the maximum value of $f$ on $[-2,2]$ is
1; the minimum value is $-1$. The graph of $f$ confirms our results.

```

```{geogebra ext6}
material_id: wgupbtn5
caption: >
    Finding the extrema of $f(x)= \cos (x^2)$ in
    Example \@ref(exm:extval6).
```

We consider one more example.

```{youtube}
id: sT_3kVSsbz4
```

```{example, label="extval7ex", echo=TRUE}

(Finding extreme values). Find the extreme values of
$f(x) = \sqrt{1-x^2}$, graphed in Figure \@ref(fig:ext7).

------------------------------------------------------------------------

A closed interval is not given, so we find the extreme values of $f$ on
its domain. $f$ is defined whenever $1-x^2\geq 0$; thus the domain of
$f$ is $[-1,1]$. Evaluating $f$ at either endpoint returns 0.

Using the Chain Rule, we find
$\displaystyle f^{\prime}(x) = \frac{-x}{\sqrt{1-x^2}}$. The critical
points of $f$ are found when $f^{\prime}(x) = 0$ or when $f^{\prime}$ is
undefined. It is straightforward to find that $f^{\prime}(x) = 0$ when
$x=0$, and $f^{\prime}$ is undefined when $x=\pm 1$, the endpoints of
the interval. The table of important values is given in Figure
\@ref(fig:ext7). The maximum value is 1, and the minimum value is
0. (See also the marginal note.)

```

```{geogebra ext7}
material_id: bwphczkk
caption: >
    Finding the extrema of the half-circle in Example
    \@ref(exm:extval7ex).
```

> **Note:** We implicitly found the derivative of $x^2+y^2=1$, the unit
> circle, in Example \@ref(exm:implicit7ex) as $\frac{dy}{dx} = -x/y$. In
> Example \@ref(exm:extval7ex), half of the unit circle is given as
> $y=f(x) = \sqrt{1-x^2}$. We found
> $f^{\prime}(x) = \frac{-x}{\sqrt{1-x^2}}$. Recognize that the
> denominator of this fraction is $y$; that is, we again found
> $f^{\prime}(x) = \frac{dy}{dx} = -x/y.$

We have seen that continuous functions on closed intervals always have a
maximum and minimum value, and we have also developed a technique to
find these values. In the next section, we further our study of the
information we can glean from "nice" functions with the Mean Value
Theorem. On a closed interval, we can find the *average rate of change*
of a function (as we did at the beginning of Chapter 2). We will see
that differentiable functions always have a point at which their
*instantaneous* rate of change is same as the *average* rate of change.
This is surprisingly useful, as we'll see.
