## Increasing and Decreasing Functions {#sec:incr_decr}

Our study of "nice" functions $f$ in this chapter has so far focused on
individual points: points where $f$ is maximal/minimal, points where
$f^{\prime}(x) = 0$ or $f^{\prime}$ does not exist, and points $c$ where
$f^{\prime}(c)$ is the average rate of change of $f$ on some interval.

In this section we begin to study how functions behave *between* special
points; we begin studying in more detail the shape of their graphs.

We start with an intuitive concept. Given the graph in Figure
\@ref(fig:incr0), where would you say the function is *increasing*?
*Decreasing*? Even though we have not defined these terms
mathematically, one likely answered that $f$ is increasing when $x>1$
and decreasing when $x<1$. We formally define these terms here.

```{geogebra, label="incr0"}
material_id: yqjwapx7
caption: >
    A graph of a function $f$ used to illustrate the concepts of
    *increasing* and *decreasing*.

```

```{youtube}
id: NtV0R-JxrmM
```

```{definition, label="incr-decr", echo=TRUE}

(Increasing and Decreasing Functions). Let $f$ be a function defined on
an interval $I$.

1.  $f$ is **increasing** on $I$ if for every $a<b$ in $I$,
    $f(a) < f(b)$.

2.  $f$ is **decreasing** on $I$ if for every $a<b$ in $I$,
    $f(a) > f(b)$.

```

Informally, a function is increasing if as $x$ gets larger (i.e.,
looking left to right) $f(x)$ gets larger.

Our interest lies in finding intervals in the domain of $f$ on which $f$
is either increasing or decreasing. Such information should seem useful.
For instance, if $f$ describes the speed of an object, we might want to
know when the speed was increasing or decreasing (i.e., when the object
was accelerating vs. decelerating). If $f$ describes the population of a
city, we should be interested in when the population is growing or
declining.

To find such intervals, we again consider secant lines. Let $f$ be an
increasing, differentiable function on an open interval $I$, such as the
one shown in Figure \@ref(fig:incr00), and let $a<b$ be given in $I$.
The secant line on the graph of $f$ from $x=a$ to $x=b$ is drawn; it has
a slope of $(f(b)-f(a))/(b-a)$. But note:
$$\frac{f(b)-f(a)}{b-a} \Rightarrow \frac{\text{numerator }>0}{\text{denominator } >0} \Rightarrow \text{slope of the secant line $>0$}.$$ But this means that the average rate of change of $f$ on $[a,b]$ is $>0$.

```{geogebra, label="incr00"}
material_id: nemxkxy2
caption: Examining the secant line of an increasing function.

```

We have shown mathematically what may have already been obvious: when
$f$ is increasing, its secant lines will have a positive slope. Now
recall the Mean Value Theorem guarantees that there is a number $c$,
where $a<c<b$, such that $$f^{\prime}(c) = \frac{f(b)-f(a)}{b-a}>0.$$ By
considering all such secant lines in $I$, we strongly imply that
$f^{\prime}(x) > 0$ on $I$. A similar statement can be made for
decreasing functions.

```{youtube}
id: SjF3vslBqOA
```

### Increasing and Decreasing Intervals

Our above logic can be summarized as "If $f$ is increasing, then
$f^{\prime}$ is probably positive.\" Theorem \@ref(thm:first-deriv-test) below
turns this around by stating "If $f^{\prime}$ is positive, then $f$ is
increasing." This leads us to a method for finding when functions are
increasing and decreasing.

```{theorem, label="first-deriv-test", echo=TRUE}

(Test For Increasing/Decreasing Functions). Let $f$ be a continuous
function on $[a,b]$ and differentiable on $(a,b)$.

1.  If $f^{\prime}(c) > 0$ for all $c$ in $(a,b)$, then $f$ is
    increasing on $[a,b]$.

2.  If $f^{\prime}(c) <0$ for all $c$ in $(a,b)$, then $f$ is decreasing
    on $[a,b]$.

3.  If $f^{\prime}(c) =0$ for all $c$ in $(a,b)$, then $f$ is constant
    on $[a,b]$.

```

> **Note:** Parts 1 & 2 of Theorem \@ref(thm:first-deriv-test) also hold if
> $f^{\prime}(c) = 0$ for a finite number of values of $c$ in $I$.

Let $f$ be differentiable on an interval $I$ and let $a$ and $b$ be in
$I$ where $f^{\prime}(a)>0$ and $f^{\prime}(b)<0$. If $f^{\prime}$ is
continuous on $[a,b]$, it follows from the Intermediate Value Theorem
that there must be some value $c$ between $a$ and $b$ where
$f^{\prime}(c) = 0$. (It turns out that this is still true even if
$f^{\prime}$ is not continuous on $[a,b]$.) This leads us to the
following method for finding intervals on which a function is increasing
or decreasing.

```{theorem incr-decr2, echo=TRUE}
Let $f$ be a differentiable function on an interval $I$. To find
intervals on which $f$ is increasing and decreasing:

1.  Find the critical values of $f$. That is, find all $c$ in $I$ where
    $f^{\prime}(c) = 0$ or $f^{\prime}$ is not defined.
2.  Use the critical values to divide $I$ into subintervals.
3.  Pick any point $p$ in each subinterval, and find the sign of
    $f^{\prime}(p)$.
    1.  If $f^{\prime}(p)>0$, then $f$ is increasing on that
        subinterval.
    2.  If $f^{\prime}(p)<0$, then $f$ is decreasing on that
        subinterval.

```

We demonstrate using this process in the following example.


```{youtube}
id: DW6qcgE1TZ0
```

```{example, label="incr1ex", echo=TRUE}

(Finding intervals of increasing/decreasing). Let $f(x) = x^3+x^2-x+1$.
Find intervals on which $f$ is increasing or decreasing.

------------------------------------------------------------------------

Using Theorem \@ref(thm:incr-decr2), we first find the critical values
of $f$. We have $f^{\prime}(x) = 3x^2+2x-1 = (3x-1)(x+1)$, so
$f^{\prime}(x) = 0$ when $x=-1$ and when $x=1/3$. $f^{\prime}$ is never
undefined.

Since an interval was not specified for us to consider, we consider the
entire domain of $f$ which is $(-\infty,\infty)$. We thus break the
whole real line into three subintervals based on the two critical values
we just found: $(-\infty,-1)$, $(-1,1/3)$ and $(1/3,\infty)$. This is
shown in Figure \@ref(fig:incrline1).

We now pick a value $p$ in each subinterval and find the sign of
$f^{\prime}(p)$. All we care about is the sign, so we do not actually
have to fully compute $f^{\prime}(p)$; pick "nice" values that make this
simple.

**Subinterval 1**, $(-\infty,-1)$:We (arbitrarily) pick $p=-2$. We can
compute $f^{\prime}(-2)$ directly:
$f^{\prime}(-2) = 3(-2)^2+2(-2)-1=7>0$. We conclude that $f$ is
increasing on $(-\infty,-1)$.

Note we can arrive at the same conclusion without computation. For
instance, we could choose $p=-100$. The first term in
$f^{\prime}(-100)$, i.e., $3(-100)^2$ is clearly positive and very
large. The other terms are small in comparison, so we know
$f^{\prime}(-100)>0$. All we need is the sign.

**Subinterval 2**, $(-1,1/3)$:We pick $p=0$ since that value seems easy
to deal with. $f^{\prime}(0) = -1<0$. We conclude $f$ is decreasing on
$(-1,1/3)$.

**Subinterval 3**, $(1/3,\infty)$:Pick an arbitrarily large value for
$p>1/3$ and note that $f^{\prime}(p) =3p^2+2p-1 >0$. We conclude that
$f$ is increasing on $(1/3,\infty)$.

We can verify our calculations by considering Figure \@ref(fig:incr1),
where $f$ is graphed. The graph also presents $f^{\prime}$; note how
$f^{\prime}>0$ when $f$ is increasing and $f^{\prime}<0$ when $f$ is
decreasing.
```

```{tikz incrline1, fig.width=NULL, fig.cap="Number line for $f$ in Example \\@ref(exm:incr1ex).", cache=TRUE}
\begin{tikzpicture}
 \begin{axis}[numberline,
  xmin=-2, xmax=1,
  extra x ticks={-1, 0.3333},
  extra x tick labels={$-1$,$1/3$},
]
\addplot[guideline] coordinates {(-1,0) (-1,2)};
\addplot[guideline] coordinates {(0.3333,0) (0.3333,2)};
\addplot[mark=none] coordinates {(-1.6666,1)} node {\parbox{3em}{\centering \small $f'>0$ incr }};
\addplot[mark=none] coordinates {(-0.3333,1)} node {\parbox{3em}{\centering \small $f'<0$ decr }};
\addplot[mark=none] coordinates {(0.75,1)} node {\parbox{3em}{\centering \small $f'>0$ incr }};
\end{axis}
\end{tikzpicture}
```

```{geogebra, label="incr1"}
material_id: mahtag9b
caption: > 
    A graph of $f(x)$ in Example \@ref(exm:incr1ex), showing where
    $f$ is increasing and decreasing.

```


One is justified in wondering why so much work is done when the graph
seems to make the intervals very clear. We give three reasons why the
above work is worthwhile.

First, the points at which $f$ switches from increasing to decreasing
are not precisely known given a graph. The graph shows us something
significant happens near $x=-1$ and $x=0.3$, but we cannot determine
exactly where from the graph.

One could argue that just finding critical values is important; once we
know the significant points are $x=-1$ and $x=1/3$, the graph shows the
increasing/decreasing traits just fine. That is true. However, the
technique prescribed here helps reinforce the relationship between
increasing/decreasing and the sign of $f^{\prime}$. Once mastery of this
concept (and several others) is obtained, one finds that either (a) just
the critical points are computed and the graph shows all else that is
desired, or (b) a graph is never produced, because determining
increasing/decreasing using $f^{\prime}$ is straightforward and the
graph is unnecessary. So our second reason why the above work is
worthwhile is this: once mastery of a subject is gained, one has
*options* for finding needed information. We are working to develop
mastery.

Finally, our third reason: many problems we face "in the real world" are
very complex. Solutions are tractable only through the use of computers
to do many calculations for us. Computers do not solve problems "on
their own," however; they need to be taught (i.e., *programmed*) to do
the right things. It would be beneficial to give a function to a
computer and have it return maximum and minimum values, intervals on
which the function is increasing and decreasing, the locations of
relative maxima, etc. The work that we are doing here is easily
programmable. It is hard to teach a computer to "look at the graph and
see if it is going up or down." It is easy to teach a computer to
"determine if a number is greater than or less than 0."

### The First Derivative Test for Extreme Values

In Section \@ref(sec:extreme-values) we learned the definition of
relative maxima and minima and found that they occur at critical points.
We are now learning that functions can switch from increasing to
decreasing (and vice--versa) at critical points. This new understanding
of increasing and decreasing creates a great method of determining
whether a critical point corresponds to a maximum, minimum, or neither.
Imagine a function increasing until a critical point at $x=c$, after
which it decreases. A quick sketch helps confirm that $f(c)$ must be a
relative maximum. A similar statement can be made for relative minimums.
We formalize this concept in a theorem.

```{youtube}
id: _HjE4urOM4Y
```

```{theorem, label="first-der", echo=TRUE}

(First Derivative Test). Let $f$ be differentiable on an interval $I$
and let $c$ be a critical number in $I$.

1.  If the sign of $f'$ switches from positive to negative at $c$, then
    $f(c)$ is a relative maximum of $f$.
2.  If the sign of $f'$ switches from negative to positive at $c$, then
    $f(c)$ is a relative minimum of $f$.
3.  If $f'$ does not change sign as it crosses $c$, then $f(c)$
    is not a relative extrema of $f$.

```


```{youtube}
id: 94iCiIX07R0
```

```{example, label="incr2ex", echo=TRUE}

(Using the First Derivative Test). Find the intervals on which $f$ is
increasing and decreasing, and use the First Derivative Test to
determine the relative extrema of $f$, where
$$f(x) = \frac{x^2+3}{x-1}.$$

------------------------------------------------------------------------

We start by noting the domain of $f$: $(-\infty,1)\cup(1,\infty)$. Key
Idea \@ref(thm:incr-decr2) describes how to find intervals where $f$ is
increasing and decreasing *when the domain of $f$ is an interval.* Since
the domain of $f$ in this example is the union of two intervals, we
apply the techniques of Theorem \@ref(thm:incr-decr2) to both intervals
of the domain of $f$.

Since $f$ is not defined at $x=1$, the increasing/decreasing nature of
$f$ could switch at this value. We do not formally consider $x=1$ to be
a critical value of $f$, but we will include it in our list of critical
values that we find next.

Using the Quotient Rule, we find
$$f^{\prime}(x) = \frac{x^2-2x-3}{(x-1)^2}.$$ We need to find the
critical values of $f$; we want to know when $f^{\prime}(x)=0$ and when
$f^{\prime}$ is not defined. That latter is straightforward: when the
denominator of $f^{\prime}(x)$ is 0, $f^{\prime}$ is undefined. That
occurs when $x=1$, which we've already recognized as an important value.

$f^{\prime}(x)=0$ when the numerator of $f^{\prime}(x)$ is 0. That
occurs when $x^2-2x-3 = (x-3)(x+1) = 0$; i.e., when $x=-1,3$.

We have found that $f$ has two critical numbers, $x=-1,3$, and at $x=1$
something important might also happen. These three numbers divide the
real number line into 4 subintervals:
$$(-\infty,-1), \quad (-1, 1), \quad (1,3) \quad \text{and} \quad (3,\infty).$$
Pick a number $p$ from each subinterval and test the sign of $f^\prime$ at $p$
to determine whether $f$ is increasing or decreasing on that interval.
Again, we do well to avoid complicated computations; notice that the
denominator of $f^{\prime}$ is *always* positive so we can ignore it
during our work.

**Interval 1**, $(-\infty,-1)$:Choosing a very small number (i.e., a
negative number with a large magnitude) $p$ returns $p^2-2p-3$ in the
numerator of $f^{\prime}$; that will be positive. Hence $f$ is
increasing on $(-\infty,-1)$.

**Interval 2**, $(-1,1)$:Choosing 0 seems simple: $f^{\prime}(0)=-3<0$.
We conclude $f$ is decreasing on $(-1,1)$.

**Interval 3**, $(1,3)$:Choosing 2 seems simple: $f^{\prime}(2) = -3<0$.
Again, $f$ is decreasing.

**Interval 4**, $(3,\infty)$:Choosing an very large number $p$ from this
subinterval will give a positive numerator and (of course) a positive
denominator. So $f$ is increasing on $(3,\infty)$.


In summary, $f$ is increasing on the intervals $(-\infty,-1)$ and
$(3,\infty)$ and is decreasing on the intervals $(-1,1)$ and $(1,3)$.
Since at $x=-1$, the sign of $f^\prime$ switched from positive to negative,
Theorem \@ref(thm:first-der) states that $f(-1)$ is a relative maximum
of $f$. At $x=3$, the sign of $f^\prime$ switched from negative to positive,
meaning $f(3)$ is a relative minimum. At $x=1$, $f$ is not defined, so
there is no relative extrema at $x=1$.

This is summarized in the number line shown in Figure
\@ref(fig:incrline2). Also, Figure \@ref(fig:incr2) shows a graph of
$f$, confirming our calculations. This figure also shows $f^{\prime}$,
again demonstrating that $f$ is increasing when $f^{\prime}>0$ and
decreasing when $f^{\prime}<0$.

```

```{tikz incrline2, fig.width=NULL, fig.cap="Number line for $f$ in Example \\@ref(exm:incr2ex).", cache=TRUE}
\begin{tikzpicture}
  \begin{axis}[
      numberline,
      xmin=-3,
      xmax=5,
      extra x ticks={-1, 1, 3},
      extra x tick labels={$-1$,$1$, $3$},
    ]
    \addplot[guideline] coordinates {(-1,0) (-1,2)};
    \addplot[guideline] coordinates {(1,0) (1,2)};
    \addplot[guideline] coordinates {(3,0) (3,2)};
    \addplot[mark=none] coordinates {(-2,1)} node {\parbox{3em}{\centering \small $f'>0$\\$f$ incr }};
    \addplot[mark=none] coordinates {(0,1)} node {\parbox{3em}{\centering \small $f'<0$\\$f$ decr }};
    \addplot[mark=none] coordinates {(2,1)} node {\parbox{3em}{\centering \small $f'<0$\\$f$ decr }};
    \addplot[mark=none] coordinates {(4,1)} node {\parbox{3em}{\centering \small $f'>0$\\$f$ incr }};
    \addplot[mark=none] coordinates {(-1,2)} node[above] {\parbox{3em}{\centering \small  rel\\max}};
    \addplot[mark=none] coordinates {(1,2)} node[above] {\parbox{3em}{\centering \small  VA}};
    \addplot[mark=none] coordinates {(3,2)} node[above] {\parbox{3em}{\centering \small  rel\\min}};
  \end{axis}
\end{tikzpicture}
```

```{geogebra, label="incr2"}
material_id: wtagdqzb
caption: >
    A graph of $f(x)$ in Example \@ref(exm:incr2ex), showing where
    $f$ is increasing and decreasing.

```


One is often tempted to think that functions always alternate
"increasing, decreasing, increasing, decreasing,$\ldots$" around
critical values. Our previous example demonstrated that this is not
always the case. While $x=1$ was not technically a critical value, it
was an important value we needed to consider. We found that $f$ was
decreasing on "both sides of $x=1.$"

We examine one more example.

```{youtube}
id: T4RxcQnNotc
```

```{example, label="incr3ex", echo=TRUE}

(Using the First Derivative Test). Find the intervals on which
$f(x) = x^{8/3}-4x^{2/3}$ is increasing and decreasing and identify the
relative extrema.

------------------------------------------------------------------------

We again start with taking a derivative. Since we know we want to solve
$f^{\prime}(x) = 0$, we will do some algebra after taking the
derivative.

$$\begin{aligned}
f(x) &= x^{\frac{8}{3}}-4x^{\frac{2}{3}} \\
f^{\prime}(x) &= \frac 83 x^{\frac 53} - \frac 83x^{-\frac 13}\\
    &= \frac 83x^{-\frac 13}\left(x^{\frac 63}-1\right)\end{aligned}$$
$$\begin{aligned}
    &=\frac 83x^{-\frac 13}(x^2-1)\\
    &=\frac 83x^{-\frac 13}(x-1)(x+1).\end{aligned}$$

This derivation of $f^{\prime}$ shows that $f^{\prime}(x) = 0$ when
$x=\pm 1$ and $f^\prime$ is not defined when $x=0$. Thus we have 3 critical
values, breaking the number line into 4 subintervals as shown in Figure
\@ref(fig:incrline3).

**Interval 1**, $(\infty,-1)$: We choose $p=-2$; we can easily verify
that $f^{\prime}(-2)<0$. So $f$ is decreasing on $(-\infty,-1)$.

**Interval 2**, $(-1,0)$: Choose $p=-1/2$. Once more we practice finding
the sign of $f^{\prime}(p)$ without computing an actual value. We have
$f^{\prime}(p) = (8/3)p^{-1/3}(p-1)(p+1)$; find the sign of each of the
three terms.
$$f^{\prime}(p) = \frac 83 \cdot \underbrace{p^{-\frac 13}}_{<0}\cdot \underbrace{(p-1)}_{<0}\underbrace{(p+1)}_{>0}.$$
We have a "negative $\times$ negative $\times$ positive" giving a
positive number; $f$ is increasing on $(-1,0)$.

**Interval 3**, $(0,1)$: We do a similar sign analysis as before, using
$p$ in $(0,1)$.
$$f^{\prime}(p) = \frac 83 \cdot \underbrace{p^{-\frac 13}}_{>0}\cdot \underbrace{(p-1)}_{<0}\underbrace{(p+1)}_{>0}.$$
We have 2 positive factors and one negative factor; $f^{\prime}(p)<0$
and so $f$ is decreasing on $(0,1)$.

**Interval 4**, $(1,\infty)$: Similar work to that done for the other
three intervals shows that $f^{\prime}(x)>0$ on $(1,\infty)$, so $f$ is
increasing on this interval.

We conclude by stating that $f$ is increasing on the intervals $(-1,0)$
and $(1,\infty)$ and decreasing on the intervals $(-\infty,-1)$ and
$(0,1)$. The sign of $f^\prime$ changes from negative to positive around $x=-1$
and $x=1$, meaning by Theorem \@ref(thm:first-der) that $f(-1)$ and
$f(1)$ are relative minima of $f$. As the sign of $f^\prime$ changes from
positive to negative at $x=0$, we have a relative maximum at $f(0)$.
Figure \@ref(fig:incr3) shows a graph of $f$, confirming our result. We
also graph $f^{\prime}$, highlighting once more that $f$ is increasing
when $f^{\prime}>0$ and is decreasing when $f^{\prime}<0$.
```

```{tikz incrline3, fig.width=NULL, fig.cap="Number line for $f$ in Example \\@ref(exm:incr3ex).", cache=TRUE}
\begin{tikzpicture}
 \begin{axis}[
      numberline,
      xmin=-2,
      xmax=2,
      extra x ticks={-1, 0, 1},
      extra x tick labels={$-1$,$0$, $1$},
    ]
    \addplot[guideline] coordinates {(-1,0) (-1,2)};
    \addplot[guideline] coordinates {(0,0) (0,2)};
    \addplot[guideline] coordinates {(1,0) (1,2)};
    \addplot[mark=none] coordinates {(-1.5,1)} node {\parbox{3em}{\centering \small $f'<0$\\$f$ decr }};
    \addplot[mark=none] coordinates {(-0.5,1)} node {\parbox{3em}{\centering \small $f'>0$\\$f$ incr }};
    \addplot[mark=none] coordinates {(0.5,1)}  node {\parbox{3em}{\centering \small $f'<0$\\$f$ decr }};
    \addplot[mark=none] coordinates {(1.5,1)}  node {\parbox{3em}{\centering \small $f'>0$\\$f$ incr }};
    \addplot[mark=none] coordinates {(-1,2)} node[above] {\parbox{3em}{\centering \small rel\\min}};
    \addplot[mark=none] coordinates {(0,2)} node[above] {\parbox{3em}{\centering \small rel\\max}};
    \addplot[mark=none] coordinates {(1,2)} node[above] {\parbox{3em}{\centering \small rel\\min}};
  \end{axis}
\end{tikzpicture}
```
```{geogebra, label="incr3"}
material_id: kmc6vpdy
caption: >
    A graph of $f(x)$ in Example \@ref(exm:incr3ex), showing where
    $f$ is increasing and decreasing.

```


We have seen how the first derivative of a function helps determine when
the function is going "up" or "down." In the next section, we will see
how the second derivative helps determine how the graph of a function
curves.
