## Taylor Polynomials {#sec:taylor-poly}

```{youtube}
id: SYJ2uGJCQdY
```

Consider a function $y=f(x)$ and a point $\big(c,f(c)\big)$. The
derivative, $f^{\prime}(c)$, gives the instantaneous rate of change of
$f$ at $x=c$. Of all lines that pass through the point
$\big(c,f(c)\big)$, the line that best approximates $f$ at this point is
the tangent line; that is, the line whose slope (rate of change) is
$f^{\prime}(c)$.

```{geogebra taypolyintroa}
material_id: rwgq7vkm
caption: Plotting $y=f(x)$ and its tangent line at 0.
```

```{youtube}
id: Eko7c9FNUKY
```

In Figure \@ref(fig:taypolyintroa), we see a function $y=f(x)$ graphed.
The table below the graph shows that $f(0)=2$ and $f^{\prime}(0) = 1$;
therefore, the tangent line to $f$ at $x=0$ is
$p_1(x) = 1(x-0)+2 = x+2$. The tangent line is also given in the figure.
Note that "near" $x=0$, $p_1(x) \approx f(x)$; that is, the tangent line
approximates $f$ well.



:::{.floatright}

\begin{aligned}
f(0)&= 2\\
f'(0) &= 1\\
f''(0)&=2\\
f'''(0)&=-1\\
f^{(4)}(0)&=-12\\
f^{(5)}(0)&=-19
\end{aligned}

:::


One shortcoming of this linear approximation is that the tangent line only
matches the slope of $f$; it does not, for instance, match the concavity
of $f$. We can find a polynomial, $p_2(x)$, that does match the
concavity without much difficulty, though. The table of values of the function and its derivatives to the right gives the following information about the function at $x=0$:
$$f(0) = 2 \qquad f^{\prime}(0) = 1 \qquad f^{\prime\prime}(0) = 2.$$
Therefore, we want our polynomial $p_2(x)$ to have these same
properties. That is, we need
$$p_2(0) = 2 \qquad p_2'(0) = 1 \qquad p_2''(0) = 2.$$
```{youtube}
id: v8mPY7fu1e0
```

Let's start with a general quadratic function $p(x)=a_0+a_1 x + a_2 x^2$.

We find the following:
\begin{align}
p_2(x) & = a_0+a_1x+a_2x^2 & p_2(0)&=a_0\\
p_2''(x) & = a_1+2a_2x & p_2''(0) & = a_1\\
p_2'''(x) & = 2a_2 & p_2'''(0) & = 2a_2.
\end{align}

To get the desired properties above, we must have

$$a_0 = f(0) = 2,\qquad a_1 = f'(0) = 1,\qquad 2a_2 = f''(0) = 2,$$
so $a_0=2$, $a_1 = 1$, and $a_2 = 2/2 = 1$, giving us the polynomial
$$p_2(x)=2+x+x^2.$$

We can repeat this approximation process by creating polynomials of higher degree that match more of the derivatives of 
$f$ at $x=0.$ In general, a polynomial of degree $n$ can be created to match the first $n$ derivatives of $f$. Figure \@ref(fig:taypolyintrob) cycles through the first five polynomials created in this way. Setting $n=$ in the controls, for example, shows $p_4(x)=−x^4/2−x^3/6+x^2+x+2,$ whose first four derivatives at 0 match those of $f$.

```{geogebra, label="taypolyintrob"}
material_id: baxv7pvr
caption: Plotting $f$, along with the $n$-th order polynomial approximation near $x=0$. The animation cycles through the first five polynomials.

```

How do we ensure that the derivatives of our polynomial match those of 
$f$? We simply begin with a polynomial of the desired degree, compute its derivatives, and compare them to those of 
$f$! Recall that each term in a polynomial consists of a power of $x$ and a coefficient, like so: 
$a_nx^n.$ Our goal is to determine the value for each coefficient $a_n$ so that the derivatives of our polynomial match those of our function $f.$ If we take $k$ derivatives of the term $a_nx^n$, with $k\leq n,$ we obtain
$$\frac{d^k}{dx^k}(a_nx^n)= n(n-1)\cdots (n-k+1)a_nx^{n-k}\text{.}$$
For $k<n,$ the expression above vanishes when we set $x=0.$ However, for $n=k,$ we obtain the constant value
\begin{equation}
\frac{d^k}{dx^k}(a_kx^k) = k\cdot (k-1)\cdots 2\cdot 1 a_k\text{.} (\#eq:taycoef)
\end{equation}
Consider a polynomial
$$p_n(x) = a_0+a_1x+\cdots +a_kx^k+\cdots +a_nx^n$$
of degree $n.$ If we take $k$ derivatives, all of the terms involving powers of $x$ less than $k$ disappear, and when we set 
$x=0$, all of the terms involving powers of $x$ larger than $k$ disappear, leaving us with the single constant given in Equation \@ref(eq:taycoef).

Recalling the factorial notation $k!=1\cdot 2\cdot 3\cdots k$ for the product of the first $k$ integers, we have shown that
$$p_n^{(k)}(0) = k!a_k\text{.}$$
If we want the derivatives of $p_n$ to agree with some unknown function $f$ when $x=0$, then we must have 
$$a_k = \frac{f^{(k)}(0)}{k!}\text{.}$$

```{geogebra, label="taypolyintroc"}
material_id: xzrhtznu
caption: Plotting $f$ and $p_{13}$.

```



As we use more and more derivatives, our polynomial approximation to $f$
gets better and better. In this example, the interval on which the
approximation is "good" gets bigger and bigger. Figure
\@ref(fig:taypolyintroc) shows $p_{13}(x)$; we can visually affirm that
this polynomial approximates $f$ very well on $[-2,3]$. (The polynomial
$p_{13}(x)$ is not particularly "nice". It is
\begin{gathered}
\frac{16901x^{13}}{6227020800}+\frac{13x^{12}}{1209600}-\frac{1321x^{11}}{39916800}-\frac{779x^{10}}{1814400}-\frac{359x^9}{362880}+\\
\frac{x^8}{240}+\frac{139x^7}{5040}+\frac{11 x^6}{360}-\frac{19x^5}{120}-\frac{x^4}{2}-\frac{x^3}{6}+x^2+x+2.)
\end{gathered}

```{youtube}
id: J-5vVJIGQp4
```

### Taylor Polynomials {-}

The polynomials we have created are examples of *Taylor polynomials*,
named after the British mathematician [Brook Taylor](https://mathshistory.st-andrews.ac.uk/Biographies/Taylor/){:target="_blank"} who made important
discoveries about such functions. While we created the above Taylor
polynomials by solving initial--value problems, it can be shown that
Taylor polynomials follow a general pattern that make their formation
much more direct. This is described in the following definition.

```{definition, label="taypoly", echo=TRUE}

(Taylor Polynomial, Maclaurin Polynomial). Let $f$ be a function whose
first $n$ derivatives exist at $x=c$.

1.  The **Taylor polynomial of degree $n$ of $f$ at $x=c$** is $$p_n(x) = f(c) + f^{\prime}(c)(x-c) + \frac{f^{\prime\prime}(c)}{2!}(x-c)^2+\frac{f^{\prime\prime\prime}(c)}{3!}(x-c)^3+\cdots+\frac{f^{(n)}(c)}{n!}(x-c)^n.$$

2.  A special case of the Taylor polynomial is the Maclaurin polynomial ([Colin Maclaurin](https://mathshistory.st-andrews.ac.uk/Biographies/Maclaurin/){:target="_blank"}),
    where $c=0$. That is, the **Maclaurin polynomial of degree $n$ of
    $f$** is $$p_n(x) = f(0) + f^{\prime}(0)x + \frac{f^{\prime\prime}(0)}{2!}x^2+\frac{f^{\prime\prime\prime}(0)}{3!}x^3+\cdots+\frac{f\,^{(n)}(0)}{n!}x^n.$$

```



We will practice creating Taylor and Maclaurin polynomials in the
following examples.

```{youtube}
id: ENf-Z2pLrJg
```

```{example, label="taypoly1", echo=TRUE}

(Finding and using Maclaurin polynomials).

1.  Find the $n^\text{th}$ Maclaurin polynomial for $f(x) = e^x$.

2.  Use $p_5(x)$ to approximate the value of $e$.

------------------------------------------------------------------------

1.  We start with creating a table of the derivatives of $e^x$ evaluated
    at $x=0$. In this particular case, this is relatively simple, as
    shown below.
    \begin{aligned}
    f(x)&=e^x & f(0) &= 1\\
    f'(x)&=e^x & f'(0) &= 1\\
    f''(x)&=e^x & f''(0) &= 1\\
    &\vdots & &\vdots \\
    f^{(n)}(x)&=e^x & f^{(n)}(0) &= 1\\
    \end{aligned}

    By the definition of the Maclaurin series, we have

    $$\begin{aligned}
    p_n(x) &= f(0) + f^{\prime}(0)x + \frac{f^{\prime\prime}(0)}{2!}x^2+\frac{f^{\prime\prime\prime}(0)}{3!}x^3+\cdots+\frac{f\,^{(n)}(0)}{n!}x^n\\
                &= 1+x+\frac{1}{2}x^2+\frac{1}{6}x^3 + \frac{1}{24}x^4 + \cdots + \frac{1}{n!}x^n.\end{aligned}$$

2.  Using our answer from part 1, we have
    $$p_5 = 1+x+\frac{1}{2}x^2+\frac{1}{6}x^3 + \frac{1}{24}x^4 + \frac{1}{120}x^5.$$
    To approximate the value of $e$, note that
    $e = e^1 = f(1) \approx p_5(1).$ It is very straightforward to
    evaluate $p_5(1)$:
    $$p_5(1) = 1+1+\frac 12+\frac 16+\frac 1{24}+\frac 1{120} = \frac{163}{60} \approx 2.71667.$$

    A plot of $f(x)=e^x$ and $p_5(x)$ is given in Figure
    \@ref(fig:taypoly1b).



```

```{geogebra, label="taypoly1b"}
material_id: anqhv34y
caption: A plot of $f(x)=e^x$ and its first 5 Maclaurin polynomials $p_1(x)$ through $p_5(x)$.

```


```{youtube}
id: 6BeNQe0hl3k
```

```{example, label="taypoly2", echo=TRUE}

(Finding and using Taylor polynomials).

1.  Find the $n^\text{th}$ Taylor polynomial of $y=\ln x$ at $x=1$.

2.  Use $p_6(x)$ to approximate the value of $\ln 1.5$.

3.  Use $p_6(x)$ to approximate the value of $\ln 2$.

------------------------------------------------------------------------

1.  We begin by creating a table of derivatives of $\ln x$ evaluated at
    $x=1$. While this is not as straightforward as it was in the
    previous example, a pattern does emerge, as shown below.
    \begin{aligned}
        f(x) &= \ln x  & f(1) &= 0 \\
        f'(x) &= 1/x & f'(1) &= 1 \\
        f''(x) &= -1/x^2 & f''(1) &= -1\\
        f'''(x) &= 2/x^3 & f'''(1) &= 2\\
        f^{(4)}(x) &= -6/x^4 & f^{(4)}(1) &= -6\\
        & \vdots & & \vdots \\
        f^{(n)}(x) &= \frac{(-1)^{n+1}(n-1)!}{x^n} & f^{(n)}(1) &= (-1)^{n+1}(n-1)! 
    \end{aligned}
        Note that starting at $n=1$ the coefficients alternate sign, and ignoring the sign they follow
        a factorial sequence.
        
    Using Definition \@ref(def:taypoly), we have $$\begin{aligned}
        p_n(x) &=   f(c) + f^{\prime}(c)(x-c) + \frac{f^{\prime\prime}(c)}{2!}(x-c)^2+\frac{f^{\prime\prime\prime}(c)}{3!}(x-c)^3+\cdots+\frac{f\,^{(n)}(c)}{n!}(x-c)^n\\
                        &= 0+(x-1)-\frac 12(x-1)^2+\frac 13(x-1)^3-\frac 14(x-1)^4+\cdots+\frac{(-1)^{n+1}}{n}(x-1)^n.\end{aligned}$$
    Note how the coefficients of the $(x-1)$ terms turn out to be
    "nice."

2.  We can compute $p_6(x)$ using our work above:
    $$p_6(x) = (x-1)-\frac 12(x-1)^2+\frac 13(x-1)^3-\frac 14(x-1)^4+\frac 15(x-1)^5-\frac 16(x-1)^6.$$
    Since $p_6(x)$ approximates $\ln x$ well near $x=1$, we approximate
    $\ln 1.5 \approx p_6(1.5)$:

    $$\begin{aligned}
    p_6(1.5) &= (1.5-1)-\frac 12(1.5-1)^2+\frac 13(1.5-1)^3-\frac 14(1.5-1)^4+\cdots \\
                &\cdots +\frac 15(1.5-1)^5-\frac 16(1.5-1)^6\\
        &=\frac{259}{640}\\
        &\approx 0.404688.\end{aligned}$$ This is a good approximation
    as a calculator shows that $\ln 1.5 \approx 0.4055.$ Figure
    \@ref(fig:taypoly2b) plots $y=\ln x$ with $y=p_6(x)$. We can see
    that $\ln 1.5\approx p_6(1.5)$.



3.  We approximate $\ln 2$ with $p_6(2)$: $$\begin{aligned}
    p_6(2) &= (2-1)-\frac 12(2-1)^2+\frac 13(2-1)^3-\frac 14(2-1)^4+\cdots \\
                &\cdots +\frac 15(2-1)^5-\frac 16(2-1)^6\\
                &=  1-\frac 12+\frac 13-\frac 14+\frac 15-\frac 16 \\
                &= \frac{37}{60}\\ 
                &\approx 0.616667.\end{aligned}$$ This approximation is
    not terribly impressive: a hand held calculator shows that
    $\ln 2 \approx 0.693147.$ The graph in Figure \@ref(fig:taypoly2b)
    shows that $p_6(x)$ provides less accurate approximations of $\ln x$
    as $x$ gets close to 0 or 2.

    Surprisingly enough, even the 20$^\text{th}$ degree Taylor
    polynomial fails to approximate $\ln x$ for $x>2$, as shown in
    Figure \@ref(fig:taypoly2c). We'll soon discuss why this is.



```

```{geogebra, label="taypoly2b"}
material_id: vqfjhnxs
caption: A plot of $y=\ln x$ and its Taylor polynomials of order 1 through 20 at $x=1$.

```

Taylor polynomials are used to approximate functions $f(x)$ in mainly
two situations:

1.  When $f(x)$ is known, but perhaps "hard" to compute directly. For
    instance, we can define $y=\cos x$ as either the ratio of sides of a
    right triangle ("adjacent over hypotenuse") or with the unit circle.
    However, neither of these provides a convenient way of computing
    $\cos 2$. A Taylor polynomial of sufficiently high degree can
    provide a reasonable method of computing such values using only
    operations usually hard--wired into a computer ($+$, $-$, $\times$
    and $\div$).

2.  When $f(x)$ is not known, but information about its derivatives is
    known. This occurs more often than one might think, especially in
    the study of differential equations.

> **Note:** Even though Taylor polynomials *could* be used in
> calculators and computers to calculate values of trigonometric
> functions, in practice they generally aren't. Other more efficient and
> accurate methods have been developed, such as the CORDIC algorithm.

In both situations, a critical piece of information to have is "How good
is my approximation?" If we use a Taylor polynomial to compute $\cos 2$,
how do we know how accurate the approximation is? 

### Approximation Error of Taylor Polynomials {-}

Although much of the content presented in Calculus concerns the search for exact answers to problems such as integration and differentiation, many practical applications of calculus involve attempts to find approximations; for example, using Newton's Method to approximate the zeros of a function, or numerical integration to approximate the value of an integral that cannot be solved exactly. Whenever an approximation is used, one naturally wishes to know how good the approximation is. In other words, we look for a bound on the error introduced by working with an approximation. The following theorem gives bounds on the error introduced in using a Taylor (and hence Maclaurin) polynomial to approximate a function.

```{youtube}
id: 2IHECY8dFN0
```

```{theorem, label="taylorthm", echo=TRUE}

(Taylor's Theorem).

1.  Let $f$ be a function whose $n+1^\text{th}$ derivative exists on an
    interval $I$ and let $c$ be in $I$. Then, for each $x$ in $I$, there
    exists $z_x$ between $x$ and $c$ such that
    $$f(x) = f(c) + f^{\prime}(c)(x-c) + \frac{f^{\prime\prime}(c)}{2!}(x-c)^2+ \cdots +\frac{f\,^{(n)}(c)}{n!}(x-c)^n+R_n(x),$$
    where
    $\displaystyle R_n(x) = \frac{f\,^{(n+1)}(z_x)}{(n+1)!}(x-c)^{(n+1)}.$

2.  $\displaystyle\big|R_n(x)\big| \leq \frac{\max\left|\,f\,^{(n+1)}(z)\right|}{(n+1)!}\big|(x-c)^{(n+1)}\big|$,
    where $z$ is in $I$.

```

The first part of Taylor's Theorem states that $f(x) = p_n(x) + R_n(x)$,
where $p_n(x)$ is the $n^\text{th}$ order Taylor polynomial and $R_n(x)$
is the remainder, or error, in the Taylor approximation. The second part
gives bounds on how big that error can be. If the $(n+1)^\text{th}$
derivative is large on $I$, the error may be large; if $x$ is far from
$c$, the error may also be large. However, the $(n+1)!$ term in the
denominator tends to ensure that the error gets smaller as $n$
increases.

The following example computes error estimates for the approximations of
$\ln 1.5$ and $\ln 2$ made in Example \@ref(exm:taypoly2).\

```{youtube}
id: TBV4-X7HoHk
```

```{example, label="taypoly3", echo=TRUE}

(Finding error bounds of a Taylor polynomial). Use Theorem
\@ref(thm:taylorthm) to find error bounds when approximating $\ln 1.5$
and $\ln 2$ with $p_6(x)$, the Taylor polynomial of degree 6 of
$f(x)=\ln x$ at $x=1$, as calculated in Example \@ref(exm:taypoly2).

------------------------------------------------------------------------

1.  We start with the approximation of $\ln 1.5$ with $p_6(1.5)$. The
    theorem references an open interval $I$ that contains both $x$ and
    $c$. The smaller the interval we use the better; it will give us a
    more accurate (and smaller!) approximation of the error. We let
    $I = (0.9,1.6)$, as this interval contains both $c=1$ and $x=1.5$.

    The theorem references $\max\big|f\,^{(n+1)}(z)\big|$. In our
    situation, this is asking "How big can the $7^\text{th}$ derivative
    of $y=\ln x$ be on the interval $(0.9,1.6)$?" The seventh derivative
    is $y = -6!/x^7$. The largest value it attains on $I$ is about 1506.
    Thus we can bound the error as: $$\begin{aligned}
    \big|R_6(1.5)\big| &\leq \frac{\max\big|f\,^{(7)}(z)\big|}{7!}\big|(1.5-1)^7\big|\\
                        &\leq \frac{1506}{5040}\cdot\frac 1{2^7}\\
                        &\approx 0.0023.\end{aligned}$$ We computed
    $p_6(1.5) = 0.404688$; using a calculator, we find
    $\ln 1.5 \approx 0.405465$, so the actual error is about $0.000778$,
    which is less than our bound of $0.0023$. This affirms Taylor's
    Theorem; the theorem states that our approximation would be within
    about 2 thousandths of the actual value, whereas the approximation
    was actually closer.

2.  We again find an interval $I$ that contains both $c=1$ and $x=2$; we
    choose $I = (0.9,2.1)$. The maximum value of the seventh derivative
    of $f$ on this interval is again about 1506 (as the largest values
    come near $x=0.9$). Thus $$\begin{aligned}
    \big| R_6(2)\big| &\leq \frac{\max\big|f\,^{(7)}(z)\big|}{7!}\big|(2-1)^7\big|\\
                        &\leq \frac{1506}{5040}\cdot 1^7\\
                        &\approx 0.30.\end{aligned}$$ This bound is not
    as nearly as good as before. Using the degree 6 Taylor polynomial at
    $x =1$ will bring us within 0.3 of the correct answer. As
    $p_6(2)\approx 0.61667$, our error estimate guarantees that the
    actual value of $\ln 2$ is somewhere between $0.31667$ and
    $0.91667$. These bounds are not particularly useful.

    In reality, our approximation was only off by about 0.07. However,
    we are approximating ostensibly because we do not know the real
    answer. In order to be assured that we have a good approximation, we
    would have to resort to using a polynomial of higher degree.

```

We practice again. This time, we use Taylor's theorem to find $n$ that
guarantees our approximation is within a certain amount.

```{youtube}
id: zg1W9miUCB4
```

```{example, label="taypoly4", echo=TRUE}

(Finding sufficiently accurate Taylor polynomials). Find $n$ such that
the $n^\text{th}$ Taylor polynomial of $f(x)=\cos x$ at $x=0$
approximates $\cos 2$ to within $0.001$ of the actual answer. What is
$p_n(2)$?

------------------------------------------------------------------------

Following Taylor's theorem, we need bounds on the size of the
derivatives of $f(x)=\cos x$. In the case of this trigonometric
function, this is easy. All derivatives of cosine are $\pm \sin x$ or
$\pm \cos x$. In all cases, these functions are never greater than 1 in
absolute value. We want the error to be less than $0.001$. To find the
appropriate $n$, consider the following inequalities: $$\begin{aligned}
\frac{\max\big|f\,^{(n+1)}(z)\big|}{(n+1)!}\big|(2-0)^{(n+1)}\big| &\leq 0.001 \\
\frac 1{(n+1)!}\cdot 2^{(n+1)} &\leq 0.001\end{aligned}$$ We find an $n$
that satisfies this last inequality with trial--and--error. When $n=8$,
we have $\displaystyle\frac{2^{8+1}}{(8+1)!} \approx 0.0014$; when
$n=9$, we have
$\displaystyle\frac{2^{9+1}}{(9+1)!} \approx 0.000282 <0.001$. Thus we
want to approximate $\cos 2$ with $p_9(2)$.\
We now set out to compute $p_9(x)$. We again need a table of the
derivatives of $f(x)=\cos x$ evaluated at $x=0$. A table of these values
is given below.
$$\begin{aligned}
f(x)&=\cos x & f(0)&=1 \\
f'(x)&=\sin x & f'(0)&=0 \\
f''(x)&=-\cos x & f''(0)&=-1 \\
f'''(x)&=-\sin x & f'''(0)&=0 \\
f^{(4)}(x)&=\cos x & f^{(4)}(0)&=1 \\
&\vdots &&\vdots
\end{aligned}$$

Since the higher order derivatives of $\cos x$ loop through $\sin x$, $-\cos x$, and $-\sin x$ 
forever, so do the values of the functions at zero loop through the values $1, 0 , -1 ,0$ forever.
Notice how the derivatives, evaluated at $x=0$, follow a certain
pattern. All the odd powers of $x$ in the Taylor polynomial will
disappear as their coefficient is 0. While our error bounds state that
we need $p_9(x)$, our work shows that this will be the same as $p_8(x)$.

Since we are forming our polynomial at $x=0$, we are creating a
Maclaurin polynomial, and: $$\begin{aligned}
p_8(x) &= f(0) + f^{\prime}(0)x + \frac{f^{\prime\prime}(0)}{2!}x^2 + \frac{f^{\prime\prime\prime}(0)}{3!}x^3 + \cdots +\frac{f\,^{(8)}(0)}{8!}x^8\\
        &=  1-\frac{1}{2!}x^2+\frac{1}{4!}x^4-\frac{1}{6!}x^6+\frac{1}{8!}x^8\end{aligned}$$

We finally approximate $\cos 2$:
$$\cos 2 \approx p_8(2) = -\frac{131}{315} \approx -0.41587.$$ Our error
bound guarantee that this approximation is within $0.001$ of the correct
answer. Technology shows us that our approximation is actually within
about $0.0003$ of the correct answer.

Set $n=8$ in Figure \@ref(fig:taypoly4b) to see a graph of $y=p_8(x)$ and $y=\cos x$.
Note how well the two functions agree on about $(-\pi,\pi)$.
```



```{geogebra, label="taypoly4b"}
material_id: vq2kxrkf
caption: A graph of $f(x)= \cos x$ and its Maclaurin polynomials of order 2 through 20.

```

```{example, label="taypoly5", echo=TRUE}

(Finding and using Taylor polynomials).

1.  Find the degree 4 Taylor polynomial, $p_4(x)$, for $f(x)=\sqrt{x}$
    at $x=4.$

2.  Use $p_4(x)$ to approximate $\sqrt{3}$.

3.  Find bounds on the error when approximating $\sqrt{3}$ with
    $p_4(3)$.

------------------------------------------------------------------------

1.  We begin by evaluating the derivatives of $f$ at $x=4$. This is done
    below.
    $$\begin{aligned}
    f(x)&=\sqrt x & f(4)&=2\\
    f'(x)&=1/(2\sqrt x) & f'(4)&=1/4\\
    f''(x)&=-1/(4x^{3/2}) & f''(4)&=-1/32\\
    f'''(x)&=3/(8x^{5/2}) & f'''(4)&=3/256\\
    f^{(4)}(x)&=-15/(16x^{7/2}) & f^{(4)}(4)&=-15/2048
    \end{aligned}$$

    These values allow us to form the Taylor polynomial $p_4(x)$:
    $$p_4(x) = 2 + \frac 14(x-4) +\frac{-1/32}{2!}(x-4)^2+\frac{3/256}{3!}(x-4)^3+\frac{-15/2048}{4!}(x-4)^4.$$

2.  As $p_4(x) \approx \sqrt{x}$ near $x=4$, we approximate $\sqrt{3}$
    with $p_4(3) = 1.73212$.

3.  To find a bound on the error, we need an open interval that contains
    $x=3$ and $x=4$. We set $I = (2.9,4.1)$. The largest value the fifth
    derivative of $f(x)=\sqrt{x}$ takes on this interval is near
    $x=2.9$, at about $0.0273$. Thus
    $$\big|R_4(3)\big| \leq \frac{0.0273}{5!}\big|(3-4)^5\big| \approx 0.00023.$$
    This shows our approximation is accurate to at least the first 3
    places after the decimal. (It turns out that our approximation is
    actually accurate to 4 places after the decimal.) A graph of
    $f(x)=\sqrt x$ and $p_4(x)$ is given in Figure \@ref(fig:taypoly5b).
    Note how the two functions are nearly indistinguishable on $(2,7)$.



```

```{tikz, label="taypoly5b", fig.cap="A plot of $f(x)=\\sqrt{x}$ and its degree 4 Taylor polynomial at $x=4$."}
                \begin{tikzpicture}

                \begin{axis}[
                 axis x line = middle,
                axis y line = middle,                      
                axis on top,
                ymin=-.1,ymax=3.5,
                xmin=-1,xmax=11
                ]

                \addplot+ [-,domain=0:3.16,samples=40, no markers] ({x^2},{x}) node [pos=1,above left] { $y=\sqrt x$};
                \addplot+ [-, no markers] coordinates {(0,0.5469)(0.2,0.6536)(0.4,0.7551)(0.6,0.8518)(0.8,0.944)(1.,1.032)(1.
                2,1.116)(1.4,1.196)(1.6,1.273)(1.8,1.346)(2.,1.417)(2.2,1.485)(2.4,1.
                55)(2.6,1.613)(2.8,1.673)(3.,1.732)(3.2,1.789)(3.4,1.844)(3.6,1.897)(
                3.8,1.949)(4.,2.)(4.2,2.049)(4.4,2.098)(4.6,2.145)(4.8,2.191)(5.,2.
                236)(5.2,2.28)(5.4,2.324)(5.6,2.366)(5.8,2.408)(6.,2.448)(6.2,2.488)(
                6.4,2.527)(6.6,2.565)(6.8,2.602)(7.,2.637)(7.2,2.672)(7.4,2.705)(7.6,
                2.737)(7.8,2.768)(8.,2.797)(8.2,2.824)(8.4,2.849)(8.6,2.873)(8.8,2.
                894)(9.,2.913)(9.2,2.929)(9.4,2.942)(9.6,2.953)(9.8,2.96)(10.,2.964)} node [pos=0.8,below right] { $y=p_{4}(x)$};

                \end{axis}

                \end{tikzpicture}


```



