## Numerical Integration {#sec:numerical-integration}

The Fundamental Theorem of Calculus gives a concrete technique for
finding the exact value of a definite integral. That technique is based
on computing antiderivatives. Despite the power of this theorem, there
are still situations where we must *approximate* the value of the
definite integral instead of finding its exact value. The first
situation we explore is where we *cannot* compute the antiderivative of
the integrand. The second case is when we actually do not know the
function in the integrand, but only its value when evaluated at certain
points.\
An **elementary function** is any function that is a combination of
polynomial, $n^{\text{th}}$ root, rational, exponential, logarithmic and
trigonometric functions. We can compute the derivative of any elementary
function, but there are many elementary functions of which we cannot
compute an antiderivative. For example, the following functions do not
have antiderivatives that we can express with elementary functions:

$$e^{-x^2}, \quad \sin(x^3)\quad \text{and} \quad \frac{\sin x}{x}.$$

The simplest way to refer to the antiderivatives of $e^{-x^2}$ is to
simply write $\int e^{-x^2}\ dx$.

This section outlines three common methods of approximating the value of
definite integrals. We describe each as a systematic method of
approximating area under a curve. By approximating this area accurately,
we find an accurate approximation of the corresponding definite
integral.

We will apply the methods we learn in this section to the following
definite integrals:

$$\int_0^1 e^{-x^2} \ dx, \quad \int_{-\frac{\pi}{4}}^{\frac{\pi}{2}} \sin(x^3) \ dx, \quad \text{and} \quad \int_{0.5}^{4\pi} \frac{\sin(x)}{x} \ dx,$$
as pictured in Figure \@ref(fig:numerical1).

::: {#fig:numerical1 .tab}
**Table 1**. caption: Graphically representing three definite integrals
that cannot be evaluated using antiderivatives.
:::

**The Left and Right Hand Rule Methods**\
In Section \@ref(sec:riemann) we addressed the problem of evaluating
definite integrals by approximating the area under the curve using
rectangles. We revisit those ideas here before introducing other methods
of approximating definite integrals.

We start with a review of notation. Let $f$ be a continuous function on
the interval $[a,b]$. We wish to approximate
$\displaystyle\int_a^b f(x)\ dx$. We partition $[a,b]$ into $n$ equally
spaced subintervals, each of length
$\displaystyle\Delta x= \frac{b-a}{n}$. The endpoints of these
subintervals are labeled as
$$x_1=a,\ x_2 = a+\Delta x,\ x_3 = a+ 2\Delta x,\ \ldots,\ x_i = a+(i-1)\Delta x,\ \ldots,\ x_{n+1} = b.$$

Key Idea \@ref(idea:riemann) states that to use the Left Hand Rule we
use the summation $\displaystyle\sum_{i=1}^n f(x_i)\Delta x$ and to use
the Right Hand Rule we use
$\displaystyle\sum_{i=1}^n f(x_{i+1})\Delta x$. We review the use of
these rules in the context of examples.\

```{example, label="num1", echo=TRUE}

(Approximating definite integrals with rectangles). Approximate
$\displaystyle\int_0^1e^{-x^2}\ dx$ using the Left and Right Hand Rules
with 5 equally spaced subintervals.

------------------------------------------------------------------------

We begin by partitioning the interval $[0,1]$ into 5 equally spaced
intervals. We have $\Delta x= \frac{1-0}5 = 1/5=0.2$, so
$$x_1 = 0,\ x_2 = 0.2,\ x_3 = 0.4,\ x_4 = 0.6,\ x_5 = 0.8,\ \text{and}\ x_6 = 1.$$

Using the Left Hand Rule, we have:

$$\begin{aligned}
\sum_{i=1}^n f(x_i)\Delta x&= \big(f(x_1)+f(x_2) + f(x_3) + f(x_4) + f(x_5)\big)\Delta x\\
                                                &= \big(f(0) + f(0.2) + f(0.4) + f(0.6) + f(0.8)\big)\Delta x\\
                                                &\approx \big(1+0.961 + 0.852 + 0.698 + 0.527)(0.2)\\
                                                &\approx 0.808.\end{aligned}$$

Using the Right Hand Rule, we have:

$$\begin{aligned}
\sum_{i=1}^n f(x_{i+1})\Delta x&= \big(f(x_2) + f(x_3) + f(x_4) + f(x_5)+f(x_6)\big)\Delta x\\
                                                &= \big(f(0.2) + f(0.4) + f(0.6) + f(0.8)+f(1)\big)\Delta x\\
                                                &\approx \big(0.961 +0.852 + 0.698 + 0.527 + 0.368)(0.2)\\
                                                &\approx 0.681.\end{aligned}$$

::: {#fig:num1 .tab}
**Table 2**. caption: Approximating $\int_0^1e^{-x^2}\ dx$ in Example
\@ref(exm:num1).
:::

Figure \@ref(fig:num1) shows the rectangles used in each method to
approximate the definite integral. These graphs show that in this
particular case, the Left Hand Rule is an over approximation and the
Right Hand Rule is an under approximation. To get a better
approximation, we could use more rectangles, as we did in Section
\@ref(sec:riemann). We could also average the Left and Right Hand Rule
results together, giving $$\frac{0.808 + 0.681}{2} = 0.7445.$$ The
actual answer, accurate to 4 places after the decimal, is 0.7468,
showing our average is a good approximation.

```

\

```{example, label="num2", echo=TRUE}

(Approximating definite integrals with rectangles). Approximate
$\displaystyle\int_{-\frac{\pi}4}^{\frac{\pi}2} \sin (x^3)\ dx$ using
the Left and Right Hand Rules with 10 equally spaced subintervals.

------------------------------------------------------------------------

We begin by finding x:
$$\frac{b-a}{n} = \frac{\pi/2 - (-\pi/4)}{10} = \frac{3\pi}{40}\approx 0.236.$$
It is useful to write out the endpoints of the subintervals in a table;
in Figure \@ref(fig:num2a), we give the exact values of the endpoints,
their decimal approximations, and decimal approximations of $\sin(x^3)$
evaluated at these points.

::: {#fig:num2a .tab}
**Table 3**. caption: Table of values used to approximate
$\int_{-\frac{\pi}4}^{\frac{\pi}2}\sin(x^3)\ dx$ in Example
\@ref(exm:num2).
:::

Once this table is created, it is straightforward to approximate the
definite integral using the Left and Right Hand Rules. (Note: the table
itself is easy to create, especially with a standard spreadsheet program
on a computer. The last two columns are all that are needed.) The Left
Hand Rule sums the first 10 values of $\sin(x_i^3)$ and multiplies the
sum by $\Delta x$; the Right Hand Rule sums the last 10 values of
$\sin(x_i^3)$ and multiplies by $\Delta x$. Therefore we have:

Left Hand Rule:
$\displaystyle\int_{-\frac{\pi}4}^{\frac{\pi}2}\sin(x^3)\ dx \approx (1.91)(0.236) = 0.451.$

Right Hand Rule:
$\displaystyle\int_{-\frac{\pi}4}^{\frac{\pi}2}\sin(x^3)\ dx \approx (1.71)(0.236) = 0.404.$

Average of the Left and Right Hand Rules: 0.4275.

::: {#fig:num2b .tab}
**Table 4**. caption: Approximating\
$\int_{-\frac{\pi}4}^{\frac{\pi}2}\sin(x^3)\ dx$ in Example
\@ref(exm:num2).
:::

The actual answer, accurate to 3 places after the decimal, is 0.460. Our
approximations were once again fairly good. The rectangles used in each
approximation are shown in Figure \@ref(fig:num2b). It is clear from the
graphs that using more rectangles (and hence, narrower rectangles)
should result in a more accurate approximation.

```

\
**The Trapezoidal Rule**

In Example \@ref(exm:num1) we approximated the value of
$\displaystyle\int-0^1 e^{-x^2}\ dx$ with 5 rectangles of equal width.
Figure \@ref(fig:num1) shows the rectangles used in the Left and Right
Hand Rules. These graphs clearly show that rectangles do not match the
shape of the graph all that well, and that accurate approximations will
only come by using lots of rectangles.

Instead of using rectangles to approximate the area, we can instead use
*trapezoids.* In Figure \@ref(fig:num3a), we show the region under
$f(x) = e^{-x^2}$ on $[0,1]$ approximated with 5 trapezoids of equal
width; the top "corners" of each trapezoid lies on the graph of $f(x)$.
It is clear from this figure that these trapezoids more accurately
approximate the area under $f$ and hence should give a better
approximation of $\int-0^1 e^{-x^2}\ dx$. (In fact, these trapezoids
seem to give a *great* approximation of the area!)

```{geogebra, label="num3a"}

caption: >
    Approximating $\int_0^1 e^{-x^2}\ dx$ using 5 trapezoids of equal widths.

```

The formula for the area of a trapezoid is given in Figure
\@ref(fig:trapezoid). We approximate $\int-0^1 e^{-x^2}\ dx$ with these
trapezoids in the following example.\

```{example, label="num3", echo=TRUE}

(Approximating definite integrals using trapezoids). Use 5 trapezoids of
equal width to approximate $\displaystyle\int_0^1e^{-x^2}\ dx$.

------------------------------------------------------------------------

To compute the areas of the 5 trapezoids in Figure \@ref(fig:num3a), it
will again be useful to create a table of values as shown in Figure
\@ref(fig:num3b).


::: {#fig:num3b .tab}
**Table 5**. caption: A table of values of $e^{-x^2}$.
:::

The leftmost trapezoid has legs of length 1 and 0.961 and a height of
0.2. Thus, by our formula, the area of the leftmost trapezoid is:
$$\frac{1+0.961}{2}(0.2) = 0.1961.$$ Moving right, the next trapezoid
has legs of length 0.961 and 0.852 and a height of 0.2. Thus its area
is: $$\frac{0.961+0.852}2(0.2) = 0.1813.$$

The sum of the areas of all 5 trapezoids is:

$$\begin{aligned}
\frac{1+0.961}{2}(0.2) + \frac{0.961+0.852}2(0.2)+\frac{0.852+0.698}2(0.2)&+ \\
\frac{0.698+0.527}2(0.2)+\frac{0.527+0.368}2(0.2)&= 0.7445.\end{aligned}$$

We approximate $\displaystyle\int_0^1 e^{-x^2}\ dx \approx 0.7445.$

```


```{geogebra, label="trapezoid"}

caption: >
    The area of a trapezoid.

```
\
There are many things to observe in this example. Note how each term in
the final summation was multiplied by both 1/2 and by $\Delta x= 0.2$.
We can factor these coefficients out, leaving a more concise summation
as:
$$\frac12(0.2)\Big[(1+0.961) + (0.961+0.852) + (0.852+0.698) + ( 0.698+ 0.527) +(0.527 + 0.368)\Big].$$
Now notice that all numbers except for the first and the last are added
twice. Therefore we can write the summation even more concisely as
$$\frac{0.2}{2}\Big[1 + 2(0.961+0.852+0.698+0.527) + 0.368\Big].$$

This is the heart of the **Trapezoidal Rule**, wherein a definite
integral $\displaystyle\int_a^b f(x) \ dx$ is approximated by using
trapezoids of equal widths to approximate the corresponding area under
$f$. Using $n$ equally spaced subintervals with endpoints $x_1$, $x_2$,
$\ldots$, $x_{n+1}$, we again have $\displaystyle\Delta x= \frac{b-a}n$.
Thus: $$\begin{aligned}
\int_a^b f(x)\ dx & \approx \sum_{i=1}^n \frac{f(x_i)+f(x_{i+1})}2\Delta x\\
                                    & = \frac{\Delta x}2 \sum_{i=1}^n \big(f(x_i)+f(x_{i+1})\big)\\
                                    & = \frac{\Delta x}2\Big[f(x_1)+ 2\sum_{i=2}^n f(x_i) + f(x_{n+1})\Big].\\ \end{aligned}$$

```{example, label="num4", echo=TRUE}

(Using the Trapezoidal Rule). Revisit Example \@ref(exm:num2) and
approximate
$\displaystyle\int_{-\frac{\pi}{4}}^{\frac{\pi}{2}} \sin (x^3)\ dx$
using the Trapezoidal Rule and 10 equally spaced subintervals.

------------------------------------------------------------------------

We refer back to Figure \@ref(fig:num2a) for the table of values of
$\sin(x^3)$. Recall that $\Delta x= 3\pi/40 \approx 0.236$. Thus we
have:$$\begin{aligned}
\int_{-\frac{\pi}4}^{\frac{\pi}2} \sin (x^3)\ dx &\approx \frac{0.236}{2}\Big[-0.466 + 2\Big(-0.165+(-0.031)+\ldots+
0.69\Big)+(-0.67)\Big]\\
            &= 0.4275.\end{aligned}$$

```

\
Notice how "quickly" the Trapezoidal Rule can be implemented once the
table of values is created. This is true for all the methods explored in
this section; the real work is creating a table of $x_i$ and $f(x_i)$
values. Once this is completed, approximating the definite integral is
not difficult. Again, using technology is wise. Spreadsheets can make
quick work of these computations and make using lots of subintervals
easy.

Also notice the approximations the Trapezoidal Rule gives. It is the
average of the approximations given by the Left and Right Hand Rules!
This effectively renders the Left and Right Hand Rules obsolete. They
are useful when first learning about definite integrals, but if a real
approximation is needed, one is generally better off using the
Trapezoidal Rule instead of either the Left or Right Hand Rule.\
How can we improve on the Trapezoidal Rule, apart from using more and
more trapezoids? The answer is clear once we look back and consider what
we have *really* done so far. The Left Hand Rule is not *really* about
using rectangles to approximate area. Instead, it approximates a
function $f$ with constant functions on small subintervals and then
computes the definite integral of these constant functions. The
Trapezoidal Rule is really approximating a function $f$ with a linear
function on a small subinterval, then computes the definite integral of
this linear function. In both of these cases the definite integrals are
easy to compute in geometric terms.

So we have a progression: we start by approximating $f$ with a constant
function and then with a linear function. What is next? A quadratic
function. By approximating the curve of a function with lots of
parabolas, we generally get an even better approximation of the definite
integral. We call this process **Simpson's Rule**, named after Thomas
Simpson (1710-1761), even though others had used this rule as much as
100 years prior.\
**Simpson's Rule**

Given one point, we can create a constant function that goes through
that point. Given two points, we can create a linear function that goes
through those points. Given three points, we can create a quadratic
function that goes through those three points (given that no two have
the same $x$--value).

Consider three points $(x_1,y_1)$, $(x_2,y_2)$ and $(x_3,y_3)$ whose
$x$--values are equally spaced and $x_1<x_2<x_3$. Let $f$ be the
quadratic function that goes through these three points. It is not hard
to show that
$$\int_{x_1}^{x_3} f(x)\ dx = \frac{x_3-x_1}{6}\big(y_1+4y_2+y_3\big).\label{eq:simpsons}$$

Consider Figure \@ref(fig:numsimpsons). A function $f$ goes through the
3 points shown and the parabola $g$ that also goes through those points
is graphed with a dashed line. Using our equation from above, we know
exactly that
$$\int-1^3 g(x) \ dx = \frac{3-1}{6}\big(3+4(1)+2\big)= 3.$$ Since $g$
is a good approximation for $f$ on $[1,3]$, we can state that
$$\int_1^3 f(x)\ dx \approx 3.$$

```{geogebra, label="numsimpsons"}

caption: >
    A graph of a function $f$ and a parabola that approximates it well on $[1,3]$.

```

Notice how the interval $[1,3]$ was split into two subintervals as we
needed 3 points. Because of this, whenever we use Simpson's Rule, we
need to break the interval into an even number of subintervals.

In general, to approximate $\displaystyle\int_a^b f(x)\ dx$ using
Simpson's Rule, subdivide $[a,b]$ into $n$ subintervals, where $n$ is
even and each subinterval has width $\Delta x= (b-a)/n$. We approximate
$f$ with $n/2$ parabolic curves, using Equation \@ref(eq:simpsons) to
compute the area under these parabolas. Adding up these areas gives the
formula:
$$\int_a^b f(x) \ dx \approx \frac{\Delta x}3\Big[f(x_1)+4f(x_2)+2f(x_3)+4f(x_4)+\ldots+2f(x_{n-1})+4f(x_n)+f(x_{n+1})\Big].$$
Note how the coefficients of the terms in the summation have the pattern
1, 4, 2, 4, 2, 4, $\ldots$, 2, 4, 1.

Let's demonstrate Simpson's Rule with a concrete example.\

```{example, label="num5", echo=TRUE}

(Using Simpson's Rule). Approximate $\displaystyle\int_0^1 e^{-x^2}\ dx$
using Simpson's Rule and 4 equally spaced subintervals.

------------------------------------------------------------------------

We begin by making a table of values as we have in the past, as shown in
Figure \@ref(fig:num5a)(a).

::: {#fig:num5a .tab}
**Table 6**. caption: A table of values to approximate
$\int_0^1e^{-x^2}\ dx$, along with a graph of the function.
:::

Simpson's Rule states that
$$\int_0^1e^{-x^2}\ dx \approx \frac{0.25}{3}\Big[1+4(0.939)+2(0.779)+4(0.570) + 0.368\Big] = 0.7468\overline{3}.$$

Recall in Example \@ref(exm:num1) we stated that the correct answer,
accurate to 4 places after the decimal, was 0.7468. Our approximation
with Simpson's Rule, with 4 subintervals, is better than our
approximation with the Trapezoidal Rule using 5!

Figure \@ref(fig:num5a)(b) shows $f(x) = e^{-x^2}$ along with its
approximating parabolas, demonstrating how good our approximation is.
The approximating curves are nearly indistinguishable from the actual
function.

```



```{example, label="num6", echo=TRUE}

(Using Simpson's Rule). Approximate
$\displaystyle\int_{-\frac{\pi}4}^{\frac{\pi}2} \sin (x^3)\ dx$ using
Simpson's Rule and 10 equally spaced intervals.

------------------------------------------------------------------------

Figure \@ref(fig:num6a) shows the table of values that we used in the
past for this problem, shown here again for convenience. Again,
$\Delta x= (\pi/2+\pi/4)/10 \approx 0.236$.

::: {#fig:num6a .tab}
**Table 7**. caption: Table of values used to approximate
$\int_{-\frac{\pi}4}^{\frac{\pi}2}\sin(x^3)\ dx$ in Example
\@ref(exm:num6).
:::

Simpson's Rule states that $$\begin{aligned}
\int_{-\frac{\pi}4}^{\frac{\pi}2} \sin (x^3)\ dx &\approx \frac{0.236}3\Big[(-0.466)+4(-0.165)+2(-0.031) + \ldots \\
            & \ldots + 2(0.971) + 4(0.69) + (-0.67)\big]\\
        &= 0.4701\end{aligned}$$


Recall that the actual value, accurate to 3 decimal places, is 0.460.
Our approximation is within one 1/100$^\text{th}$ of the correct value.
The graph in Figure \@ref(fig:num6b) shows how closely the parabolas
match the shape of the graph.

```

```{geogebra, label="num6b"}

caption: >
    Approximating $\int_{-\frac{\pi}4}^{\frac{\pi}2}\sin(x^3)\ dx$ in Example \@ref(exm:num6) with Simpson's Rule and 10 equally spaced intervals.

```

**Summary and Error Analysis**

We summarize the key concepts of this section thus far in the following
Key Idea.

Let $f$ be a continuous function on $[a,b]$, let $n$ be a positive
integer, and let $\displaystyle\Delta x= \frac{b-a}{n}$.

Set $x_1=a$, $x_2 = a+\Delta x$, $\ldots$, $x_i = a+(i-1)\Delta x$,
$x_{n+1}=b$.

Consider $\displaystyle\int_a^b f(x)\ dx$.

Left Hand Rule:
$\displaystyle\int_a^b f(x)\ dx \approx \Delta x\Big[f(x_1) + f(x_2) + \ldots + f(x_n)\big]$.\
Right Hand Rule:
$\displaystyle\int_a^b f(x)\ dx \approx \Delta x\Big[f(x_2) + f(x_3) + \ldots + f(x_{n+1})\big]$.\
Trapezoidal Rule:
$\displaystyle\int_a^b f(x)\ dx \approx \frac{\Delta x}2\Big[f(x_1) + 2f(x_2) + 2f(x_3) +\ldots + 2f(x_n)+ f(x_{n+1})\big]$.\
Simpson's Rule:
$\displaystyle\int_a^b f(x)\ dx \approx \frac{\Delta x}3\Big[f(x_1) + 4f(x_2) + 2f(x_3) +\ldots + 4f(x_n)+ f(x_{n+1})\big]$
($n$ even).

\
In our examples, we approximated the value of a definite integral using
a given method then compared it to the "right" answer. This should have
raised several questions in the reader's mind, such as:

1.  How was the "right" answer computed?

2.  If the right answer can be found, what is the point of
    approximating?

3.  If there is value to approximating, how are we supposed to know if
    the approximation is any good?

These are good questions, and their answers are educational. In the
examples, *the* right answer was never computed. Rather, an
approximation accurate to a certain number of places after the decimal
was given. In Example \@ref(exm:num1), we do not know the *exact*
answer, but we know it starts with 0.7468. These more accurate
approximations were computed using numerical integration but with more
precision (i.e., more subintervals and the help of a computer).

Since the exact answer cannot be found, approximation still has its
place. How are we to tell if the approximation is any good?

"Trial and error" provides one way. Using technology, make an
approximation with, say, 10, 100, and 200 subintervals. This likely will
not take much time at all, and a trend should emerge. If a trend does
not emerge, try using yet more subintervals. Keep in mind that trial and
error is never foolproof; you might stumble upon a problem in which a
trend will not emerge.

A second method is to use Error Analysis. While the details are beyond
the scope of this text, there are some formulas that give *bounds* for
how good your approximation will be. For instance, the formula might
state that the approximation is within 0.1 of the correct answer. If the
approximation is 1.58, then one knows that the correct answer is between
1.48 and 1.68. By using lots of subintervals, one can get an
approximation as accurate as one likes. Theorem
\@ref(thm:numerical-error) states what these bounds are.

```{theorem, echo=TRUE}

(t). 185ptError Bounds in the Trapezoidal Rule and Simpson's Rule\]
[\[thm:numerical_error\]]{#thm:numerical_error
label="thm:numerical_error"}

1.  Let $E_T$ be the error in approximating
    $\displaystyle\int_a^b f(x)\ dx$ using the Trapezoidal Rule with $n$
    subintervals.

    If $f$ has a continuous 2$^\text{nd}$ derivative on $[a,b]$ and $M$
    is any upper bound of $\big|f^{\prime\prime}(x)\big|$ on $[a,b]$,
    then $$\displaystyle E_T \leq \frac{(b-a)^3}{12n^2}M.$$

2.  Let $E_S$ be the error in approximating
    $\displaystyle\int_a^b f(x)\ dx$ using Simpson's Rule with $n$
    subintervals.

    If $f$ has a continuous 4$^\text{th}$ derivative on $[a,b]$ and $M$
    is any upper bound of $\big|f\,^{(4)}\big|$ on $[a,b]$, then
    $$E_S \leq \frac{(b-a)^5}{180n^4}M.$$

```

There are some key things to note about this theorem.

1.  The larger the interval, the larger the error. This should make
    sense intuitively.

2.  The error shrinks as more subintervals are used (i.e., as $n$ gets
    larger).

3.  The error in Simpson's Rule has a term relating to the
    4$^{\text{th}}$ derivative of $f$. Consider a cubic polynomial: it's
    $4^{\text{th}}$ derivative is 0. Therefore, the error in
    approximating the definite integral of a cubic polynomial with
    Simpson's Rule is 0 -- Simpson's Rule computes the exact answer!

We revisit Examples \@ref(exm:num3) and \@ref(exm:num5) and compute the
error bounds using Theorem \@ref(thm:numerical-error) in the following
example.\

```{example, label="num7", echo=TRUE}

(Computing error bounds). Find the error bounds when approximating
$\displaystyle\int_0^1 e^{-x^2}\ dx$ using the Trapezoidal Rule and 5
subintervals, and using Simpson's Rule with 4 subintervals.

------------------------------------------------------------------------

**Trapezoidal Rule with $n=5$:**


We start by computing the $2^\text{nd}$ derivative of $f(x) = e^{-x^2}$:
$$f^{\prime\prime}(x) = e^{-x^2}(4x^2-2).$$ Figure \@ref(fig:num7a)
shows a graph of $f^{\prime\prime}(x)$ on $[0,1]$. It is clear that the
largest value of $f^{\prime\prime}$, in absolute value, is 2. Thus we
let $M=2$ and apply the error formula from Theorem
\@ref(thm:numerical-error).

$$E_T = \frac{(1-0)^3}{12\cdot 5^2}\cdot 2 = 0.00\overline{6}.$$

Our error estimation formula states that our approximation of 0.7445
found in Example \@ref(exm:num3) is within 0.0067 of the correct answer,
hence we know that
$$0.7445-0.0067 = .7378 \leq \int_0^1e^{-x^2}\ dx \leq 0.7512 = 0.7445 + 0.0067.$$
We had earlier computed the exact answer, correct to 4 decimal places,
to be 0.7468, affirming the validity of Theorem
\@ref(thm:numerical-error).\
**Simpson's Rule with $n=4$:**

We start by computing the $4^\text{th}$ derivative of $f(x) = e^{-x^2}$:
$$f\,^{(4)}(x) = e^{-x^2}(16x^4-48x^2+12).$$ Figure \@ref(fig:num7b)
shows a graph of $f\,^{(4)}(x)$ on $[0,1]$. It is clear that the largest
value of $f\,^{(4)}$, in absolute value, is 12. Thus we let $M=12$ and
apply the error formula from Theorem \@ref(thm:numerical-error).

$$E_s = \frac{(1-0)^5}{180\cdot 4^4}\cdot 12 = 0.00026.$$

Our error estimation formula states that our approximation of
$0.7468\overline{3}$ found in Example \@ref(exm:num5) is within 0.00026
of the correct answer, hence we know that
$$0.74683-0.00026 = .74657 \leq \int_0^1e^{-x^2}\ dx \leq 0.74709 = 0.74683 + 0.00026.$$
Once again we affirm the validity of Theorem \@ref(thm:numerical-error).

```

```{geogebra, label="num7a"}

caption: >
    Graphing $f^{\prime\prime}(x)$ in Example \@ref(exm:num7) to help establish error bounds.

```

```{geogebra, label="num7b"}

caption: >
    Graphing $f\,^{(4)}(x)$ in Example \@ref(exm:num7) to help establish error bounds.

```


At the beginning of this section we mentioned two main situations where
numerical integration was desirable. We have considered the case where
an antiderivative of the integrand cannot be computed. We now
investigate the situation where the integrand is not known. This is, in
fact, the most widely used application of Numerical Integration methods.
"Most of the time" we observe behavior but do not know "the" function
that describes it. We instead collect data about the behavior and make
approximations based on this data. We demonstrate this in an example.\

```{example, label="num8", echo=TRUE}

(Approximating distance traveled). One of the authors drove his daughter
home from school while she recorded their speed every 30 seconds. The
data is given in Figure \@ref(fig:num8). Approximate the distance they
traveled.

------------------------------------------------------------------------

Recall that by integrating a speed function we get distance traveled. We
have information about $v(t)$; we will use Simpson's Rule to approximate
$\displaystyle\int_a^b v(t)\ dt.$

The most difficult aspect of this problem is converting the given data
into the form we need it to be in. The speed is measured in miles per
hour, whereas the time is measured in minutes.

::: {#fig:num8 .tab}
**Table 8**. caption: Speed data collected at 30 second intervals for
Example \@ref(exm:num8).
:::

We need to compute $\Delta x= (b-a)/n$. With 25 data points collected,
there are $n=24$ subintervals. What are $a$ and $b$? Since we start at
time $t=0$, we have $a=0$. The final recorded time was $t=12$ minutes,
which is 1/5 of an hour. Thus we have
$$\Delta x= \frac{b-a}{n} = \frac{1/5-0}{24} = \frac 1{120}; \quad \frac{\Delta x}{3} = \frac{1}{360}.$$

Thus the distance traveled is approximately: $$\begin{aligned}
\int_0^{0.2}v(t)\ dt &\approx \frac{1}{360}\Big[f(x_1)+4f(x_2) + 2f(x_3) + \cdots + 4f(x_n)+f(x_{n+1})\Big]\\
                    &= \frac{1}{360}\Big[0+4\cdot 25+2\cdot 22 + \cdots + 2\cdot 40+4\cdot 23 + 0\Big]\\
                    &\approx 6.2167 \ \text{miles.}\end{aligned}$$ We
approximate the author drove 6.2 miles. (Because we are sure the reader
wants to know, the author's odometer recorded the distance as about 6.05
miles.)

```


We started this chapter learning about antiderivatives and indefinite
integrals. We then seemed to change focus by looking at areas between
the graph of a function and the $x$-axis. We defined these areas as the
definite integral of the function, using a notation very similar to the
notation of the indefinite integral. The Fundamental Theorem of Calculus
tied these two seemingly separate concepts together: we can find areas
under a curve, i.e., we can evaluate a definite integral, using
antiderivatives.

We ended the chapter by noting that antiderivatives are sometimes more
than difficult to find: they are impossible. Therefore we developed
numerical techniques that gave us good approximations of definite
integrals.

We used the definite integral to compute areas, and also to compute
displacements and distances traveled. There is far more we can do than
that. In Chapter \@ref(chapter:app-of-int) we'll see more applications
of the definite integral. Before that, in Chapter
\@ref(chapter:anti-tech) we'll learn advanced techniques of integration,
analogous to learning rules like the Product, Quotient and Chain Rules
of differentiation.
