## Riemann Sums {#sec:riemann}

```{youtube zobel-planimeter}
id: RI9aq30OdU0
```

In the previous section we defined the definite integral of a function
on $[a,b]$ to be the signed area between the curve and the $x$--axis.
Some areas were simple to compute; we ended the section with a region
whose area was not simple to compute. In this section we develop a
technique to find such areas.

A fundamental calculus technique is to first answer a given problem with
an approximation, then refine that approximation to make it better, then
use limits in the refining process to find the exact answer. That is
what we will do here.

Consider the region given in Figure \@ref(fig:rie1a), which is the area
under $y=4x-x^2$ on $[0,4]$. What is the signed area of this region --
i.e., what is $\int_0^4(4x-x^2)\ dx$?

```{geogebra, label="rie1a"}

caption: >
    A graph of $f(x) = 4x-x^2$. What is the area of the shaded region?

```

We start by approximating. We can surround the region with a rectangle
with height and width of 4 and find the area is approximately 16 square
units. This is obviously an *over--approximation*; we are including area
in the rectangle that is not under the parabola.

We have an approximation of the area, using one rectangle. How can we
refine our approximation to make it better? The key to this section is
this answer: *use more rectangles.*

Let's use 4 rectangles with an equal width of 1. This *partitions* the
interval $[0,4]$ into 4 *subintervals*, $[0,1]$, $[1,2]$, $[2,3]$ and
$[3,4]$. On each subinterval we will draw a rectangle.

There are three common ways to determine the height of these rectangles:
the **Left Hand Rule**, the **Right Hand Rule**, and the **Midpoint
Rule**. The **Left Hand Rule** says to evaluate the function at the
left--hand endpoint of the subinterval and make the rectangle that
height. In Figure \@ref(fig:rie1b), moving the rectangle rule slider to 
the left end ($k=0$) shows the Left Hand Rule.

```{geogebra, label="rie1b"}
material_id: pf8g3huf
caption: >
    Approximating $\int_0^4(4x-x^2)\ dx$ using rectangles. The heights of the rectangles are determined using different rules.

```

The **Right Hand Rule** says the opposite: on each subinterval, evaluate
the function at the right endpoint and make the rectangle that height.
In the figure, moving the rectangle rule slider to the right end ($k=1$)
shows the result of using the Right Hand Rule.

The **Midpoint Rule** says that on each subinterval, evaluate the
function at the midpoint and make the rectangle that height. Setting the 
rectangle rule slider at the middle ($k=0.5$) shows the result of using
the Midpoint Rule.

These are the three most common rules for determining the heights of
approximating rectangles, but as the animation shows, one is not forced 
to use one of these three methods, one could choose any location within 
the subintervals to determine the height of the rectangle. One could even 
choose a different position for each subinterval if one desired.

The following example will approximate the value of
$\int_0^4 (4x-x^2)\ dx$ using these rules.\

```{example, label="rie2ex", echo=TRUE}

(Using the Left Hand, Right Hand and Midpoint Rules). Approximate the
value of $\int_0^4 (4x-x^2)\ dx$ using the Left Hand Rule, the Right
Hand Rule, and the Midpoint Rule, using 4 equally spaced subintervals.

------------------------------------------------------------------------

We break the interval $[0,4]$ into four subintervals as before. In
Figure \@ref(fig:rie2)(a) we see 4 rectangles drawn on $f(x) = 4x-x^2$
using the Left Hand Rule. (The areas of the rectangles are given in each
figure.)


Note how in the first subinterval, $[0,1]$, the rectangle has height
$f(0)=0$. We add up the areas of each rectangle (height$\times$ width)
for our Left Hand Rule approximation: $$\begin{aligned}
 f(0)\cdot 1 + f(1)\cdot 1+ f(2)\cdot 1+f(3)\cdot 1 &=\\
    0+3+4+3&= 10.
    \end{aligned}$$

Setting Figure \@ref(fig:rie2) so that it shows 4 rectangles drawn 
under $f$ using the Right Hand Rule, note how the $[3,4]$ subinterval 
has a rectangle of height 0.

In this example, these rectangle seem to be the mirror image of those
found in part (a) of the Figure. This is because of the symmetry of our
shaded region. Our approximation gives the same answer as before, though
calculated a different way: $$\begin{aligned}
 f(1)\cdot 1 + f(2)\cdot 1+ f(3)\cdot 1+f(4)\cdot 1 &=\\
    3+4+3+0&= 10.
    \end{aligned}$$

When Figure \@ref(fig:rie2) is set to show 4 rectangles drawn under 
$f$ using the Midpoint Rule, we see that we get an approximation 
for $\int_0^4(4x-x^2)\ dx$ of:
$$\begin{aligned}
 f(0.5)\cdot 1 + f(1.5)\cdot 1+ f(2.5)\cdot 1+f(3.5)\cdot 1 &=\\
    1.75+3.75+3.75+1.75&= 11.
    \end{aligned}$$ Our three methods provide two approximations of
$\int_0^4(4x-x^2)\ dx$: 10 and 11.

```

```{geogebra rie2}
material_id: k6qyd9aj
caption: >
    Approximating $\int_0^4(4x-x^2)\ dx$ in Example
    \@ref(exm:rie2ex). Moving the rectangle rule slider to the
    three different positions shows the areas of the rectangles for
    the Left, Right, and Midpoint rules.
```

### Summation Notation {-}

It is hard to tell at this moment which is a
better approximation: 10 or 11? We can continue to refine our
approximation by using more rectangles. The notation can become
unwieldy, though, as we add up longer and longer lists of numbers. We
introduce **summation notation** to ameliorate this problem.

Suppose we wish to add up a list of numbers $a_1$, $a_2$, $a_3$, ...,
$a_9$. Instead of writing $$a_1+a_2+a_3+a_4+a_5+a_6+a_7+a_8+a_9,$$ we
use summation notation and write

::: {.center}
```{tikz rie_notation,echo=FALSE, dev="png", dpi=72, cache=TRUE}
\begin{tikzpicture}[>=latex]
    \node[] (sum) {$\displaystyle \sum$};
    \node at (sum.north) (ub) {$\scriptstyle 9$};
    \node at (sum.south) (lb) {$\scriptstyle i=1$};
    \node at (sum.east) (summand) {$\, a_i$};
    \node[above left of=ub, anchor=east, color=blue] (top) {Upper bound};
    \node[left of=sum, anchor=east,color=blue] (front) {Summation symbol};
    \node[below left of=lb, anchor=north,color=blue] (bottom) {Summation index $i$ and lower bound};
    \node[right of=summand, anchor=west, color=blue] (behind) {Summand};
    \draw[->,color=blue] (top) edge [out=0, in=90] (ub);
    \draw[->,color=blue] (front) edge (sum);
    \draw[->,color=blue] (bottom) edge [out=90, in=-90] (lb);
    \draw[->,color=blue] (behind) edge (summand);
\end{tikzpicture}
```
:::

The upper case sigma ($\Sigma$) represents the verb "sum." The _index_ 
(or counter) of summation in this example is $i$; any symbol can be 
used. By convention, the index takes on every integer value
between (and including) the lower and upper bounds. The expression to the 
right of $\Sigma$ is called the _summand_. The summand tells us what terms
we are summing, in this case the values $a_i$, for every integer $i$ between
1 and 9.

Let's practice using this notation.

```{example, label="rie3", echo=TRUE}

(Using summation notation). Let the numbers $\{a_i\}$ be defined as
$a_i = 2i-1$ for integers $i$, where $i\geq 1$. So $a_1 = 1$, $a_2 = 3$,
$a_3 = 5$, etc. (The output is the positive odd integers). Evaluate the
following summations:
$$1. \sum_{i=1}^6 a_i \qquad\qquad\qquad 2. \sum_{i=3}^7 (3a_i-4)\qquad\qquad \qquad 3. \sum_{i=1}^4 (a_i)^2$$

------------------------------------------------------------------------

1.  $$\begin{aligned}
        \sum_{i=1}^6 a_i &= a_1+a_2+a_3+a_4+a_5+a_6\\
                &=  1+3+5+7+9+11 \\
                &=  36.
    \end{aligned}$$

2.  Note the starting value is different than 1: $$\begin{aligned}
        \sum_{i=3}^7 (3a_i-4) 
            &= (3a_3-4)+(3a_4-4)+(3a_5-4)+(3a_6-4)+(3a_7-4) \\
            &= 11+17+23+29+35 \\
            &= 115.
        \end{aligned}$$

3.  $$\begin{aligned}
            \sum_{i=1}^4 (a_i)^2 &= (a_1)^2+(a_2)^2+(a_3)^2+(a_4)^2\\
                                &=  1^2+3^2+5^2+7^2 \\
                                &=  84.
    \end{aligned}$$

```


It might seem odd to stress a new, concise way of writing summations
only to write each term out as we add them up. It is. The following
theorem gives some of the properties of summations that allow us to work
with them without writing individual terms. Examples will follow.
:::{style="columns: 2 330px;"}
```{theorem, label="summation", echo=TRUE}

(Properties of Summations).

1.  $\displaystyle\sum_{i=1}^n c = c\cdot n$, where $c$ is a constant.

2.  $\displaystyle\sum_{i=m}^n (a_i\pm b_i) = \sum_{i=m}^n a_i \pm \sum_{i=m}^n b_i$

3.  $\displaystyle\sum_{i=m}^n c\cdot a_i = c\cdot\sum_{i=m}^n a_i$

4.  $\displaystyle\sum_{i=m}^j a_i + \sum_{i=j+1}^n  a_i = \sum_{i=m}^n a_i$

1.  $\displaystyle\sum_{i=1}^n i = \frac{n(n+1)}2$

2.  $\displaystyle\sum_{i=1}^n i^2 = \frac{n(n+1)(2n+1)}6$

3.  $\displaystyle\sum_{i=1}^n i^3 = \left(\frac{n(n+1)}2\right)^2$

```
:::
```{example, label="rie4", echo=TRUE}

(Evaluating summations using Theorem ). Revisit Example \@ref(exm:rie3)
and, using Theorem \@ref(thm:summation), evaluate
$$\sum-{i=1}^6 a-i = \sum-{i=1}^6 (2i-1).$$

------------------------------------------------------------------------

$$\begin{aligned}
        \sum_{i=1}^6 (2i-1) & = \sum_{i=1}^6 2i - \sum_{i=1}^6 (1)\\
                                                &=  \left(2\sum_{i=1}^6 i \right)- 6 \\
                                                &= 2\frac{6(6+1)}{2} - 6 \\
                                                &= 42-6 = 36
 \end{aligned}$$ We obtained the same answer without writing out all six
terms. When dealing with small sizes of $n$, it may be faster to write
the terms out by hand. However, Theorem \@ref(thm:summation) is
incredibly important when dealing with large sums as we'll soon see.

```


### Riemann Sums{-}

Consider again $\int_0^4(4x-x^2)\ dx$. We will approximate this definite
integral using 16 equally spaced subintervals and the Right Hand Rule in
Example \@ref(exm:rie7ex). Before doing so, it will pay to do some careful
preparation.

::: {.center}
```{tikz rie5, echo=FALSE, cache=TRUE, dpi=72, fig.cap="Dividing $[0,4]$ into 16 equally spaced subintervals."}
        \begin{tikzpicture}

        \draw [<->] (-.5,0) -- (4.5,0);

        \foreach \x in {0,.25,...,4} {
            \draw (\x,-.1) -- (\x,.1);
          }
        \draw (0,-.25) node { $0$};
        \draw (1,-.25) node { $1$};
        \draw (2,-.25) node { $2$};
        \draw (3,-.25) node { $3$};
        \draw (4,-.25) node { $4$};

        \draw (0,-.55) node { $x_1$};
        \draw (1,-.55) node { $x_5$};
        \draw (2,-.55) node { $x_9$};
        \draw (3,-.55) node { $x_{13}$};
        \draw (4,-.55) node { $x_{17}$};

        \end{tikzpicture}
```
:::

Figure \@ref(fig:rie5) shows a number line of $[0,4]$ divided, or
*partitioned*, into 16 equally spaced subintervals. We denote $0$ as
$x-1$; we have marked the values of $x-5$, $x-9$, $x-{13}$ and $x-{17}$.
We could mark them all, but the figure would get crowded. While it is
easy to figure that $x-{10} = 2.25$, in general, we want a method of
determining the value of $x_i$ without consulting the figure. Consider:

::: {.center}
```{tikz rie5a, echo=FALSE, cache=TRUE, dpi=72}
      \begin{tikzpicture}
      \draw (1.5,1) node {$\displaystyle x_i = x_1 + (i-1)\Delta x$};

      \draw [blue] (1,0) node [text width=32pt,align=center] (a) { \centering starting\\[-5pt] value};
      \draw [blue,->] (a) -- (.95,.75);

      \draw [blue] (2,2.5) node [text width=60pt,align=center] (b) { \centering number of subintervals\\[-5pt] between $x_1$ and $x_i$};
      \draw [blue,->] (b) -- (1.95,1.25);

      \draw [blue] (3,0) node [text width=60pt,align=center] (c) { \centering subinterval\\[-5pt] size};
      \draw [blue,->] (c) -- (2.75,.75);

      \end{tikzpicture}
```
:::

So $x_{10} = x_1 + 9(4/16) = 2.25.$

If we had partitioned $[0,4]$ into 100 equally spaced subintervals, each
subinterval would have length $\Delta x=4/100 = 0.04$. We could compute
$x_{32}$ as $$x_{32} = x_1 + 31(4/100) = 1.24.$$ (That was far faster
than creating a sketch first.)

Given any subdivision of $[0,4]$, the first subinterval is $[x_1,x_2]$;
the second is $[x_2,x_3]$; the $i^\text{ th}$ subinterval is
$[x_i,x_{i+1}]$.

- When using the Left Hand Rule, the height of the $i^\text{ th}$
rectangle will be $f(x_i)$.

- When using the Right Hand Rule, the height of the $i^\text{ th}$
rectangle will be $f(x_{i+1})$.

- When using the Midpoint Rule, the height of the $i^\text{ th}$ rectangle
will be $\displaystyle f\left(\frac{x_i+x_{i+1}}2\right)$.

Thus approximating $\int_0^4(4x-x^2)\ dx$ with 16 equally spaced
subintervals can be expressed as follows, where $\Delta x = 4/16 = 1/4$:

- **Left Hand Rule:** $\displaystyle\sum_{i=1}^{16} f(x_i)\Delta x$

- **Right Hand Rule:** $\displaystyle\sum_{i=1}^{16} f(x_{i+1})\Delta x$

- **Midpoint Rule:** $\displaystyle\sum_{i=1}^{16} f\left(\frac{x_i+x_{i+1}}2\right)\Delta x$

We use these formulas in the next two examples.

The following example lets us practice using the Right Hand Rule and the
summation formulas introduced in Theorem \@ref(thm:summation).\

```{example, label="rie7ex", echo=TRUE}

(Approximating definite integrals using sums). Approximate
$\int_0^4(4x-x^2)\ dx$ using the Right Hand Rule and summation formulas
with 16 and 1000 equally spaced intervals.

------------------------------------------------------------------------

Using the formula derived before, using 16 equally spaced intervals and
the Right Hand Rule, we can approximate the definite integral as
$$\sum_{i=1}^{16}f(x_{i+1})\Delta x.$$ We have $\Delta x = 4/16 = 0.25$.
Since $x_i = 0+(i-1)\Delta x$, we have $$\begin{aligned}
x_{i+1} &= 0 + \big((i+1)-1\big)\Delta x \\
                &=  i\Delta x\end{aligned}$$

Using the summation formulas, consider: $$\begin{aligned}
\int_0^4 (4x-x^2)\ dx &\approx \sum_{i=1}^{16} f(x_{i+1})\Delta x \notag\\
                                            &= \sum_{i=1}^{16} f(i\Delta x) \Delta x\notag\\
                                    &= \sum_{i=1}^{16} \big(4i\Delta x - (i\Delta x)^2\big)\Delta x\notag\\
                                    &= \sum_{i=1}^{16} (4i\Delta x^2 - i^2\Delta x^3)\notag\\       
                                    &= (4\Delta x^2)\sum_{i=1}^{16} i - \Delta x^3 \sum_{i=1}^{16} i^2 \label{eq:rie7}\\
                                    &= (4\Delta x^2)\frac{16\cdot 17}{2} - \Delta x^3 \frac{16(17)(33)}6 \\
\text{(use $\Delta x = 0.25$)}
                                    &=10.625\notag\end{aligned}$$ We
were able to sum up the areas of 16 rectangles with very little
computation. In Figure \@ref(fig:rie7) the function and the 16
rectangles are graphed. While some rectangles over--approximate the
area, other under--approximate the area (by about the same amount). Thus
our approximate area of 10.625 is likely a fairly good approximation.

Notice that in the preceeding calculations, by changing the 16's to 1,000's (and
appropriately changing the value of $\Delta x$), we can use the same sequence of 
steps to sum up 1000 (or more) rectangles!

We do so here, starting from the third line from the bottom to save space. Note that
$\Delta x = 4/1000 = 0.004$. $$\begin{aligned}
\int_0^4 (4x-x^2)\ dx &\approx \sum_{i=1}^{1000} f(x_{i+1})\Delta x \notag\\
                                    &= (4\Delta x^2)\sum_{i=1}^{1000} i - \Delta x^3 \sum_{i=1}^{1000} i^2 \notag\\
                                    &= (4\Delta x^2)\frac{1000\cdot 1001}{2} - \Delta x^3 \frac{1000(1001)(2001)}6 \notag\\
                                    &=10.666656\notag\end{aligned}$$

Using many, many rectangles, we have a likely good approximation of

$\int_0^4 (4x-x^2)\Delta x$. That is,
$$\int_0^4(4x-x^2)\ dx \approx 10.666656.$$

```

```{geogebra, label="rie7"}
material_id: bew8nr8q
caption: >
    Approximating $\int_0^4(4x-x^2)\ dx$ with the Right Hand Rule
    and 16 evenly spaced subintervals. Press the play button to 
    see an animation of the calculation as the number of rectangles
    increases from 1 to 20.

```


Before the above example, we stated what the summations for the Left
Hand, Right Hand and Midpoint Rules looked like. Each had the same basic
structure, which was:

1.  each rectangle has the same width, which we referred to as
    $\Delta x$, and

2.  each rectangle's height is determined by evaluating $f$ at a
    particular point in each subinterval. For instance, the Left Hand
    Rule states that each rectangle's height is determined by evaluating
    $f$ at the left hand endpoint of the subinterval the rectangle lives
    on.

One could partition an interval $[a,b]$ with subintervals that do not
have the same size. We refer to the length of the $i^\text{ th}$
subinterval as $\Delta x_i$. Also, one could determine each rectangle's
height by evaluating $f$ at *any* point $c_i$ in the $i^\text{ th}$
subinterval. Thus the height of the $i^\text{ th}$ subinterval would be
$f(c_i)$, and the area of the $i^\text{ th}$ rectangle would be
$f(c_i)\Delta x_i$. These ideas are formally defined below.

```{definition, label="partition", echo=TRUE}

(Partition). A **partition** $\Delta x$ of a closed interval $[a,b]$ is
a set of numbers $x_1$, $x_2$, $\ldots$ $x_{n+1}$ where
$$a=x_1 < x_2 < \ldots < x_n < x_{n+1}=b.$$ The length of the
$i^\text{ th}$ subinterval, $[x_i,x_{i+1}]$, is
$\Delta x_i = x_{i+1}-x_i$. If $[a,b]$ is partitioned into subintervals
of equal length, we let $\Delta x$ represent the length of each
subinterval.\
The **size of the partition**, denoted $||\Delta x||$, is the length of
the largest subinterval of the partition.

```

Summations of rectangles with area $f(c_i)\Delta x_i$ are named after
mathematician Georg Friedrich Bernhard Riemann, as given in the
following definition.

```{definition, label="rie-sum", echo=TRUE}

(Riemann Sum). Let $f$ be defined on a closed interval $[a,b]$, let
$\Delta x$ be a partition of $[a,b]$

and let $c_i$ denote any value in the $i^\text{ th}$ subinterval.

The sum $$\sum_{i=1}^n f(c_i)\Delta x_i$$ is a **Riemann sum** of $f$ on
$[a,b]$.

```

Figure \@ref(fig:riedef) shows the approximating rectangles of a Riemann
sum of $\int_0^4(4x-x^2)\ dx$. While the rectangles in this example do
not approximate well the shaded area, they demonstrate that the
subinterval widths may vary and the heights of the rectangles can be
determined without following a particular rule.

```{tikz, label="riedef", cache=TRUE, echo=FALSE,fig.cap="An example of a general Riemann sum to approximate $\\int_0^4(4x-x^2)dx$."}
        \begin{tikzpicture}

        \begin{axis}[
        axis x line = middle,
        axis y line = middle,              
        axis on top,
        xtick={1,2,3,4},
        ytick={1,2,3,4},
        ymin=-1,ymax=5,
        xmin=-.5,xmax=4.5
        ]

        \addplot [color=blue,mark=none,thick,{Kite}-{Kite},solid,fill=blue!50,fill=none,fill,opacity=0.5,draw=none,domain=0:4] {4*x-x^2};
        \addplot [color=blue,mark=none,thick,{Kite}-{Kite},solid,fill=blue!50,fill=none,-,domain=0:4,samples=40] {4*x-x^2};

        \draw [thick,red] (axis cs:0,0) rectangle (axis cs:2,.9375);
        \draw [thick,red] (axis cs:2,0) rectangle (axis cs:3.5,2.79);
        \draw [thick,red] (axis cs:3.5,0) rectangle (axis cs:4,.76);
        \draw [fill=black] (axis cs:.25,.9375) circle (1pt);
        \draw [fill=black] (axis cs:3.1,2.79) circle (1pt);
        \draw [fill=black] (axis cs:3.8,.76) circle (1pt);

        \end{axis}

        \end{tikzpicture}

```

"Usually" Riemann sums are calculated using one of the three methods we
have introduced. The uniformity of construction makes computations
easier. Before working another example, let's summarize some of what we
have learned in a convenient way.

```{definition riemann, echo=TRUE}
(**Riemann Sum Concepts**). Consider $\displaystyle\int_a^b f(x) \ dx \approx \sum_{i=1}^n f(c_i)\Delta x_i.$

1.  When the $n$ subintervals have equal length,
    $\displaystyle\Delta x_i = \Delta x = \frac{b-a}n.$

2.  The $i^\text{ th}$ term of an equally spaced partition is
    $x_i = a + (i-1)\Delta x$. (Thus $x_1=a$ and $x_{n+1} = b$.)

3.  The Left Hand Rule summation is:
    $\displaystyle\sum_{i=1}^n f(x_i)\Delta x$.

4.  The Right Hand Rule summation is:
    $\displaystyle\sum_{i=1}^n f(x_{i+1})\Delta x$.

5.  The Midpoint Rule summation is:
    $\displaystyle\sum_{i=1}^n f\left(\frac{x_i+x_{i+1}}{2}\right)\Delta x$.

```

Let's do another example.

```{example, label="rie8ex", echo=TRUE}

(Approximating definite integrals with sums). Approximate
$\int_{-2}^3 (5x+2)\ dx$ using the Midpoint Rule and 10 equally spaced
intervals.

------------------------------------------------------------------------

Following Key Idea \@ref(def:riemann), we have
$$\Delta x = \frac{3 - (-2)}{10} = 1/2 \quad \text{and} \quad x_i = (-2) + (1/2)(i-1) = i/2-5/2.$$
As we are using the Midpoint Rule, we will also need $x_{i+1}$ and
$\displaystyle\frac{x_i+x_{i+1}}2$. Since
$x_i = i/2-5/2$,$x_{i+1} = (i+1)/2 - 5/2 = i/2 -2$. This gives
$$\frac{x_i+x_{i+1}}2 = \frac{(i/2-5/2) + (i/2-2)}{2} = \frac{i-9/2}{2} = i/2 - 9/4.$$
We now construct the Riemann sum and compute its value using summation
formulas. $$\begin{aligned}
\int_{-2}^3 (5x+2)\ dx  &\approx \sum_{i=1}^{10} f\left(\frac{x_i+x_{i+1}}{2}\right)\Delta x \\
                                                &=  \sum_{i=1}^{10} f(i/2 - 9/4)\Delta x \\
                                                &=  \sum_{i=1}^{10} \big(5(i/2-9/4) + 2\big)\Delta x\\
                                                &=  \Delta x\sum_{i=1}^{10}\left[\left(\frac{5}{2}\right)i - \frac{37}{4}\right]\\
                                                &=  \Delta x\left(\frac{5}2\sum_{i=1}^{10} (i) - \sum_{i=1}^{10}\left(\frac{37}{4}\right)\right) \\
                                                &= \frac 12\left(\frac 52\cdot\frac{10(11)}{2} - 10\cdot\frac{37}4\right)  \\
                                                &= \frac{45}2 = 22.5\end{aligned}$$


Note the graph of $f(x) = 5x+2$ in Figure \@ref(fig:rie8). The regions
whose area is computed by the definite integral are triangles, meaning
we can find the exact answer without summation techniques. We find that
the exact answer is indeed 22.5. One of the strengths of the Midpoint
Rule is that often each rectangle includes area that should not be
counted, but misses other area that should. When the partition size is
small, these two amounts are about equal and these errors almost "cancel
each other out." In this example, since our function is a line, these
errors are exactly equal and they do cancel each other out, giving us
the exact answer.

Note too that when the function is negative, the rectangles have a
"negative" height. When we compute the area of the rectangle, we use
$f(c_i)\Delta x$; when $f$ is negative, the area is counted as negative.

```

```{geogebra, label="rie8"}
material_id: xftwenqf
caption: >
    Approximating $\int_{-2}^3 (5x+2)\ dx$ using the Midpoint Rule and 10 evenly spaced subintervals in Example \@ref(exm:rie8ex).

```
\
Notice in the previous example that while we used 10 equally spaced
intervals, the number "10" didn't play a big role in the calculations
until the very end. Mathematicians love to abstract ideas; let's
approximate the area of another region using $n$ subintervals, where we
do not specify a value of $n$ until the very end.\

```{example, label="rie9ex", echo=TRUE}

(Approximating definite integrals with a formula, using sums). Revisit
$\int_0^4(4x-x^2)\ dx$ yet again. Approximate this definite integral
using the Right Hand Rule with $n$ equally spaced subintervals.

------------------------------------------------------------------------

Using Key Idea \@ref(def:riemann), we know
$\Delta x = \frac{4-0}{n} = 4/n$. We also find
$x_i = 0 + \Delta x(i-1) = 4(i-1)/n$. The Right Hand Rule uses
$x_{i+1}$, which is $x_{i+1} = 4i/n$.

We construct the Right Hand Rule Riemann sum as follows. Be sure to
follow each step carefully. If you get stuck, and do not understand how
one line proceeds to the next, you may skip to the result and consider
how this result is used. You should come back, though, and work through
each step for full understanding. $$\begin{aligned}
\int_0^4(4x-x^2)\ dx &\approx \sum_{i=1}^n f(x_{i+1})\Delta x \\
        &= \sum_{i=1}^n f\left(\frac{4i}{n}\right) \Delta x \\
        &=  \sum_{i=1}^n \left[4\frac{4i}n-\left(\frac{4i}n\right)^2\right]\Delta x\\
        &=  \sum_{i=1}^n \left(\frac{16\Delta x}{n}\right)i - \sum_{i=1}^n \left(\frac{16\Delta x}{n^2}\right)i^2 \\
        &=  \left(\frac{16\Delta x}{n}\right)\sum_{i=1}^n i - \left(\frac{16\Delta x}{n^2}\right)\sum_{i=1}^n i^2  \\
        &= \left(\frac{16\Delta x}{n}\right)\cdot \frac{n(n+1)}{2} - \left(\frac{16\Delta x}{n^2}\right)\frac{n(n+1)(2n+1)}{6} \\
\text{(substitute $\Delta x = 4/n$)}
        &=\frac{32(n+1)}{n} - \frac{32(n+1)(2n+1)}{3n^2} \\
\text{(now simplify)}
        &= \frac{32}{3}\left(1-\frac{1}{n^2}\right)\end{aligned}$$

The result is an amazing, easy to use formula. To approximate the
definite integral with 10 equally spaced subintervals and the Right Hand
Rule, set $n=10$ and compute
$$\int_0^4 (4x-x^2)\ dx \approx \frac{32}{3}\left(1-\frac{1}{10^2}\right) = 10.56.$$
Recall how earlier we approximated the definite integral with 4
subintervals; with $n=4$, the formula gives 10, our answer as before.

It is now easy to approximate the integral with 1,000,000 subintervals!
Hand-held calculators will round off the answer a bit prematurely giving
an answer of $10.66666667$. (The actual answer is $10.666666666656$.)

We now take an important leap. Up to this point, our mathematics has
been limited to geometry and algebra (finding areas and manipulating
expressions). Now we apply *calculus*. For any *finite* $n$, we know
that
$$\int_0^4 (4x-x^2)\ dx \approx \frac{32}{3}\left(1-\frac{1}{n^2}\right).$$
Both common sense and high--level mathematics tell us that as $n$ gets
large, the approximation gets better. In fact, if we take the *limit* as
$n\rightarrow \infty$, we get the *exact area* described by
$\int_0^4 (4x-x^2)\ dx$. That is, $$\begin{aligned}
\int_0^4 (4x-x^2)\ dx &= \lim_{n\rightarrow \infty} \frac{32}{3}\left(1-\frac{1}{n^2}\right) \\
                                    &= \frac{32}{3}\left(1-0\right)\\
                                    &= \frac{32}{3} = 10.\overline{6}\end{aligned}$$
This is a fantastic result. By considering $n$ equally--spaced
subintervals, we obtained a formula for an approximation of the definite
integral that involved our variable $n$. As $n$ grows large -- without
bound -- the error shrinks to zero and we obtain the exact area.

```


This section started with a fundamental calculus technique: make an
approximation, refine the approximation to make it better, then use
limits in the refining process to get an exact answer. That is precisely
what we just did.

Let's practice this again.

```{example, label="rie10ex", echo=TRUE}

(Approximating definite integrals with a formula, using sums). Find a
formula that approximates $\int_{-1}^5 x^3\ dx$ using the Right Hand
Rule and $n$ equally spaced subintervals, then take the limit as
$n\to\infty$ to find the exact area.

------------------------------------------------------------------------

Following Key Idea \@ref(def:riemann), we have
$\Delta x = \frac{5-(-1)}{n} = 6/n$. We have
$x_i = (-1) + (i-1)\Delta x$; as the Right Hand Rule uses $x_{i+1}$, we
have $x_{i+1} = (-1) + i\Delta x$.

The Riemann sum corresponding to the Right Hand Rule is (followed by
simplifications): $$\begin{aligned}
\int_{-1}^5 x^3\ dx     &\approx \sum_{i=1}^n f(x_{i+1})\Delta x \\
                                            &= \sum_{i=1}^n f(-1+i\Delta x)\Delta x \\
                                            &= \sum_{i=1}^n (-1+i\Delta x)^3\Delta x \\
                                            &= \sum_{i=1}^n \big((i\Delta x)^3 -3(i\Delta x)^2 + 3i\Delta x -1\big)\Delta x \\ 
\text{(now distribute $\Delta x$)}
                                            &= \sum_{i=1}^n \big(i^3\Delta x^4 - 3i^2\Delta x^3 + 3i\Delta x^2 -\Delta x\big) \\ \text{(now split up summation)}
                                            &= \Delta x^4 \sum_{i=1}^ni^3 -3\Delta x^3 \sum_{i=1}^n i^2+ 3\Delta x^2 \sum_{i=1}^n i - \sum_{i=1}^n \Delta x \\
                                            &= \Delta x^4 \left(\frac{n(n+1)}{2}\right)^2 -3\Delta x^3 \frac{n(n+1)(2n+1)}{6}+ 3\Delta x^2 \frac{n(n+1)}{2} - n\Delta x \\
                                            \text{(use $\Delta x = 6/n$)}
                                            &= \frac{1296}{n^4}\cdot\frac{n^2(n+1)^2}{4} - 3\frac{216}{n^3}\cdot\frac{n(n+1)(2n+1)}{6} + 3\frac{36}{n^2}\frac{n(n+1)}2 -6 \\
                                            \text{(algebraic simplification)}
                                            &=156 + \frac{378}n + \frac{216}{n^2}\end{aligned}$$
    
Once again, we have found a compact formula for approximating the
definite integral with $n$ equally spaced subintervals and the Right
Hand Rule. Using 10 subintervals, we have an approximation of $195.96$
(these rectangles are shown in Figure \@ref(fig:rie10)). Using $n=100$
gives an approximation of $159.802$.

Now find the exact answer using a limit:
$$\int_{-1}^5 x^3\ dx = \lim_{n\to\infty} \left(156 + \frac{378}n + \frac{216}{n^2}\right) = 156.$$

```

```{geogebra, label="rie10"}
material_id: ce44gumn
caption: >
    Approximating $\int_{-1}^5 x^3\ dx$ using the Right Hand Rule and 10 evenly spaced subintervals.

```

### Limits of Riemann Sums {-}

We have used limits to evaluate given definite integrals. Will this
always work? We will show, given not--very--restrictive conditions, that
yes, it will always work.

The previous two examples demonstrated how an expression such as
$$\sum_{i=1}^n f(x_{i+1})\Delta x$$ can be rewritten as an expression
explicitly involving $n$, such as $32/3(1-1/n^2)$.

Viewed in this manner, we can think of the summation as a function of
$n$. An $n$ value is given (where $n$ is a positive integer), and the
sum of areas of $n$ equally spaced rectangles is returned, using the
Left Hand, Right Hand, or Midpoint Rules.

Given a definite integral $\int_a^b f(x)\ dx$, let:

-   $\displaystyle S_L(n) = \sum_{i=1}^n f(x_i)\Delta x$, the sum of
    equally spaced rectangles formed using the Left Hand Rule,

-   $\displaystyle S_R(n) = \sum_{i=1}^n f(x_{i+1})\Delta x$, the sum of
    equally spaced rectangles formed using the Right Hand Rule, and

-   $\displaystyle S_M(n) = \sum_{i=1}^n f\left(\frac{x_i+x_{i+1}}{2}\right)\Delta x$,
    the sum of equally spaced rectangles formed using the Midpoint Rule.

Recall the definition of a limit as $n\to\infty$:
$\displaystyle\lim_{n\to\infty}S_L(n) = K$ if, given any $\epsilon>0$,
there exists $N>0$ such that
$$\left|S_L(n)-K\right| < \epsilon \quad \text{when}\quad n\geq N.$$

The following theorem states that we can use any of our three rules to
find the exact value of a definite integral $\int_a^b f(x)\ dx$. It also
goes two steps further. The theorem states that the height of each
rectangle doesn't have to be determined following a specific rule, but
could be $f(c_i)$, where $c_i$ is any point in the $i^\text{ th}$
subinterval, as discussed before Riemann Sums were defined in Definition
\@ref(def:rie-sum).

The theorem goes on to state that the rectangles do not need to be of
the same width. Using the notation of Definition \@ref(def:partition),
let $\Delta x_i$ denote the length of the $i^\text{ th}$ subinterval in
a partition of $[a,b]$ and let $||\Delta x||$ represent the length of
the largest subinterval in the partition: that is, $||\Delta x||$ is the
largest of all the $\Delta x_i$'s. If $||\Delta x||$ is small, then
$[a,b]$ must be partitioned into many subintervals, since all
subintervals must have small lengths. "Taking the limit as
$||\Delta x||$ goes to zero" implies that the number $n$ of subintervals
in the partition is growing to infinity, as the largest subinterval
length is becoming arbitrarily small. We then interpret the expression
$$\lim_{||\Delta x||\to 0}\sum_{i=1}^nf(c_i)\Delta x_i$$ as "the limit
of the sum of the areas of rectangles, where the width of each rectangle
can be different but getting small, and the height of each rectangle is
not necessarily determined by a particular rule." The theorem states
that this Riemann Sum also gives the value of the definite integral of
$f$ over $[a,b]$.

```{theorem, label="riemann-sum", echo=TRUE}

(Definite Integrals and the Limit of Riemann Sums). Let $f$ be
continuous on the closed interval $[a,b]$ and let $S_L(n)$, $S_R(n)$,
$S_M(n)$, $\Delta x$, $\Delta x_i$ and $c_i$ be defined as before. Then:

1.  $\displaystyle\lim_{n\to\infty} S_L(n) = \lim_{n\to\infty} S_R(n) = \lim_{n\to\infty} S_M(n) = \lim_{n\to\infty}\sum_{i=1}^n f(c_i)\Delta x$,

2.  $\displaystyle\lim_{n\to\infty}\sum_{i=1}^n f(c_i)\Delta x = \int_a^b f(x)\ dx$,
    and

3.  $\displaystyle\lim_{\|\Delta x\|\to 0} \sum_{i=1}^n f(c_i)\Delta x_i = \int_a^b f(x)\ dx$.

```

We summarize what we have learned over the past few sections here.

-   Knowing the "area under the curve" can be useful. One common
    example: the area under a velocity curve is displacement.

-   We have defined the definite integral, $\int_a^b f(x)\ dx$, to be
    the signed area under $f$ on the interval $[a,b]$.

-   While we can approximate a definite integral many ways, we have
    focused on using rectangles whose heights can be determined using
    the Left Hand Rule, the Right Hand Rule and the Midpoint Rule.

-   Sums of rectangles of this type are called Riemann sums.

-   The exact value of the definite integral can be computed using the
    limit of a Riemann sum. We generally use one of the above methods as
    it makes the algebra simpler.

We first learned of derivatives through limits then learned rules that
made the process simpler. We know of a way to evaluate a definite
integral using limits; in the next section we will see how the
Fundamental Theorem of Calculus makes the process simpler. The key
feature of this theorem is its connection between the indefinite
integral and the definite integral.
