# Reference Material {-}

$$
\newcommand{\ds}{\displaystyle}
\newcommand{\deriv}[2]{\ds\frac{d}{dx}\left(#1\right)=#2}
\newcommand{\myint}[2]{\ds\int #1\ dx = #2}
\DeclareMathOperator{\sech}{sech}
\DeclareMathOperator{\csch}{csch}
$$

### Differentiation Rules {-}

1.  $\deriv{cx}{c}$
1.  $\deriv{u\pm v}{u'\pm v'}$
1.  $\deriv{u\cdot v}{uv'+ u'v}$
1.  $\deriv{\frac uv}{\frac{vu'-uv'}{v^2}}$
1.  $\deriv{u(v)}{u'(v)v'}$
1.  $\deriv{c}{0}$
1.  $\deriv{x}{1}$
1.  $\deriv{x^n}{nx^{n-1}}$
1.  $\deriv{e^x}{e^x}$
1.  $\deriv{a^x}{\ln a\cdot a^x}$
1.  $\deriv{\ln x}{\frac{1}{x}}$
1.  $\deriv{\log_a x}{\frac{1}{\ln a}\cdot \frac1x}$
1.  $\deriv{\sin x}{\cos x}$
1.  $\deriv{\cos x}{-\sin x}$
1.  $\deriv{\csc x}{-\csc x\cot x}$
1.  $\deriv{\sec x}{\sec x\tan x}$
1.  $\deriv{\tan x}{\sec^2 x}$
1.  $\deriv{\cot x}{-\csc^2 x}$
1.  $\deriv{\sin^{-1}x}{\frac{1}{\sqrt{1-x^2}}}$
1.  $\deriv{\cos^{-1}x}{\frac{-1}{\sqrt{1-x^2}}}$
1.  $\deriv{\csc^{-1}x}{\frac{-1}{|x|\sqrt{x^2-1}}}$
1.  $\deriv{\sec^{-1}x}{\frac{1}{|x|\sqrt{x^2-1}}}$
1.  $\deriv{\tan^{-1}x}{\frac{1}{1+x^2}}$
1.  $\deriv{\cot^{-1}x}{\frac{-1}{1+x^2}}$
1.  $\deriv{\cosh x}{\sinh x}$
1.  $\deriv{\sinh x}{\cosh x}$
1.  $\deriv{\tanh x}{\sech^2 x}$
1.  $\deriv{\sech x}{-\sech x\tanh x}$
1.  $\deriv{\csch x}{-\csch x\coth x}$
1.  $\deriv{\coth x}{-\csch^2 x}$
1.  $\deriv{\cosh^{-1}x}{\frac1{\sqrt{x^2-1}}}$
1.  $\deriv{\sinh^{-1}x}{\frac1{\sqrt{x^2+1}}}$
1.  $\deriv{\sech^{-1}x}{\frac{-1}{x\sqrt{1-x^2}}}$
1.  $\deriv{\csch^{-1}x}{\frac{-1}{|x|\sqrt{1+x^2}}}$
1.  $\deriv{\tanh^{-1}x}{\frac1{1-x^2}}$
1.  $\deriv{\coth^{-1}x}{\frac1{1-x^2}}$

### Integration Rules  {-}

1.  $\myint{c\cdot f(x)}{c\int f(x)\ dx}$
1.  $\myint{f(x)\pm g(x)}{}\\$
\vskip2pt$\ds  \int f(x)\ dx \pm \int g(x)\ dx$
1.  $\myint{0}{C}$
1.  $\myint{1}{x+C}$
1.  $\myint{x^n}{\frac{1}{n+1}x^{n+1}+C, \ n\neq -1}$
1.  $\myint{e^x}{e^x+C}$
1.  $\myint{\ln x}{x\ln x -x +C}$
1.  $\myint{a^x}{\frac{1}{\ln a}\cdot a^x+C}$
1.  $\myint{\frac{1}{x}}{\ln |x| + C}$
1.  $\myint{\cos x}{\sin x+C}$
1.  $\myint{\sin x}{-\cos x+C}$
1.  $\myint{\tan x}{-\ln |\cos x|+C}$
1.  $\myint{\sec x}{\ln |\sec x+\tan x|+C}$
1.  $\myint{\csc x}{-\ln |\csc x+\cot x|+C}$
1.  $\myint{\cot x}{\ln |\sin x|+C}$
1.  $\myint{\sec^2 x}{\tan x+C}$
1.  $\myint{\csc^2x}{-\cot x+C}$
1.  $\myint{\sec x\tan x}{\sec x+C}$
1.  $\myint{\csc x\cot x}{-\csc x+C}$
1.  $\myint{\cos^2x}{\frac12x+\frac14\sin\big(2x\big)+C}$
1.  $\myint{\sin^2x}{\frac12x-\frac14\sin\big(2x\big)+C}$
1.  $\myint{\frac{1}{x^2+a^2}}{\frac1a\tan^{-1}\left(\frac xa\right)+C}$
1.  $\myint{\frac{1}{\sqrt{a^2-x^2}}}{\sin^{-1}\left(\frac xa\right)+C}$
1.  $\myint{\frac{1}{x\sqrt{x^2-a^2}}}{\frac1a\sec^{-1}\left(\frac{|x|}{a}\right)+C}$
1.  $\myint{\cosh x}{\sinh x+C}$
1.  $\myint{\sinh x}{\cosh x+C}$
1.  $\myint{\tanh x}{\ln(\cosh x)+C}$
1.  $\myint{\coth x}{\ln |\sinh  x|+C}$
1.  $\myint{\frac{1}{\sqrt{x^2-a^2}}}{\ln\big|x+\sqrt{x^2-a^2}\big|+C}$
1.  $\myint{\frac{1}{\sqrt{x^2+a^2}}}{\ln\big|x+\sqrt{x^2+a^2}\big|+C}$
1.  $\myint{\frac{1}{a^2-x^2}}{\frac1{2a}\ln\left|\frac{a+x}{a-x}\right|+C}$
1.  $\myint{\frac{1}{x\sqrt{a^2-x^2}}}{\frac1a\ln\left(\frac{x}{a+\sqrt{a^2-x^2}}\right)+C}$
1.  $\myint{\frac{1}{x\sqrt{x^2+a^2}}}{\frac1a\ln\left|\frac{x}{a+\sqrt{x^2+a^2}}\right|+C}$

### The Unit Circle {-}

```{tikz unitcircle, dev="png", echo=FALSE, cache=TRUE, fig.width=NULL}
\begin{tikzpicture}[scale=3]
\draw [<->,>=latex] (-1.5,0) -- (1.4,0) node [right] {\scriptsize $x$};
\draw [<->,>=latex] (0,-1.3) -- (0,1.3) node [above] {\scriptsize $y$};
\foreach \x / \y / \z / \w / \v in {
        0/0/{1,0}/right/white,
        30/{\pi/6}/{\frac{\sqrt{3}}2,\frac 12}/above right/none,%
        45/{\pi/4}/{\frac{\sqrt{2}}2,\frac{\sqrt{2}}2}/above right/none,
        60/{\pi/3}/{\frac{1}2,\frac{\sqrt{3}}2}/{above right}/none,
        90/ {\pi/2}/{0,1}/above/white,%
        120/{2\pi/3}/{-\frac{1}2,\frac{\sqrt{3}}2}/above left/none, 
        135/{3\pi/4}/{-\frac{\sqrt{2}}2,\frac{\sqrt{2}}2}/above left/none, 
        150/ {5\pi/6}/{-\frac{\sqrt{3}}2,\frac{1}2}/above left/none,%
        180/ {\pi}/{-1,0}/left/white, 
        210/{7\pi/6}/{-\frac{\sqrt{3}}2,-\frac{1}2}/below left/none, 
        225/{5\pi/4}/{-\frac{\sqrt{2}}2,-\frac{\sqrt{2}}2}/below left/none, 
        240/{4\pi/3}/{-\frac{1}{2},-\frac{\sqrt{3}}{2}}/below left/none,
        270/{3\pi/2}/{0,-1}/below/white, 
        300/{5\pi/3}/{\frac{1}2,-\frac{\sqrt{3}}{2}}/below right/none, 
        315/{7\pi/4}/{\frac{\sqrt{2}}{2},-\frac{\sqrt{2}}2}/below right/none, 
        330/{11\pi/6}/{\frac{\sqrt{3}}{2},-\frac{1}2}/below right/none%
          }
	{%
  \draw (\x:.65cm) node [fill=\v] {\scriptsize \x$^\circ$};
  \draw (\x:.85cm) node [fill=\v] {\scriptsize $\y$};
  \draw (\x:1cm) node [\w,fill=\v] {\scriptsize $(\z)$};
  \draw [fill=black] (\x:1) circle (.5pt);
	}

\draw [thick] (0,0) circle (1);
\end{tikzpicture}
```

### Definitions of the Trigonometric Functions {-}

### Unit Circle Definition {-}

```{tikz trigcircle, dev="svg", echo=FALSE, cache=TRUE, fig.width=NULL}
\begin{tikzpicture}[>=latex,scale=1.5,thick]
\draw [<->](-1.3,0)--(1.3,0) node [right] {$x$};
\draw [<->] (0,-1.3) -- (0,1.3) node [above] {$y$};
\draw (0,0) circle (1);
\draw [fill= black] (-.6,.8) circle (1pt);
\draw (0,0) -- (-.6,.8) node [above left] {$(x,y)$};
\draw [->] (.5,0) arc (0:127:.5);
\draw [dashed,thin] (-.6,.8) -- (-.6,0) node [pos=.5,left] {$y$};
\draw (-.3,0) node [below] {$x$};
\draw (.45,.45) node {$\theta$};
\end{tikzpicture}
```

\begin{tabular}{cc}
$\sin \theta = y$ & $\cos \theta = x$ \\
\\
$\ds\csc \theta = \frac1y$&$\ds\sec \theta = \frac1x$ \\
\\
$ \ds\tan \theta = \frac yx$ & $\ds\cot \theta = \frac xy$
\end{tabular}


### Right Triangle Definition {-}

```{tikz rttriangle, dev="svg", echo=FALSE, cache=TRUE, fig.width=NULL}
\begin{tikzpicture}[thick]
\draw (0,0) -- (2.5,0) node [below,pos=.5] {Adjacent} -- (2.5,2) node [pos=.5,rotate=-90,shift={(0pt,7pt)}] {Opposite} -- (0,0) node [pos=.5,above,rotate=38.7] {Hypotenuse} node [shift={(20pt,8pt)}] {$\theta$};
\draw[->,>=latex] (1,0) arc (0:38.7:1);
\draw (2.2,0) -- (2.2,.3) -- (2.5,.3);
\end{tikzpicture}
```

\begin{tabular}{cc}
$\ds\sin \theta = \frac{\text{O}}{\text{H}}$ & $\ds\csc \theta = \frac{\text{H}}{\text{O}}$ \\
\\
$\ds\cos \theta = \frac{\text{A}}{\text{H}}$ & $\ds\sec \theta = \frac{\text{H}}{\text{A}}$ \\
\\
$\ds\tan \theta = \frac{\text{O}}{\text{A}}$ & $\ds\cot \theta = \frac{\text{A}}{\text{O}}$ \\
\end{tabular}

### Common Trigonometric Identities {-}

### Pythagorean Identities {-}

  $\ds \sin ^2x+\cos ^2x= 1$ 

  $\ds \tan^2x+ 1 = \sec^2 x$ 

  $\ds 1 + \cot^2x=\csc^2 x$ 

### Cofunction Identities {-}


  $\ds \sin\left(\frac{\pi}{2}-x\right) = \cos x$ 
  $\ds \cos\left(\frac{\pi}{2}-x\right) = \sin x$ 
  $\ds \tan\left(\frac{\pi}{2}-x\right) = \cot x$ 
  $\ds \csc\left(\frac{\pi}{2}-x\right) = \sec x$ 
  $\ds \sec\left(\frac{\pi}{2}-x\right) = \csc x$ 
  $\ds \cot\left(\frac{\pi}{2}-x\right) = \tan x$ 

### Double Angle Formulas {-}
  $\sin 2x = 2\sin x\cos x$  
  $\cos 2x = \cos^2x - \sin^2 x$ 
  $\phantom{\cos 2x}= 2\cos^2x-1$ 
  $\phantom{\cos 2x}= 1-2\sin^2x$ 
  $\ds\tan 2x = \frac{2\tan x}{1-\tan^2 x}$

### Sum to Product Formulas {-}

$\ds \sin x+\sin y = 2\sin \left(\frac{x+y}2\right)\cos\left(\frac{x-y}2\right)$ 
$\ds \sin x-\sin y = 2\sin \left(\frac{x-y}2\right)\cos\left(\frac{x+y}2\right)$ 
$\ds \cos x+\cos y = 2\cos \left(\frac{x+y}2\right)\cos\left(\frac{x-y}2\right)$ 
$\ds \cos x-\cos y = -2\sin \left(\frac{x+y}2\right)\sin\left(\frac{x-y}2\right)$ 

### Power--Reducing Formulas {-}

$\ds \sin^2 x = \frac{1-\cos 2x}{2}$ 
$\ds \cos^2 x = \frac{1+\cos 2x}{2}$ 
$\ds \tan^2x = \frac{1-\cos 2x}{1+\cos 2x}$
 
 
### Even/Odd Identities  {-}
$\sin(-x) = -\sin x$ 
$\cos (-x) = \cos x$ 
$\tan (-x) = -\tan x$ 
$\csc(-x) = -\csc x$ 
$\sec (-x) = \sec x$ 
$\cot (-x) = -\cot x$ 
 

 
### Product to Sum Formulas {-}
$\ds \sin x\sin y = \frac12 \big(\cos(x-y) - \cos (x+y)\big)$ 
$\ds \cos x\cos y = \frac12\big(\cos (x-y) +\cos (x+y)\big)$ 
$\ds \sin x\cos y = \frac12 \big(\sin(x+y) + \sin (x-y)\big)$ 
 
 
### Angle Sum/Difference Formulas  {-}
$\sin (x\pm y) = \sin x\cos y \pm \cos x\sin y$ 
$\cos (x\pm y) = \cos x\cos y \mp \sin x\sin y$ 
$\ds \tan (x\pm y) = \frac{\tan x\pm \tan y}{1\mp \tan x\tan y}$
 

###   Areas and Volumes {-}
 
%\begin{tabular}{cc}
 %
%
 
   
### Triangles {-}

  $h=a\sin \theta$ 
  
  Area = $\frac12bh$ 
  
  Law of Cosines:
  
  $c^2=a^2+b^2-2ab\cos \theta$ 
   
```{tikz triangle, dev="svg", cache=TRUE, fig.width=NULL, echo=FALSE}
    \begin{tikzpicture}[x=30pt,y=30pt,thick]
    \draw (0,0) -- node [below,pos=.5]  { $b$} (3,0) node [shift={(-15pt,8pt)}] {$\theta$} -- node [pos=.5,right] { $a$} (2,1.5) -- node [pos=.5,above left] { $c$} (0,0);
    \draw (2.7,0) arc (180:125:.3);
    \draw [dashed] (2,1.5) -- (2,0) node [pos=.5,left] {$h$};
    \draw (2,.2) -- (1.8,.2) -- (1.8,0);
    \end{tikzpicture}
```   

### Right Circular Cone {-}
  Volume = $\frac 13 \pi r^2h$  
  Surface Area = $\pi r\sqrt{r^2+h^2} +\pi r^2$
   
```{tikz circlecone, dev="svg", cache=TRUE, fig.width=NULL, echo=FALSE}
    \begin{tikzpicture}[x=13pt,y=15pt,thick]
    \begin{scope}[xscale=2]
    \draw (-1,0) arc (-180:0:1);
    \draw [dashed] (1,0) arc (0:180:1);
    \draw (-1,.1) -- (0,3) -- (1,.15);
    \draw [dashed] (0,3) -- node [pos=.5,left] {\small $h$} (0,0);
    \draw [dashed] (0,0) -- (1,0) node [pos=.5,above] {\small $r$};
    \end{scope}
    \draw [fill=black] (0,0) circle (1pt);
    \end{tikzpicture}
```   
 

### Parallelograms {-}
  Area = $bh$

```{tikz parallelogram, dev="svg", cache=TRUE, fig.width=NULL, echo=FALSE}
    \begin{tikzpicture}[x=30pt,y=25pt,thick]
    \draw (0,0) -- node [below,pos=.5]  { $b$} (2,0) -- (3,1.5) -- (1,1.5) -- (0,0);
    \draw [dashed] (1,1.5) -- (1,0) node [pos=.5,right] {$h$};
    \draw (.8,0) -- (.8,.2) -- (1,.2);
    \end{tikzpicture}
```
   
 
 
### Right Circular Cylinder {-}

  Volume = $\pi r^2h$  

  Surface Area = $2\pi rh  +2\pi r^2$

```{tikz cylinder, dev="svg", cache=TRUE, fig.width=NULL, echo=FALSE}
    \begin{tikzpicture}[x=13pt,y=14pt,thick]
    \begin{scope}[xscale=2]
    \draw (-1,0) arc (-180:0:1);
    \draw [dashed] (1,0) arc (0:180:1);
    \draw (0,2.5) circle (1);
    \draw (-1,0) -- (-1,2.5) (1,0)-- (1,2.5) node [right,pos=.5] {$h$};
    \draw (0,2.5) -- (1,2.5) node [above,pos=.5] {$r$};
    \end{scope}
    \draw [fill=black] (0,2.5) circle (1pt);
    \end{tikzpicture}
```   
  
### Trapezoids {-}
  Area = $\frac12(a+b)h$

```{tikz trapezoid, dev="svg", cache=TRUE, fig.width=NULL, echo=FALSE}    
    \begin{tikzpicture}[x=30pt,y=25pt,thick]
    \draw (0,0) -- node [below,pos=.7]  { $b$} (3,0) -- (2.5,1.5) -- node [above,pos=.5] {$a$} (1.5,1.5) -- (0,0);
    \draw [dashed] (1.5,1.5) -- (1.5,0) node [pos=.5,right] {$h$};
    \draw (1.3,0) -- (1.3,.2) -- (1.5,.2);
    \end{tikzpicture}
```   
 
 
 
### Sphere {-}
  Volume = $\frac43\pi r^3$  
  Surface Area =$4\pi r^2$
   
```{tikz sphere, dev="svg", cache=TRUE, fig.width=NULL, echo=FALSE}
    \begin{tikzpicture}[x=13pt,y=13pt,thick]
    \begin{scope}[xscale=2]
    \draw (-1,0) arc (-180:0:1);
    \draw [dashed] (1,0) arc (0:180:1);
    \end{scope}
    \draw (0,0) circle (2);
    \draw [dashed] (0,0) -- (2,0) node [pos=.5,above] {$r$};
    \draw [fill=black] (0,0) circle (1pt);
    \end{tikzpicture}
```   
 
### Circles {-}
  Area = $\pi r^2$ 
  Circumference = $2\pi r$
   
```{tikz circles, dev="svg", cache=TRUE, fig.width=NULL, echo=FALSE}
    \begin{tikzpicture}[x=30pt,y=30pt,thick]
    \draw (0,0) circle (1);
    \draw [dashed] (0,0) -- (1,0) node [pos=.5,above] {$r$};
    \draw [fill=black] (0,0) circle (1pt);
    \end{tikzpicture}
   
```
 
 
### General Cone {-}
  Area of Base = $A$ 
  Volume = $\frac13Ah$  
   
```{tikz cone, dev="svg", cache=TRUE, fig.width=NULL, echo=FALSE}
    \begin{tikzpicture}[x=13pt,y=10pt,thick]
    \begin{scope}
    \clip (0,0) rectangle (4,-2.5);
    \draw [smooth] plot coordinates {(0,0) (1,1.5) (2,1.5) (4,0) (3,-1) (2,-1.5) (1,-2) (0,0)};
    \end{scope}
    \begin{scope}
    \clip (0,0) rectangle (4,2.5);
    \draw [smooth,dashed] plot coordinates {(0,0) (1,1.5) (2,1.5) (4,0) (3,-1) (2,-1.5) (1,-2) (0,0)};
    \end{scope}
    \draw (0,0) -- (2,4)--(4,0);
    \draw [dashed] (2,0)--(2,4) node [pos=.5,right] {$h$}; 
    \draw [fill=black](2,0) circle (1pt);
    \draw (1.5,-.75) node {$A$};
    \end{tikzpicture}
   
``` 

 
   
### Sectors of Circles {-}

  $\theta$ in radians  
  Area = $\frac12\theta r^2$ 
  $s=r\theta$
   
```{tikz sectors, dev="svg", cache=TRUE, fig.width=NULL, echo=FALSE}
    \begin{tikzpicture}[x=30pt,y=30pt,thick]
    \draw (2,0) arc (0:50:2) -- (0,0);
    \draw [] (0,0) -- (2,0) node [pos=.5,below] {$r$};
    \draw [fill=black] (0,0) circle (1pt);
    \draw (1.95,1.0) node {$s$};
    \draw (0,0) node [shift={(15pt,8pt)}] {$\theta$};
    \end{tikzpicture}
```   
 
 
 
### General Right Cylinder {-}

  Area of Base = $A$ 
  Volume = $Ah$  
   
```{tikz generalcylinder, dev="svg", cache=TRUE, fig.width=NULL, echo=FALSE}
\begin{tikzpicture}[x=13pt,y=10pt,thick]
    \begin{scope}
    \clip (0,0) rectangle (4,-2.5);
    \draw [smooth] plot coordinates {(0,0) (1,1.5) (2,1.5) (4,0) (3,-1) (2,-1.5) (1,-2) (0,0)};
    \end{scope}
    \begin{scope}
    \clip (0,0) rectangle (4,2.5);
    \draw [smooth,dashed] plot coordinates {(0,0) (1,1.5) (2,1.5) (4,0) (3,-1) (2,-1.5) (1,-2) (0,0)};
    \end{scope}
    \begin{scope}[shift={(0,4)}]
    \draw [smooth] plot coordinates {(0,0) (1,1.5) (2,1.5) (4,0) (3,-1) (2,-1.5) (1,-2) (0,0)};
    \end{scope}
    \draw (0,0) -- (0,4) (4,0) -- (4,4) node [pos=.5,right] {$h$};
    \draw (2,0) node {$A$};
    \end{tikzpicture}
```   
 

###   Algebra {-}

###   Factors and Zeros of Polynomials {-}
Let $p(x) = a_n x^n + a_{n-1} x^{n-1} + \cdots + a_1 x + a_0$ be a polynomial.  If $p(a)=0$, then $a$ is a $zero$ of the polynomial and a solution
of the equation $p(x)=0$.  Furthermore, $(x-a)$ is a $factor$ of the polynomial.


###   Fundamental Theorem of Algebra {-}
An $n$th degree polynomial has $n$ (not necessarily distinct) zeros.  Although all of these zeros may be imaginary, a real polynomial of odd degree
must have at least one real zero.

###   Quadratic Formula {-}
If $p(x) = ax^2 + bx + c$, and $0 \le b^2 - 4ac$, then the real zeros of $p$ are $x=(-b\pm \sqrt{b^2-4ac})/2a$\\
 

###   Special Factors} {-}

$$
\begin{array}{ll}
x^2 - a^2 = (x-a)(x+a) \qquad \qquad \qquad & x^3 - a^3 = (x-a)(x^2+ax+a^2)\\  
x^3 + a^3 = (x+a)(x^2-ax+a^2) \qquad \qquad \qquad & x^4 - a^4 = (x^2-a^2)(x^2+a^2)\\
\end{array}
$$

$$
\begin{array}{l}
(x+y)^n  =x^n + nx^{n-1}y+\frac{n(n-1)}{2!}x^{n-2}y^2+\cdots +nxy^{n-1}+y^n\\
(x-y)^n  =x^n - nx^{n-1}y+\frac{n(n-1)}{2!}x^{n-2}y^2-\cdots \pm nxy^{n-1}\mp y^n
\end{array}
$$ 


###   Binomial Theorem} {-}
$$
\begin{array}{ll}
(x+y)^2 = x^2 + 2xy + y^2 \qquad & (x-y)^2 = x^2 -2xy +y^2\\
(x+y)^3 = x^3 + 3x^2y + 3xy^2 + y^3 \qquad  & (x-y)^3 = x^3 -3x^2y + 3xy^2 -y^3\\
(x+y)^4 = x^4 + 4x^3y + 6x^2y^2 + 4xy^3 + y^4 \qquad  & (x-y)^4 = x^4 - 4x^3y + 6x^2y^2 - 4xy^3 + y^4\\
\end{array}
$$

###   Rational Zero Theorem} {-}
If $p(x) = a_n x^n + a_{n-1} x^{n-1} + \cdots + a_1 x + a_0$ has integer coefficients, then every $rational$ $zero$ of $p$ is of the form
$x=r/s$, where $r$ is a factor of $a_0$ and $s$ is a factor of $a_n$.
 

###   Factoring by Grouping  {-}

$ac x^3 + adx^2 + bcx + bd = ax^2(cx+d)+b(cx+d)=(ax^2+b)(cx+d)$
 

###   Arithmetic Operations  {-}

$
\begin{array}{lll}
ab+ac=a(b+c) \qquad \qquad & \displaystyle \frac{a}{b}+\frac{c}{d} = \frac{ad+bc}{bd} \qquad \qquad & \displaystyle \frac{a+b}{c} = \frac{a}{c} + \frac{b}{c}\\	\\
\displaystyle\frac{\left(\displaystyle\frac{a}{b}\right)}{\left(\displaystyle\frac{c}{d}\right)}=\left(\frac{a}{b}\right)\left(\frac{d}{c}\right)=\frac{ad}{bc} 
&\displaystyle \frac{\left(\displaystyle\frac{a}{b}\right)}{c} =\displaystyle \frac{a}{bc}
&\displaystyle \frac{a}{\left(\displaystyle\frac{b}{c}\right)} =\displaystyle \frac{ac}{b}\\ \\
a\left(\displaystyle\frac{b}{c}\right)= \displaystyle \frac{ab}{c}&\displaystyle\frac{a-b}{c-d}=\frac{b-a}{d-c}&\displaystyle\frac{ab+ac}{a}=b+c\\
\end{array}
$ 

### Exponents and Radicals {-}

$$
\begin{array}{llllll}
a^0=1, \; \; a \ne 0 \quad & (ab)^x=a^xb^x \quad & a^xa^y = a^{x+y}\quad  & \sqrt{a}=a^{1/2}   &\displaystyle \frac{a^x}{a^y}=a^{x-y}  &\sqrt[n]{a}=a^{1/n}\\[15pt]
\left(\displaystyle\frac{a}{b}\right)^x=\displaystyle\frac{a^x}{b^x} &\sqrt[n]{a^m}=a^{m/n} & a^{-x}=\displaystyle\frac{1}{a^x} & \sqrt[n]{ab}=\sqrt[n]{a}\sqrt[n]{b} \quad &
(a^x)^y=a^{xy} \quad& \displaystyle\sqrt[n]{\frac{a}{b}}=\frac{\sqrt[n]{a}}{\sqrt[n]{b}}
\end{array}
$$

###   Additional Formulas {-}

###   Summation Formulas  {-}

$\ds \sum^n_{i=1}{c} = cn$ \hskip 100pt\ & $\ds\sum^n_{i=1}{i} = \frac{n(n+1)}{2}$

$\ds\sum^n_{i=1}{i\hskip1pt^2} = \frac{n(n+1)(2n+1)}{6}$

$\ds\sum^n_{i=1}{i\hskip1pt^3}= \left(\frac{n(n+1)}{2}\right)^2$


###   Trapezoidal Rule  {-}

 $\ds \int_a^b{f(x)}\ dx  \approx \frac{\Delta x}{2}\big[f(x_1)+2f(x_2) + 2f(x_3) + \cdots + 2f(x_{n}) + f(x_{n+1})\big]$

with  $\displaystyle \text{Error} \leq \frac{(b-a)^3}{12n^2}\big[ \max \big|f''(x) \big|\big]$

###   Simpson's Rule  {-}

 $\ds\int_a^b{f(x)}\ dx  \approx  \frac{\Delta x}{3}\big[f(x_1)+4f(x_2) + 2f(x_3) + 4f(x_4) + \cdots + 2f(x_{n-1}) + 4f(x_{n}) + f(x_{n+1})\big] $
 
with $\displaystyle \text{Error} \leq \frac{(b-a)^5}{180n^4}\big[ \max \big| f^{(4)}(x) \big|\big]$
 

###   Arc Length  {-}

$\displaystyleL = \int_a^b{\sqrt{1+ f\,'(x)^2}}\phantom{a}dx  $



###   Surface of Revolution {-}
$\displaystyle S = 2\pi \int_a^b{f(x) \sqrt{1+ f\,'(x)^2}}\phantom{a}dx$
(where $f(x)\geq 0$)

$\displaystyle S = 2\pi \int_a^b{x \sqrt{1+ f\,'(x)^2}}\phantom{a}dx$
(where $a,b \geq 0$)
 



###   Work Done by a Variable Force  {-}

$\displaystyle W = \int_a^b{F(x)}\phantom{a}dx$
 

###   Force Exerted by a Fluid {-}

$\displaystyle F = \int_a^b{w\,d(y)\,\ell(y)}\phantom{a}dy$
 


###   Taylor Series Expansion for $f(x)$  {-}

$\displaystyle p_n(x) = f(c) + f\,'(c)(x-c) + \frac{f\,''(c)}{2!}(x-c)^2 + \frac{f\,'''(c)}{3!}(x-c)^3 + \cdots + \frac{f\,^{(n)}(c)}{n!}(x-c)^n + \cdots$


###   Maclaurin Series Expansion for $f(x)$, where $c=0$  {-}

$\displaystyle p_n(x) = f(0) + f\,'(0)x + \frac{f\,''(0)}{2!}x^2 + \frac{f\,'''(0)}{3!}x^3 + \cdots + \frac{f\,^{(n)}(0)}{n!}x^n+\cdots$




